### ISSUE TITLE
data portal dev ui insert and remove row feature issue

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#1001]
I was doing some testing in the submission portal yesterday and sometimes I can get the red box in the screen shot to show up which have options to delete a row, insert row above, insert row below. This useful to have but it is unclear what combination of scrolling and mousing makes these options appear, normally the page ends at the 'add 100 rows button' So the first part of this ticket is to understand how to make this feature appear. 

Second issue is clicking on delete row, when it does appear does not work. I was only able to delete a row by using the delete button on my keyboard.

cc @mslarae13 

platform/repoduction: submission portal dev on July 20, 2023 using Chrome version 112.0.5615.137

![20230721 submission portal row issues](https://github.com/microbiomedata/nmdc-server/assets/8196591/052680f9-34dc-46a6-b120-88855269180e)

**Comment by pkalita-lbl** [comment]
The options you're referring to are supposed to appear in a context menu when right-clicking on a cell or row number. This should be fixed now from the DataHarmonizer upgrade that was done for https://github.com/microbiomedata/submission-schema/issues/168. @aclum please test on dev and close if you think it looks good.

**Comment by aclum** [comment]
fixed in dev.
