### ISSUE TITLE
pi profile image isn't displaying on study page for ID nmdc:sty-11-db67n062

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#1003]
https://data-dev.microbiomedata.org/details/study/nmdc:sty-11-db67n062
I can confirm that the image is visible based on the nersc ftp site
PI name is Rebecca Lybrand

**Comment by naglepuff** [comment]
The data portal is failing to obtain this image during ingest.

This might be a permissions issue. It looks like the image is more restricted than all others in the NERSC filesystem, so I think we should start by updating that.

I'd like for the owner of the new file to change the permissions (`chmod`) to allow "others" to read it.

Most profile images have at least `-rw-r--r--`. The new image that isn't displaying has `-rw-rw----`. I don't have permission to do that on the NERSC filesystem. 

@aclum 
This issue should also be assigned to someone who does have the ability to change it. Once that part is complete I will rerun ingest and we will see if the issue still persists.

**Comment by aclum** [comment]
Ready for the next ingest
aclum@perlmutter:login08:/global/cfs/cdirs/m3408/www/profile_images> ls -ltr 7571-lybrand.jpg
-rw-rw-r-- 1 nmdcda m3408 49359 Feb  4  2021 7571-lybrand.jpg

**Comment by aclum** [comment]
Resolved, this was a permission issue
