### ISSUE TITLE
study page redesign -remove gray bar if there are no award dois or publications associated with a study page

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#1011]
When a study page doesn't have an award doi or associated records there is an empty gray bar on the top right of the study page. I suggest this have the same white color background as the rest of the page.  cc @lamccue @mslarae13 
<img width="1629" alt="Screenshot 2023-07-25 at 12 59 18 PM" src="https://github.com/microbiomedata/nmdc-server/assets/8196591/18bb0cb3-ecf5-4458-97a1-5daf9ff170ea">

**Comment by jeffbaumes** [comment]
Fixed in #1057

**Comment by mslarae13** [comment]
@pkalita-lbl  what we looked at this morning for your local view of the DP with TRiP had the grey box... is there an updated needed on your side?

**Comment by pkalita-lbl** [comment]
Yeah good catch. I wasn't actually running the latest version of the front-end code. I updated my local codebase and indeed, the box is gone:

![image](https://github.com/microbiomedata/nmdc-server/assets/102547565/b991a584-4a00-456a-a33e-9dfe9894e09f)
