### ISSUE TITLE
Support multivalue DOI slots

### ISSUE THREAD

**Issue by naglepuff** [microbiomedata/nmdc-server#1030]

**Comment by jeffbaumes** [comment]
@turbomam will help get @naglepuff sample data

**Comment by jeffbaumes** [comment]
Relates to https://github.com/microbiomedata/issues/issues/338

**Comment by ssarrafan** [comment]
@turbomam is at a conference so will move this to the next sprint
@naglepuff @marySalvi let me know if you are not actively working on this issue

**Comment by ssarrafan** [comment]
@naglepuff reported that he's almost done with this yesterday. Will move to next sprint to complete.

**Comment by ssarrafan** [comment]
Related to https://github.com/microbiomedata/nmdc-server/issues/1030
