### ISSUE TITLE
incorrect number of samples for NEON

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#1032]
When selecting for the neon soil study we get the expected numbers in the map feature, the upset plot and the number of omics records. However, the number of samples and their names appear to be the records that were loaded for GSP that no longer exist, Sujay deleted these a few weeks ago. The expect result from an active search query in DP prod for this study is 4204, it is currently showing 492.

query https://data.microbiomedata.org/?q=Ch4IABABGAMiFiJubWRjOnN0eS0xMS0zNHhqMTE1MCI=

<img width="1636" alt="Screenshot 2023-08-08 at 3 16 08 PM" src="https://github.com/microbiomedata/nmdc-server/assets/8196591/4cbeb611-5949-4400-9d36-3e164f65817d">

**Comment by aclum** [comment]
Results can be variable (internet is slow here at the conference center in Portland). Here it appears to pull from older data for the upset plot (expect result is 4172 and it is showing 492) and showing all biosamples(6734 instead of the expected 4202). I suspect a timeout issue for the biosample counts here.
<img width="1639" alt="Screenshot 2023-08-08 at 3 41 41 PM" src="https://github.com/microbiomedata/nmdc-server/assets/8196591/18314aad-7be6-4da5-93e8-421e48b1f6d6">

**Comment by aclum** [comment]
This was a screenshot @ssarrafan  took today, the map counts are not correct, expected results is 4204. Other counts are correct.
![Screen Shot 2023-08-08 at 3 48 11 PM](https://github.com/microbiomedata/nmdc-server/assets/8196591/af16d5bb-97a2-486b-944c-959848c32fe7)

**Comment by aclum** [comment]
<img width="1403" alt="map timeout issue" src="https://github.com/microbiomedata/nmdc-server/assets/8196591/80cdf15a-e953-442a-8b54-a7a5264300a3">
The NEON study should not have samples shown on the map outside of of the US and US territories. After applying the NEON study filter the map still shows samples from Africa for example.

**Comment by aclum** [comment]
cc @shreddd @pkalita-lbl @eecavanna

**Comment by marySalvi** [comment]
I think this has been fixed. One of the pods for the backend was pointing to the wrong db and giving very unstable results. Everything is pointing at the right db now. The lingering issue is to try to figure out how that pod wound up pointing to the wrong db.

**Comment by ssarrafan** [comment]
Closing this issue.
