### ISSUE TITLE
negative numbers for omics processing bar chart results

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#1033]
This has happened to me a few times and @emileyfadrosh has noticed this as well. Rarely when loading the data portal a negative number appears in the omics processing bar chart. The negative values are shown in a black bar chart vs the expected purple color used for positive counts.
![image](https://github.com/microbiomedata/nmdc-server/assets/8196591/08242c6f-292f-41ce-ade3-56fcfb22a970)

**Comment by aclum** [comment]
cc @ssarrafan @shreddd

**Comment by pkalita-lbl** [comment]
I believe this is a duplicate of #1032

**Comment by marySalvi** [comment]
> I believe this is a duplicate of #1032

I agree. I think this resulted from subtracting `nmdc_b` values from `nmdc_a` values giving negative numbers.

**Comment by aclum** [comment]
I’ve seen this about 3 times in the last 2 weeks or so. If it is from the diff of a and b databases that means we have issues with new instances being added with an incorrect configuration which span beyond the instance that launched yesterday morning.

**Comment by aclum** [comment]
The root cause of this was secrets in rancher that used a global namespace that resulted having two different versions of the database being used depending on the load balancer. This issues has not happened since the rancher secrets issue was addressed. see https://github.com/microbiomedata/nmdc-server/issues/1035
