### ISSUE TITLE
Data portal: search for biosample options

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#1046]
Add support in the data portal to search for biosample_set records by slots `name` or `description` or `id`

**Comment by aclum** [comment]
Per the infrastructure meeting on 4/18 Mary will work on this ticket this sprint.

**Comment by naglepuff** [comment]
here is the development that added the equivalent functionality for studies: https://github.com/microbiomedata/nmdc-server/pull/1068

**Comment by ssarrafan** [comment]
Appears active. Moving to new sprint for review. Please remove from sprint if not active.

**Comment by ssarrafan** [comment]
Mary reported that she has a PR that Mike needs to review at the infra sync yesterday. I'll move to in review status and the next sprint.

**Comment by aclum** [comment]
@marySalvi  can you check on this one? The PR automatic tests did not pass.
