### ISSUE TITLE
submission portal columns map incorrectly when importing a spreadsheet

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#1047]
Someone reported this to @emileyfadrosh in the workshop this morning and I was able to reproduce the problem in chrome using the 'soil' DH package. 
I filled out some metadata, clicked the download xlsx button, moved the gold ecosystem pathway columns to be before the environmental context terms, filled out some of those fields, then clicked import xlsx file and it imports the data without taking into account the column headers. Example file for import is attached. The correct behavior would be for the fields to be populated based on matching up the column headers, so `broad-scale environmental context `should be populated with
  `terrestrial biome [ENVO:00000446]` not `test`

[nmdc_sample_export test_mixed up rows.xlsx](https://github.com/microbiomedata/nmdc-server/files/12434108/nmdc_sample_export.test_mixed.up.rows.xlsx)

cc @pkalita-lbl

**Comment by pkalita-lbl** [comment]
I ran across this while testing changes for https://github.com/microbiomedata/issues/issues/543. There's a related issue where currently an extra column in the XLSX file will also cause import to fail. Fixing that and fixing the original issue described here about mixed-up columns is essentially the same so I'll use this issue to track it.
