### ISSUE TITLE
Sandbox Subportal is jumpy

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-server#1049]
We had a couple people at the workshop (& @lamccue ) experience the data harmonizer interface being jumpy. When they click on a cell the screen jumps to the left, highlights all the cells, and they can't edit the cell they were on. It also sometimes throws them to the bottom of the sheet when they select a cell.

Will ask Lee Ann to try and take a screen recording.

One of the people at the workshop provided these specs for their system
Version 109.0.5414.119 (Official Build) (x86_64)
Mac OS Big Sur
Version 11.6.8
Chrome  

            @pkalita-lbl  @naglepuff  This is happening again.... :( 

https://drive.google.com/file/d/108Bxn1mhWd23YTCKmFAm5ciz_QWcjShE/view?usp=sharing

_Originally posted by @mslarae13 in https://github.com/microbiomedata/nmdc-server/issues/916#issuecomment-1658954433_

Same issue was corrected in production. Needs fixed in sandbox.

**Comment by pkalita-lbl** [comment]
At the moment sandbox and production are running the same version of the frontend code; so there wouldn't be any obvious reason for them to behave differently. I used to (pre-fix for #916) be able to reproduce the issue that other people were seeing (or so I thought). But I can't reproduce it on sandbox currently. Someone might have to help me figure out the magic trick to see this behavior.

**Comment by mslarae13** [comment]
@pkalita-lbl  I'll poke around and see if it's still happening

**Comment by mslarae13** [comment]
I haven't noticed this issue. I'm going to close this issue and will re-open fi it happen again.
