### ISSUE TITLE
Submission portal: "Download XLSX" button doesn't download anything when using "miscellaneous natural or artificial environment" package

### ISSUE THREAD

**Issue by bmeluch** [microbiomedata/nmdc-server#1054]
The button click animates but nothing appears in downloads. I was able to download the Excel template with the headers when I selected "soil", so I don't believe it's my browser misbehaving.

**Comment by mslarae13** [comment]
@pkalita-lbl looks like Bea knew about this a long time ago!!! 
resolved here: https://github.com/microbiomedata/submission-schema/issues/213
