### ISSUE TITLE
return 404 not found response for unknown studies and samples

### ISSUE THREAD

**Issue by dwinston** [microbiomedata/nmdc-server#1058]
examples:
* https://data.microbiomedata.org/details/study/nmdc:sty-NotARealID
* https://data.microbiomedata.org/details/sample/nmdc:bsm-NotARealID

related to implementation of microbiomedata/issues#423

**Comment by naglepuff** [comment]
The first URL listed (`/details/study/nmdc:sty-NotARealID`) belongs to the Vue application router, so it should only be accessed from the Vue client.

The second URL is the preferred method of getting information out of the Data Portal's postgres database, and corresponds to an endpoint in our FastAPI backend. That one will throw the `404` you'd expect
