### ISSUE TITLE
Study page Component reorg

### ISSUE THREAD

**Issue by marySalvi** [microbiomedata/nmdc-server#1059]
- [x] Move 'Funding Sources' to PI Bio
- [x] Details
     - [x] Rename 'Study Details' to 'NMDC details'
     - [x] Only include ID and Sample count
     - [x] Make section one clickable, linked component with tooltip

- [x] Resources
     - [x] Rename 'External Resources' to 'Additional Resources'
     - [x] Restructure into the sub categories: 'Data', 'Protocols' and 'Links'
     - [x] Fix Field error
     - [x] Rename 'Open in Gold' to 'Gold Metadata'
- [x] Make study page responsive for common breakpoints

**Comment by ssarrafan** [comment]
This looks like it's almost done. Will move to the next sprint @marySalvi

**Comment by ssarrafan** [comment]
@marySalvi @lamccue @mslarae13 Can this be closed?

**Comment by ssarrafan** [comment]
Appears to be done but will double check with @marySalvi on Monday. Moving to next sprint to hopefully close.

**Comment by mslarae13** [comment]
@marySalvi  for the links, did we create new slots to capture links or just re-design where they're shown???

**Comment by marySalvi** [comment]
> @marySalvi for the links, did we create new slots to capture links or just re-design where they're shown???

I believe it was just a re-design. Are the links not currently being captured?

**Comment by ssarrafan** [comment]
Checked with Mary. Added 'ingest to prod needed' label and will close.
