### ISSUE TITLE
Do not require PI for Study in ingest code

### ISSUE THREAD

**Issue by brynnz22** [microbiomedata/nmdc-server#1063]
@naglepuff @marySalvi per today's discussion in the UFO squad, the ingest code should not require the PI  since PI is not applicable to umbrella consortia and studies. 

I removed the new studies I added to production, but I did not remove the changes I submitted via change sheet showing which studies are `part_of` the new studies. So right now the `part_of` slot for many studies includes identifiers that don't exist in production. What is the timeline for this fix? If it is a while, I will go ahead and submit a new change sheet removing the `part_of` values.

**Comment by ssarrafan** [comment]
@brynnz22 @mslarae13 is this high priority? Can we get this added to the Kitware list and prioritized.  https://docs.google.com/spreadsheets/d/1t3qTjQHkghSZqb1Bvaq6NGRzyeNXHonTaZredBtoo-M/edit#gid=0

**Comment by mslarae13** [comment]
@ssarrafan I started to add it. Need to finish the details

**Comment by brynnz22** [comment]
@naglepuff does closing this mean it is okay for me to add the new umbrella studies/consortia back to production MongoDb?

**Comment by naglepuff** [comment]
@brynnz22 I think we should wait until #1067 is merged first. That will fix rendering the study pages for the new umbrella/consortia. 

@marySalvi I'll have time to review that PR by the end of the week.

Once that's merged I think we should consider pointing dev ingest at dev mongo to demo the changes before making a release and moving those studies back to production mongo.
