### ISSUE TITLE
Handle study/consortium page with no PI information

### ISSUE THREAD

**Issue by naglepuff** [microbiomedata/nmdc-server#1064]
Related to #1063

**Comment by mslarae13** [comment]
Checked in with @marySalvi  done. Can we close?

**Comment by mslarae13** [comment]
@naglepuff @marySalvi is this done? I don't remember moving it to the done column, but I did! But it isn't closed.

**Comment by mslarae13** [comment]
@naglepuff & @marySalvi this was in the 'done' column for the study page squad board, but the issue is still open. 
I think this is done & can be closed. Can you confirm?

**Comment by ssarrafan** [comment]
Mike and Mary confirmed this can be closed at the infra sync meeting today.  Closing issue.
