### ISSUE TITLE
KEGG search results should only display products from which the KEGG hit comes from

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#1072]
**Is your feature request related to a problem? Please describe.**
When searching by a KEGG search term it should only products where it makes sense to have KEGG results (metagenome, metatranscriptome, and proteomics) 
Example (https://data-dev.microbiomedata.org/?q=Ch8IABAAGAEiFyJLRUdHLk9SVEhPTE9HWTpLMDAwMDki)

**Describe the solution you'd like**
A metagenome sample has a hit to the KEGG term and also has a metatranscriptome with no KEGG hit and metabolomics the sample results should only show the metagenome product. The count of metagenomes at the study level should be the number of metagenomes in that study that have the KEGG term, not the total number of metagenome projects in the entire study. 
Minimum requirement for GSP would be to hid metabolomics and natural organic matter results for studies and samples

**Describe alternatives you've considered**
Minimum requirement for GSP would be to hid metabolomics and natural organic matter results for studies and samples

**Acceptance Criteria**
Search by KEGG term  shows the number of projects within a study that have hits and only those with products. At the sample level only show products with the KEGG hit.
![Screenshot 2023-03-30 at 7 47 23 PM](https://user-images.githubusercontent.com/8196591/229011064-890d2550-e90f-4d68-8d0f-191b05092de1.png)

**Comment by naglepuff** [comment]
@aclum feel free to add it to the sprint and I'll start taking a closer look at this. I think this might end up being a hefty change. I'll take some time starting next week to scope out the actual scale.

**Comment by emileyfadrosh** [comment]
thanks @aclum @naglepuff. 

Just confirming that the desired behavior from @aclum's comment 3 weeks ago that only products that have kegg terms as part of their output (metagenomics, metatranscriptomics, and metaproteomics) should be included. No NOM data should not be shown. thanks!

**Comment by naglepuff** [comment]
Closed by #1075

**Comment by naglepuff** [comment]
@aclum please add active query terms that had a weird result. I'll take a look at the queries to diagnose.

**Comment by naglepuff** [comment]
Note to self: take a look at https://github.com/microbiomedata/nmdc-server/blob/main/nmdc_server/query.py#L340-L356

This might not be the explanation to either of the problems that are still ongoing with combining KEGG and omics type searches, but it's a place to start.

**Comment by aclum** [comment]
Active query terms were omics type = metatranscriptome and kegg term = K00005
The first issue was in the study section it returned GROW even though there are no metatranscriptome annotation records for this study.
The second issue was that the query returned 11 omics records but 45 samples. Here I suspect an OR query is being executed instead of an AND query b/c there are 45 metatranscriptome omics projects & the same number of samples for study id gold:Gs0135149

![Image](https://github.com/microbiomedata/nmdc-server/assets/8196591/9f580519-0a6c-4ef6-933e-16d25f473763)

**Comment by aclum** [comment]
actively being worked on, move to the next sprint if not closed by COB tomorrow.

**Comment by naglepuff** [comment]
We discussed this issue in depth at the infra sync meeting 11/9/23.

To summarize (@aclum and @jeffbaumes please add and info as you see fit):

The search in the screenshot above (KEGG 00005, omics_type=metaT) displays results that are _technically_ correct (the best kind of correct), although not what a user may expect to see.

A biosample matches this particular search if:

1. Any omics processing record associated with the biosample has type "metatranscriptome"
2. Any omics processing record associated with the biosample generated a KEGG term K00005

Note that these do NOT have the be the same omics processing record. 

This is also true of studies, and the reason that GROW appears as part of this search.

So our search is valid for 11 omics processing records, 2 study records, and 45 biosample records.

A better behavior might be to default to the lowest-level search, i.e. omics processing, and only include results of other types that are related to those.

The next step for this will be to investigate an approach to do that kind of search, and come up with an estimated effort for that.

**Comment by jeffbaumes** [comment]
This matches my understanding, thanks @naglepuff .

**Comment by aclum** [comment]
Per the infrastructure meeting Mike the fixes the study filtering are in dev and will get pushed to prod  in the next release. Addressing the issues with were brought up last week (a search that intersects on omics and KEGG) were looked into and it was determined this should be backlogged until more is known about the schema refactor scheduled for December.

**Comment by aclum** [comment]
This filter is an example of where advanced search still isn't working.
https://data-dev.microbiomedata.org/?q=CgkIBxAVGAQiATkKHggAEAEYAyIWIm5tZGM6c3R5LTExLTV0Z2ZyMzQ5Ig==
The metagenome count decreases for GROW as expected but the NOM count doesn't under the studies section (699 vs expected 131). Metatranscriptomes are showing up for the Crested Butte study (gold:Gs0135149) summary even though there is a omics filter of MG and NOM applied.

Also I mentioned this over slack but I'll put here as well. The sample level is not filtering as expected.
Can you make it so that results are only shown when that workflow produces a result? (ie metabolomics & proteomics should not be shown under samples for a search for KEGG 00005 b/c none are shown in the study summary)

**Comment by jeffbaumes** [comment]
> This filter is an example of where advanced search still isn't working.
[data-dev.microbiomedata.org/?q=CgkIBxAVGAQiATkKHggAEAEYAyIWIm5tZGM6c3R5LTExLTV0Z2ZyMzQ5Ig==](https://data-dev.microbiomedata.org/?q=CgkIBxAVGAQiATkKHggAEAEYAyIWIm5tZGM6c3R5LTExLTV0Z2ZyMzQ5Ig==)
The metagenome count decreases for GROW as expected but the NOM count doesn't under the studies section (699 vs expected 131).

For me the GROW NOM count does go down to 557 (from 699 total) when I click your link. I believe that count is much higher for NOM because each sample can have many NOM analyses attached.

> Metatranscriptomes are showing up for the Crested Butte study (gold:Gs0135149) summary even though there is a omics filter of MG and NOM applied.

For this I believe we'd need to define what clicking on the upset chart means. Long ago I remember discussing this and we decided that when a user clicks on a paired-analysis row we want to return samples with **at least** those analyses (i.e. there could be more). Since that upset plot filter only filters samples and not analyses, we currently keep the MG-MT-NOM row as well when we click on the [MG-NOM row](https://data-dev.microbiomedata.org/?q=CgkIBxAVGAQiATk=) and don't hide the fact that there are some with MT. So those 43 MT are from samples that match the user search (have MG and NOM).

<img width="741" alt="image" src="https://github.com/microbiomedata/nmdc-server/assets/81305/e8c386c5-b21e-4fb0-99e4-1f45c7ce0d2f">

All can be changed, I just wanted to give the history here.

**Comment by aclum** [comment]
Thanks for the context Jeff. I'm going to close this and spin these into separate tickets which will be post-GSP activities.
