### ISSUE TITLE
Implement locking for metadata submissions

### ISSUE THREAD

**Issue by naglepuff** [microbiomedata/nmdc-server#1076]
Part of #824 

Currently, we don't have a robust set of role based access controls for metadata submissions to the NMDC Submission Portal. Part of implementing these permissions will be introducing some sort of record locking to prevent concurrent edits of a submission.

Implementation of locking is NOT blocked by permissions, since all users marked as "Admins" already have access to all submissions. Therefore, testing of these locks can be done independently of the actual role based permissions.

It might be a good idea to start with this.

**Comment by naglepuff** [comment]
This is actively being worked on. Please move to the next sprint

**Comment by ssarrafan** [comment]
Based on the infra sync meeting yesterday I'm moving this to the next sprint. FYI @mslarae13 @naglepuff

**Comment by ssarrafan** [comment]
Appears to be active (ready for review?). I'll move to the next sprint.  @naglepuff let me know if this should be in the backlog.

**Comment by naglepuff** [comment]
This is in review and can be moved to the next sprint
