### ISSUE TITLE
Edit Contributor Permissions on Metadata Submissions

### ISSUE THREAD

**Issue by naglepuff** [microbiomedata/nmdc-server#1077]
Part of #824 

Due 02/09 (in dev)

This represents the front-end changes and API changes for a role based access control system on metadata submissions. The plan is to add fields to the "Study Info" step of the submission wizard in the "Contributors" section, i.e.

![image](https://github.com/microbiomedata/nmdc-server/assets/7085625/d8d27487-4f35-46f8-b087-33c73878a88a)

Roles can only be added for a contributor if an ORCID iD is provided. This is the easiest way to link users and roles for the time being.

The role that a user has for a submission will also influence which sections of the submission they can interact with. See https://docs.google.com/spreadsheets/d/18tN1_KlQFHq1FFaBTT3zzusEn57tkidAfj-3nC5wDfM/edit#gid=235041042 for more details.

**Comment by ssarrafan** [comment]
@naglepuff @mslarae13 @shreddd is this one of the tasks that Mike will be working on next sprint? Or is this part of the ORCID auth work that's not slated for the next sprint?

**Comment by mslarae13** [comment]
@ssarrafan this is Mike's next task, post completing the hide and seek / KEGG stuff he's working on for Alicia.... but I'l llet @naglepuff confirm

**Comment by ssarrafan** [comment]
@naglepuff any update on this issue?

**Comment by naglepuff** [comment]
This issue depends on #1078, so it won't be completed this sprint.

**Comment by ssarrafan** [comment]
I'll move to the next sprint. @mslarae13 @shreddd if this is not going to be the top priority please let me know or remove from the sprint.

**Comment by naglepuff** [comment]
@ssarrafan I've added this issue to Sprint 29, which is more descriptive of the work that is being represented by #824 in the current sprint, since that issue is more of a meta-issue. Sorry for any confusion. Once this issue is closed, #824 can be closed as well, since this is the last part of that meta-issue.

**Comment by ssarrafan** [comment]
Appears to be active. Moving to current sprint. 
@naglepuff
