### ISSUE TITLE
Add cron jobs to do automatic ingest

### ISSUE THREAD

**Issue by pkalita-lbl** [microbiomedata/nmdc-server#1079]
As proposed in the Release Management Squad, it would be useful to do periodic, automatic ingests from Mongo. This would have a few benefits:

* On dev (assuming ingest is done from the dev Mongo deployment -- which is not currently the case!) a failing daily ingest would give us an earlier heads-up if the ingest code needs to be updated to accommodate recent runtime changes.
* On production (assuming ingest is done from the production Mongo deployment which is more stable see https://github.com/microbiomedata/nmdc-runtime/issues/357) a weekly ingest would alleviate the need for team members to make and respond to one-off requests for ingest. 

Most of the ingest is already pretty well-automated (either via the API or CLI). The manual steps currently are doing the A/B database swap and restarting the service in Rancher. I assume those can be automated via the Rancher CLI.

**Comment by eecavanna** [comment]
I ran into some User ID-related issues when trying to set up a CronJob recently. Here's a link to my notes about it: https://github.com/microbiomedata/infra-admin/issues/27#issuecomment-1863740052

**Comment by ssarrafan** [comment]
Sprint over, no updates, removing from sprint and adding backlog label.  If still active please move to new sprint.
