### ISSUE TITLE
Switch to ORCID Member Credientials

### ISSUE THREAD

**Issue by shreddd** [microbiomedata/nmdc-server#1082]
We need to switch the data portal to using ORCID member credentials. 

From Mary Beth West / OSTI 
```
For production, you should have access to a configuration page to what you see now re: ORCID’s developer tools.

Also, we just received the approval from ORCID to move forward with your production credentials request.

You can submit your request for your production credentials here: 
https://info.orcid.org/register-a-client-application-production-member-api/
```
 
Steps below:
- [ ] Check on use of /openid scope, and see if that needs code changes
- [x] Working session to submit registration form
- [x] Test new credentials in dev
- [x] Deploy new credentials to prod

**Comment by ssarrafan** [comment]
@shreddd @naglepuff  based on infra sync meeting yesterday I'm removing this from the sprint and adding the backlog label to it.

**Comment by shreddd** [comment]
@naglepuff - Can this be closed?

**Comment by naglepuff** [comment]
Yes, sorry for the delay.

**Comment by shreddd** [comment]
Openid will be done separately in #1096
