### ISSUE TITLE
Switch to tokens with OpenID scope 

### ISSUE THREAD

**Issue by shreddd** [microbiomedata/nmdc-server#1096]
Adjust the authentication flow to add scope openid - this will get us JWTs in the openid format that includes additional details like issued_at which will allow us to enforce expiration as per issue #1095

**Comment by shreddd** [comment]
Note: This can be post GSP

**Comment by naglepuff** [comment]
I did some testing locally regarding the first bullet point above. It looks like this can be done by changing the environment variable in out deployments to just use space-delimited scopes, (e.g. `"/read-limited openid"`)

Looks to me like this "just works" without any code changes to `nmdc-server`.

Haven't investigated expiration yet.

**Comment by shreddd** [comment]
OK - is this change already pushed to rancher?

**Comment by ssarrafan** [comment]
Checked with Shreyas and changed the status to in progress and moved to current sprint.

**Comment by ssarrafan** [comment]
@naglepuff @shreddd what's the status of this issue?  I'm going to remove from the sprint but let me know if it's still active.

**Comment by naglepuff** [comment]
I switched the scopes on Rancher but have not updated `nmdc-server` code to do anything special with the new tokens.

@shredd should we close this out and use new issues to track follow-up tasks?

**Comment by shreddd** [comment]
OK - let's close this out and I'll start a new issue.

**Comment by shreddd** [comment]
This was closed and additional work will be tracked in #1146 and #1095
