### ISSUE TITLE
Add search by data object

### ISSUE THREAD

**Issue by jbeezley** [microbiomedata/nmdc-server#110]
![data_objects1](https://user-images.githubusercontent.com/31890/88670197-c40a8000-d0b2-11ea-9578-d91687a487dd.png)
![dataobjects2](https://user-images.githubusercontent.com/31890/88670205-c4a31680-d0b2-11ea-81d4-e43b97f575eb.png)

**Comment by subdavis** [comment]
Issue out of date.
