### ISSUE TITLE
UI: Study icon looks like industrial landscape to some users

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-server#1102]
For the past 6 months, I have thought this was an industrial landscape with smokestacks.

![image](https://github.com/microbiomedata/nmdc-server/assets/134325062/e592e6ea-34e2-461a-92e0-5181067901e5)

I had been mistaking it for this FontAwesome icon: 
- https://fontawesome.com/icons/industry?f=classic&s=solid

<img width="251" alt="image" src="https://github.com/microbiomedata/nmdc-server/assets/134325062/18259a6a-9a99-47de-b4bb-f596fe5ac973">

**Comment by aclum** [comment]
Closing due to low priority.
