### ISSUE TITLE
Enable ORCID token based authentication to Submission Portal API

### ISSUE THREAD

**Issue by shreddd** [microbiomedata/nmdc-server#1104]

**Comment by shreddd** [comment]
This is to support autheticated access from
- NMDC Field Notes App
- NMDC Edge

Client requests will need to create submission portal entries by passing in an ORCID token to the API. 
Issue needs to be fleshed out in auth squad meeting.

**Comment by ssarrafan** [comment]
Checked with Shreyas and changing status to in progress.
