### ISSUE TITLE
Data portal says "0 results" while loading data (for several seconds)

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-server#1131]
When I visit https://data.microbiomedata.org/, I see "Found 0 results." for several seconds. Eventually, it changes to "Found 7978 results."

<img width="771" alt="image" src="https://github.com/microbiomedata/nmdc-server/assets/134325062/51a89c62-0596-409c-be02-3f2d519a6adb">

I recommend not showing a number of results until the app has determined the number of results, which might be the same instant at which it is already ready to show the results, themselves. Instead of showing a number, the app could say, "Loading results..." or something else that lacks a number.

**Comment by ssarrafan** [comment]
@eecavanna is this one that can be done post GSP?

**Comment by eecavanna** [comment]
Yes, it is.

**Comment by aclum** [comment]
Is this related to what @marySalvi  was working on this sprint?

**Comment by eecavanna** [comment]
Whoops! I forgot about this ticket.

>Is this related to what @marySalvi was working on this sprint?

I don't know. It don't remember hearing about this issue/topic in recent conversations (but it might have come up during a meeting I wasn't in).

**Comment by eecavanna** [comment]
I looked into this for a few minutes just now. Here are some notes for when I work on it next:

Here's where the `Found 0 results.` message is defined in `SearchSidebar.vue`:

https://github.com/microbiomedata/nmdc-server/blob/c15d511698117b45fc27105ad0f1bb25d39e6134/web/src/views/Search/SearchSidebar.vue#L200-L202

The variable, `resultsCount`, is a "prop" to the `SearchSidebar` component. That component is only used in `SearchLayout.vue`:

https://github.com/microbiomedata/nmdc-server/blob/c15d511698117b45fc27105ad0f1bb25d39e6134/web/src/views/Search/SearchLayout.vue#L204-L207

(Still new to Vue) I assume Vue makes the value of the `:results-count` attribute, accessible to the component as `resultsCount`.

Elsewhere in the codebase, there is a boolean `loading` flag that gets raised and lowered during the request/response cycle.

https://github.com/microbiomedata/nmdc-server/blob/c15d511698117b45fc27105ad0f1bb25d39e6134/web/src/use/useRequest.ts#L10-L14

Back to the `SearchLayout` component—I think the `loading` flag can be accessed as shown here:

https://github.com/microbiomedata/nmdc-server/blob/c15d511698117b45fc27105ad0f1bb25d39e6134/web/src/views/Search/SearchLayout.vue#L208-L213
> Why there is no `|| consortium.loading.value` in that condition, I do not know.

Based on all that, I plan to try defining a new, boolean prop on the `SearchSidebar` component, and pass it the same value as is being used for that `<v-progress-linear ...` element shown above. Then, within the component, I'll show something other than "0" while the flag is raised.

**Comment by eecavanna** [comment]
I implemented one approach in this PR: https://github.com/microbiomedata/nmdc-server/pull/1212. There are screenshots in the PR.

**Comment by ssarrafan** [comment]
Moving to next sprint for review? @eecavanna
