### ISSUE TITLE
Submission Portal Sandbox Validation issues

### ISSUE THREAD

**Issue by jkelliher-github** [microbiomedata/nmdc-server#1141]
I was testing things in the submission portal sandbox before the AAAS workshop and saw a few things that I didn't know if they were known issues. When I added the same sample number, it wouldn't validate but would use the color for 'Empty Invalid Cell' (dark pink) instead of just 'Invalid Cell' (light pink) and it doesn't limit the omics types based on what I put in in earlier stages of the submission portal (e.g., I selected metagenomics but it lets me choose any omics type in the submission portal. Thanks!
<img width="579" alt="Screenshot 2024-02-17 at 2 23 54 PM" src="https://github.com/microbiomedata/nmdc-server/assets/85245258/78b61166-5d0e-4722-a1ff-28ef09f6151a">

**Comment by mslarae13** [comment]
OBE, sandbox is being eliminated.
Issue doesn't occur in prod
Known issue that analysis type doesn't filter based on multiomics tab selection.. thought we already had an issue, but I cant find it. new one here: https://github.com/microbiomedata/issues/issues/831
