### ISSUE TITLE
Update navigation menu to match latest NMDC website

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-server#1152]
I am in the process of updating the navigation menu on the NMDC website. That work is being tracked in this issue:
- https://github.com/microbiomedata/issues/issues/606

Once those changes are done, I will update the navigation menu of `nmdc-server` accordingly. I think the code powering the navigation menu in `nmdc-server` is in: https://github.com/microbiomedata/nmdc-server/blob/main/web/src/menus.ts

**Comment by eecavanna** [comment]
FYI @pkalita-lbl: No action needed on your part. I just wanted you to be aware that I plan to update the navigation menu of `nmdc-server` soon. I thought you might want to know since you have done this task a few times in the past.

**Comment by pkalita-lbl** [comment]
Cool. Sounds like you found the right place to update in `nmdc-server`!
