### ISSUE TITLE
Tooltip/documentation for submission editor roles and permissions

### ISSUE THREAD

**Issue by naglepuff** [microbiomedata/nmdc-server#1162]
Additional Updates 

- [x] We should add a tool tip that explains the different permission levels.
   - Editor: Editors of a submission have full permission to edit every aspect of the submission with the exception of permission levels.
   - Owner (Author?): Submission author and Principal Investigator have full permission to edit every aspect of the submission.
   - Viewer: A viewer can see all components of a submission, but cannot edit.
   - Metadata Contributor: A metadata contributor can view all components of a submission and can only edit the sample metadata information on the last step of the submission process.
- [x]  New bug: If someone is a metadata contributor, they can't validate the EMSL shipping to move on. This relates to the EMSL shipping bug here: https://github.com/microbiomedata/nmdc-server/issues/939 
- [ ]  Add a "No shipping information required" check box.
   - [ ] https://github.com/microbiomedata/nmdc-server/issues/1083 
- [x]  Add a banner for "Metadata Contributor" that says "Permission level access does not allow editing of this page. Contact the submission Author to request a change in permission status"
- [x]  If I assign someone as PI, AND make them viewer in the Contributors section, the Contributor permission supersedes PI. Make this the other way around.

**Comment by mslarae13** [comment]
@bmeluch please add if I missed anything

@naglepuff I edited your comment to add some details
