### ISSUE TITLE
Display auth token in a persistent endpoint

### ISSUE THREAD

**Issue by shreddd** [microbiomedata/nmdc-server#1163]
Currently the process for accessing Data Portal API requires users to pull the token from the session cookie through browser dev tools.

There is a workaround that goes through the login flow:
http://data-dev.microbiomedata.org/login?behavior=jwt 

It would be easier to just have a persistent endpoint that displays this information instead.

**Comment by shreddd** [comment]
Yes - I think just returning a plain text string (no quotes) similar to runtime API endpoint would be fine:
https://api.microbiomedata.org/orcid_jwt

**Comment by ssarrafan** [comment]
@eecavanna @naglepuff I'll move this to the next sprint for Mike to review.

**Comment by eecavanna** [comment]
Hi @shreddd, I implemented an API endpoint (`/api/session_cookie`) that responds with the session cookie. You can try it out in the development environment, at the URL below. 

https://data-dev.microbiomedata.org/api/docs#/user/Get_the_session_cookie_api_session_cookie_get
