### ISSUE TITLE
"ENVO" group in left-hand search tools should be renamed. Consider  "MIxS Environmental Context" 

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-server#1175]
The following concepts are defined by MIxS, not EnvO, and the acceptable values can from ontologies other than EnvO.

The capitalization is inconsistent, too.

- Broad-scale Environmental Context
- Local Environmental Context
- Environmental medium

![image](https://github.com/microbiomedata/nmdc-server/assets/25185273/48974b47-2cae-439d-9842-de3b5e96384e)

Here are the definitions from MIxS
- [broad-scale environmental context](https://genomicsstandardsconsortium.github.io/mixs/0000012/) 
- [local environmental context](https://genomicsstandardsconsortium.github.io/mixs/0000013/) 
- [environmental medium](https://genomicsstandardsconsortium.github.io/mixs/0000014/) 

@naglepuff @aclum @mslarae13 @cmungall

**Comment by mslarae13** [comment]
I would say "ENVO" should be "Environmental Triad" 
Not sure where this comes from. Probably hard coded?

**Comment by aclum** [comment]
This came up in user research and would be an easy win.

**Comment by turbomam** [comment]
I'd like to keep MIxS in the name to distinguish between our other environmental context system, GOLD.

**Comment by mslarae13** [comment]
MIxS Environmental Triad
or
GSC MIxS Environmental Triad 

@turbomam @aclum

**Comment by aclum** [comment]
I prefer 'MIxS Environmental Triad'. @turbomam  can we make a grouping slot like we have for [gold_path_field](https://microbiomedata.github.io/berkeley-schema-fy24/gold_path_field/) and then we could add a description/tool tip which could be added to the data portal or no b/c these fields inherit from MIxS?
