### ISSUE TITLE
use tagged version of nmdc-ontology

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#1183]
Placeholder for updating to a tagged release version of nmdc-ontology. Changes in main in nmdc-ontology recently broke data portal ingest (b/c of Cyclic graph) so this is a good time to update it.

Realvant code https://github.com/microbiomedata/nmdc-server/blob/f6bfe8f0f24c4dd1dd036e866a126be2ced1ef43/nmdc_server/ingest/envo.py#L16

**Comment by turbomam** [comment]
https://raw.githubusercontent.com/microbiomedata/nmdc-ontology/2024-02-16/nmdco-classes.json

**Comment by ssarrafan** [comment]
@aclum should this be in the current sprint?  Who owns this issue?

**Comment by ssarrafan** [comment]
@mbthornton-lbl @naglepuff  is this something you are currently working on?

**Comment by aclum** [comment]
It should be a straightforward swap so seemed okay to have in this sprint.
If not, next sprint is fine too.

**Comment by ssarrafan** [comment]
@naglepuff @marySalvi I'm assigning this to you in case one of you has time to do this week.

**Comment by ssarrafan** [comment]
@marySalvi said she is looking into this one. I'll remove Mike from this ticket.

**Comment by marySalvi** [comment]
@turbomam @aclum Do we want to always use the latest release or do we want to 'pin' to a specific release? Pinning would require manual updating but potentially less friction for testing different releases

**Comment by turbomam** [comment]
I defer to @aclum 

I am doing active development in the main branch. I'm pretty careful about what I merge, but I haven't been doing an ingest each time. So a pinned release would be safer.

**Comment by aclum** [comment]
The request is for a pinned release. We haven't been doing this and it broke ingest a few weeks ago. The nmdc-server code  and therefore ingest will be more stable. I'd like updating the pinned version to be part of the monthly release cycle. That is, if Mark has a new version there would be a nmdc-server ticket to update the nmdc-ontology version, ideally at least a week before the monthly production release so we could test ingest and the data portal interface on dev.  cc @shreddd @pkalita-lbl
