### ISSUE TITLE
Update submission portal landing page to emphasize the need to login before submitting

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-server#1187]
This issue represents the task of addressing the feedback @shreddd posted at  https://github.com/microbiomedata/nmdc-server/issues/1144#issuecomment-1995981463.

The gist of the task is (in my own words): Update the submission portal landing page that is displayed to logged-out users, in a way that makes it more likely that they understand that they won't be able to create a submission unless they login first.

Here is what the (top part of the) page looks like today:

<img width="1068" alt="image" src="https://github.com/microbiomedata/nmdc-server/assets/134325062/8c56c268-8c01-4ce5-973a-199ff121c837">

**Comment by eecavanna** [comment]
One thing I've noted while working on this is that the original prompt said:
> Login [...] to access the Submission Portal.

Since the page header already says "Submission Portal," visitors might not know what the benefit is of logging in.

That is as opposed to the prompt saying, for example:
> Login [...] to submit data.

Here's what the latter looks like in place:

<img width="1106" alt="image" src="https://github.com/microbiomedata/nmdc-server/assets/134325062/95f05495-9b0a-4cad-807e-465fb92936e6">

**Comment by eecavanna** [comment]
Here's what the latter looks like in place, with a heading above it.

![image](https://github.com/microbiomedata/nmdc-server/assets/134325062/708d515c-3448-4923-8a83-2b312a06da32)

**Comment by eecavanna** [comment]
Here's what the latter looks like in place, with a heading above it and with more margin above the gray box.

<img width="1037" alt="image" src="https://github.com/microbiomedata/nmdc-server/assets/134325062/3884d9e9-ddee-4a50-ad5d-1c23d4267d9c">

**Comment by ssarrafan** [comment]
checked with @eecavanna and moving to next sprint

**Comment by mslarae13** [comment]
@eecavanna I like the additional information
IDK how I feel about a purple box that big. I saw Shreyas also suggested a boarder. Maybe just a purple boarder??

**Comment by JamesTessmer** [comment]
Branch merged, this is completed
