### ISSUE TITLE
Progress bar scrolls down with viewport, overlapping other elements

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-server#1217]
When the web page loads, there is a horizontal progress bar that appears in the upper right area of the page.

When I scroll down while that progress bar is still animating, the progress bar "follows" the viewport down the page. As a result, it appears above some other page elements, as shown in the screenshot below.

<img width="1135" alt="image" src="https://github.com/microbiomedata/nmdc-server/assets/134325062/85d95791-3149-4b2e-a6df-01200ee2db66">

This behavior is present in the production data portal, which is currently deployed from the `app-banner` branch (not `main`). I have not checked whether the behavior is present in `main`.

**Comment by aclum** [comment]
@marySalvi  could you take a look at this, it is only happening in prod so I think is interacting strangely with the banner. In dev the loading bar doesn't move.
