### ISSUE TITLE
Focus plus context for omics type bar chart

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#124]
Highlight selected data as partially filled bars but keep the context (possibly greyed out).

**Comment by subdavis** [comment]
Turns out GCharts are pretty powerful and will do a lot of what we want.

![Screenshot from 2020-08-13 16-10-47](https://user-images.githubusercontent.com/4214172/90182193-95152f00-dd7f-11ea-8ece-91b640610097.png)

**Comment by subdavis** [comment]
Note that, without any conditions selected, you have the regular bars.  I switch to 100% width after conditions are added because the scaling makes it hard to see distinction across bars.

![Screenshot from 2020-08-13 16-16-54](https://user-images.githubusercontent.com/4214172/90182838-8bd89200-dd80-11ea-8e05-f28f080aac80.png)

**Comment by jeffbaumes** [comment]
Could you show an example of a filter without changing to 100% width? Is it that you can't see small numbers of items filled in? The textual representation of the amount would seem to compensate for that. I'm not loving the fact that the same amount of ink does not mean the same amount of data across the bars in the vis.

**Comment by jeffbaumes** [comment]
Maybe you are showing that :) Perhaps a "X / Y" label for showing X out of Y selected would alleviate the issue best.

**Comment by subdavis** [comment]
Here's the same search with both modes:

![Screenshot from 2020-08-13 16-39-52](https://user-images.githubusercontent.com/4214172/90184812-b5df8380-dd83-11ea-810d-cc6e8dfc1e6e.png)
![Screenshot from 2020-08-13 16-40-05](https://user-images.githubusercontent.com/4214172/90184815-b6781a00-dd83-11ea-84aa-c6f63140bccf.png)

**Comment by jeffbaumes** [comment]
This is probably a user group question, but I have a preference to normally scaled bars with a label along the lines of "3 / 8" for your example (and "0 / X" for the other bars).

Also, I think the unselected portion should be a lighter gray, maybe matching the country fill color on the map.

**Comment by subdavis** [comment]
It's trivial to change, let's go with your preference for now.
