### ISSUE TITLE
orcid ID list for users that have bulk downloaded NEON data

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#1268]
We've had to retract some of the NEON records because the the input data was not correct. I would like make sure we contact any users that may have downloaded this data. Do you have the ORCID ID for users that bulk downloaded data from the following studies:

nmdc:sty-11-pzmd0x14
nmdc:sty-11-34xj1150
nmdc:sty-11-hht5sb92

**Comment by jeffbaumes** [comment]
@aclum I've responded in Slack with the list

**Comment by ssarrafan** [comment]
Thanks Jeff. Closing this.
