### ISSUE TITLE
add tooltip for `GOLD Ecosystems` 

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#1303]
Help text should be populated with information from the schema tooltip annotation for [gold_path_field](https://microbiomedata.github.io/nmdc-schema/gold_path_field/)

This is in nmdc-schema main, there should be a tagged release tomorrow.

The two formats these tooltip annotations could take are described in 
https://github.com/microbiomedata/nmdc-server/issues/750

**Comment by aclum** [comment]
Not sure if there is enough time to get this in for the July 29th release, if not its fine to move to the following sprint.

**Comment by ssarrafan** [comment]
This doesn't appear to be ready for the release. I'll move to the next sprint. @aclum @marySalvi

**Comment by aclum** [comment]
looks great thanks!
