### ISSUE TITLE
BUG: info box expansion is moving to far right

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-server#1304]
In the NMDC sandbox & in nmdc submission portal production the column help show hide is broken

If you hide the column help pop out, when you re-expand it you have to scroll to the FAR right to see it
<img width="379" alt="Screenshot 2024-07-19 at 4 38 04 PM" src="https://github.com/user-attachments/assets/152db849-c9d0-4418-9a7f-e0023bdbac32">
<img width="284" alt="Screenshot 2024-07-19 at 4 38 09 PM" src="https://github.com/user-attachments/assets/fd0a1f5f-16b6-41fa-a240-742567f72273">

**Comment by mslarae13** [comment]
high priority to fix for GSC conference

**Comment by mslarae13** [comment]
@naglepuff @pkalita-lbl 
Who should work on this?

**Comment by pkalita-lbl** [comment]
@mslarae13 This should now be fixed on dev. Please give it a test there before next week's release to production.
