### ISSUE TITLE
BUG: column filter not working

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-server#1306]
The "show hide" tool isn't working. When I select a specific section to show only/filter it just hides all the columns.

<img width="1626" alt="Screenshot 2024-07-19 at 4 38 56 PM" src="https://github.com/user-attachments/assets/532f6467-ac18-4367-a6c8-da90226bd9ff">
<img width="1618" alt="Screenshot 2024-07-19 at 4 39 04 PM" src="https://github.com/user-attachments/assets/ac626c3c-bf72-4050-bd45-7d825b6b1ea7">

**Comment by mslarae13** [comment]
@naglepuff @pkalita-lbl 
Who should/can work on this?

**Comment by mslarae13** [comment]
high priority for GSC conference

**Comment by pkalita-lbl** [comment]
@mslarae13 This should now be fixed on dev. Please give it a test there before next week's release to production.
