### ISSUE TITLE
Test ingest for new WorkflowExecutionActivity subclasses - metatranscriptomes

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#1307]
Test that ingest code picks up new WorkflowExecutionActivity subclasses.  Example data that is in mongo dev has also been committed to nmdc-schema here 
https://github.com/microbiomedata/nmdc-schema/blob/768-generate-example-data-to-test-that-nmdc-server-code-can-ingest-new-metatranscriptome-workflow-execution-sub-classes/src/data/valid/Database-metatranscriptome_WorkflowExecution_DataObject.yaml

success criteria: 
1) a search for nmdc:bsm-11-cnc9ww90 has a black metatranscriptome box, when expanded there are results for the following:
nmdc:ReadQcAnalysisActivity
nmdc:MetatranscriptomeAssembly
MetatranscriptomeAnnotationActivity
MetatranscriptomeExpressionAnalysis
2) a KEGG search for `KEGG.ORTHOLOGY:K00005` returns biosample nmdc:bsm-11-cnc9ww90

We'd like this tested for the July 29th release.

**Comment by aclum** [comment]
Added some example documents to mongo dev functional_annotation_agg to test the KEGG search.

**Comment by ssarrafan** [comment]
I tested the success criteria in dev and it's working fine. This can be included in the release on Monday please.  

success criteria:

1. a search for nmdc:bsm-11-cnc9ww90 has a black metatranscriptome box, when expanded there are results for the following:
nmdc:ReadQcAnalysisActivity
nmdc:MetatranscriptomeAssembly
MetatranscriptomeAnnotationActivity
MetatranscriptomeExpressionAnalysis
<img width="509" alt="Screenshot 2024-07-26 at 2 19 18 PM" src="https://github.com/user-attachments/assets/4bfb35c5-8927-4766-9a68-d8ec5884f8fc">
<img width="589" alt="Screenshot 2024-07-26 at 2 19 29 PM" src="https://github.com/user-attachments/assets/b4d10010-2c18-4367-aa4b-dea2b89ea614">


2. a KEGG search for KEGG.ORTHOLOGY:K00005 
<img width="1354" alt="Screenshot 2024-07-26 at 2 33 23 PM" src="https://github.com/user-attachments/assets/6bce2aeb-08c8-408f-90c8-098b5b99b07d">


<img width="1327" alt="Screenshot 2024-07-26 at 2 33 36 PM" src="https://github.com/user-attachments/assets/9176d049-f6d3-4448-a7e7-2bfe486a51f1">
