### ISSUE TITLE
`berkeley` Replace references to OmicsProcessing with DataGeneration

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-server#1326]
Under “Omics” bar chart, it is not intuitive to have Organic Matter there, since that is not an omics data type 
(this is a broader issue than just the Omics bar chart, but that is where attendees noted it)

![Screen Shot 2023-03-30 at 12 38 13 PM](https://user-images.githubusercontent.com/44581429/228946024-8bb46f2b-4edf-466a-b635-19ab96155a5d.png)
![Screen Shot 2023-03-30 at 12 38 19 PM](https://user-images.githubusercontent.com/44581429/228946026-f05832e7-1c5e-4430-ae13-2f98c8043f4a.png)

**Comment by aclum** [comment]
Looking at https://data-berkeley.microbiomedata.org/ references to Omics are hard coded. Please update, in the berkeley nmdc-server branch the following:
`Omics Processing` header in faceted search to `Data Generation`
`Omics type` in faceted search to `Data type`
`Omics` in the bar chart to `Data type`

cc @mslarae13

**Comment by aclum** [comment]
@naglepuff  I don't see these changes in the berkeley data portal?  I though @eecavanna  redeployed this a few days ago so I was expecting
![Screenshot 2024-08-21 at 12 56 41 PM](https://github.com/user-attachments/assets/bb05fab2-98ba-4320-a1a2-d8e715814904)
 to see to those changes in the UI.

**Comment by naglepuff** [comment]
I just redeployed the front and back end services, and I see the changes. The change must not have been merged into the feature branch for the redeployment that you mentioned.

**Comment by mslarae13** [comment]
@aclum thoughts... this might be getting nit-picky.. but

<img width="564" alt="Screenshot 2024-08-22 at 8 40 46 AM" src="https://github.com/user-attachments/assets/ea4b3b72-2d9a-4550-9f2c-eb4f9bcd0965">

Metagenome vs Proteomics

Metagenomics & Proteomics

or

Metagenome & Proteome ??

**Comment by aclum** [comment]
That is the same as it is now, once berkeley gets pushed out I suggest we add a title slot to AnalyteCategoryEnum permissible values and use consistent vocab.

**Comment by aclum** [comment]
ticket for title slot for AnalyteCategoryEnum
https://github.com/microbiomedata/nmdc-schema/issues/2154
