### ISSUE TITLE
backend ingest updates to support functional search by COG terms

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#1333]
related to FY25 Q1 milestone https://github.com/microbiomedata/issues/issues/522

Assumes records would be in the functional_annotation_agg collection with a prefix of 'COG'
example 
{
  "metagenome_annotation_id": "nmdc:wfmgan-11-ndgg7v31.1",
  "gene_function_id": "COG:COG0001",
  "count": 56
}

2020 release term names, pathways and categories on nersc /global/cfs/cdirs/m3408/functional_annotation_mappings/cog2020

There will be similar tickets for Pfam and GO so we should take the opportunity to generalize https://github.com/microbiomedata/nmdc-server/blob/main/nmdc_server/ingest/kegg.py

Acceptance criteria: ingest process accepts COG terms such that they appear in the postgres database. There will be a separate ticket for data portal front end changes to make the functional search more generic.

**Comment by naglepuff** [comment]
@aclum is there any test data in dev for this?

**Comment by ssarrafan** [comment]
@aclum can you help Mike with some test data in dev?

**Comment by aclum** [comment]
example parsing would be for the same cog block
for a match in results.cog.cogid
name would be results.cog.name
pathway would be results.cog.pathways - this can be a list
category name would be results.cog.funcats.name 
category description would be  results.cog.funcats.description

so for `COG0001`, name is `Glutamate-1-semialdehyde aminotransferase`, pathway is `Heme biosynthesis category` name is `H` category description is `Coenzyme transport and metabolism`

**Comment by naglepuff** [comment]
This is going to have to continue into the next sprint.

**Comment by aclum** [comment]
two test records have been added to dev, that will get overwritten monday afternoon but I can add it back if needed.
 ```
[
    {
      "metagenome_annotation_id": "nmdc:wfmgan-11-wpcf1e84.1",
      "gene_function_id": "COG:COG0003",
      "count": 5
    },
    {
      "metagenome_annotation_id": "nmdc:wfmgan-11-wpcf1e84.1",
      "gene_function_id": "COG:COG1155",
      "count": 10
    }
  ]
```

**Comment by aclum** [comment]
Added some test data last friday which Mike grabbed before it was overwritten by prod data today. Please ping me again if you didn't have a chance to grab the data and need me to repopulate.

**Comment by ssarrafan** [comment]
Moving to next sprint. @naglepuff @aclum let me know if this won't be reviewed next sprint.
