### ISSUE TITLE
Data portal web ui update functional search to include Pfam and COG

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#1338]
Update the faceted search `function` section to include Pfam and COG.

depends on #1333, #1337 and https://github.com/microbiomedata/nmdc-aggregator/issues/12

related to FY25 Q1 milestone https://github.com/microbiomedata/issues/issues/522

**Comment by aclum** [comment]
Note pfam clan bioregistry link is different than for pfam terms, see https://github.com/microbiomedata/nmdc-schema/issues/2162

**Comment by aclum** [comment]
Assigning to me until requirements are clear.
cc @emileyfadrosh @cmungall

**Comment by aclum** [comment]
Spoke with @cmungall about this and his suggestion was to add a faceted search each for KEGG, COG, Pfam, and GO. This will more easily facilitate browsing the hierarchy like we have for the environmental context terms.
![20240912 expanded func search front end](https://github.com/user-attachments/assets/f175fd94-776f-4140-ba55-694c4c3a6785)

Requirements:
Under the Function faceted search section:

- [ ] Add `COG`
- [ ] Add `GO`
- [ ] Change `KEGG term` to `KEGG` (since we support search for orthologs, pathways and modules)
- [ ] Add  `Pfam`
- [ ] order alphabetically

@emileyfadrosh to weigh in.

**Comment by ssarrafan** [comment]
@aclum are you still waiting on feedback from @emileyfadrosh on this issue?

I'll move one more sprint

**Comment by aclum** [comment]
Yes

**Comment by ssarrafan** [comment]
Sent a note to @emileyfadrosh on Slack to look at this.

**Comment by emileyfadrosh** [comment]
Sorry for the delay. Agree with this plan and to list the functions in alpha-order.

**Comment by ssarrafan** [comment]
@naglepuff what's the status of this issue?  Can it be closed this sprint?

**Comment by naglepuff** [comment]
This will have to be moved to the next sprint

**Comment by ssarrafan** [comment]
Mike mentioned he was going to work on this. I'll move to the new sprint.

**Comment by naglepuff** [comment]
Almost done with the UI for this. Given the amount that still needs to be done plus time for code review, I will say that this will likely be wrapped up early next week.
