### ISSUE TITLE
Implement aggregate file size information for bulk download

### ISSUE THREAD

**Issue by ljohnson09** [microbiomedata/nmdc-server#1344]
**Deliverable this task is associated with**

_See Deliverables tab here: _

- [Add the Deliverable #]
4.1 Perform user research to refine the Data Portal user experience

**RACI**

_Tag people in their roles_
- Responsible: Eric or Kitware team members (Need to discuss who will do this)
- Accountable: Alicia
- Consulted:
- Informed:

**Describe the the task**
- [ ] Implement file size info for bulk download (e.g., under select file type, aggregation of file sizes) - Users wanted to know the file size of total selected download, not just the individual file sizes that we have listed in the sample dropdown 

**Criteria for completion**
- [What does success look like for this task to be considered complete?]

**Estimate people time**
- S or M tshirt 

**Completion Date (Goal)**
- [GOAL!]

**Target Sprint Start & End Dates**
- Start:
- End:

**Tag Blocker/Contingent upon issues**
- [Tagg issues]

**Comment by jeffbaumes** [comment]
We currently get live file counts based on the current search so there's a chance we can just roll up file sizes in the same server logic without too much trouble or performance hit. @naglepuff may be worth investigating a bit to see if this is a big lift or not.

**Comment by naglepuff** [comment]
I can take a look and give an estimate

**Comment by naglepuff** [comment]
I don't think this is a big lift, it could probably be done in a few hours to maybe a day max.

The workflow type/file type tree from the drop down is populated by data fetched from the `/data_object/workflow_summary` endpoint. You can see the shape of that data [here](https://github.com/microbiomedata/nmdc-server/blob/main/web/src/data/api.ts#L294-L298). Currently this is an object whose top level keys are the workflow types, and the values are objects whose keys are file types and values are numbers (the count of the that file type). So we don't currently have the size information. 

[Here](https://github.com/microbiomedata/nmdc-server/blob/main/nmdc_server/aggregations.py#L168-L226) is the function that builds the response for the `/data_objects/workflow_summary` endpoint. It doesn't currently include the file size, but I don't think it would be much of a lift to modify the SQLAlchemy here to include that information. From there, it would be a matter of updating the pydantic model and typescript classes, and making sure the aggregation function builds the expected output. Something like:

```
{
  WorkflowType1: {
    count: number,
    size: number,
    file_types: {
      FileType1: {
        size: number,
        count: number
      }
    }  
  }
}
```

I've taken a quick look at all the places where this pydantic class is used, and I believe its really only for this aggregation, so I don't think there would be a ton of cleanup to do outside of these changes. We'd also need to update the [bulk download component](https://github.com/microbiomedata/nmdc-server/blob/8715c7a1ea71b433980edbd0e274c38ddee756a0/web/src/components/BulkDownload.vue#L38-L46) to make use of this new information.

**Comment by naglepuff** [comment]
@aclum this should be in dev now

**Comment by aclum** [comment]
looks good.
