### ISSUE TITLE
Add ability to select multiple sample type environment

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-server#1367]
Currently, NMDC submission portal has a radio button to select only 1 type of sample (soil, water, sediment, etc)

We'd like this to be checkboxes and all for 1 study to have multiple sample types in 1 submission.

- IF submitting for JGI and EMSL, all the sample types will need to populate the JGI and EMSL tabs the same way the single sample does
- Need to make sure the sample type is populated for each sample when the ingest to mongo happens
- Can we update Environmental Packages to Environmental Extensions to accurately match GSC

**Comment by ssarrafan** [comment]
Discussed at infra sync and it's more complicated that expected. @marySalvi still working on this.

**Comment by pkalita-lbl** [comment]
The proposed changes will require changes in the Field Notes app. Cross-linking that issue here: https://github.com/microbiomedata/nmdc-field-notes/issues/177

**Comment by mslarae13** [comment]
Work will be complete by end of September to satisfy milestone.
Roll out to production will NOT happen with September roll out.
Roll out can happen in October, updates to the app should be done in time.

**Comment by mslarae13** [comment]
Will NOT be part of https://github.com/microbiomedata/issues/issues/874

**Comment by ssarrafan** [comment]
Moving to next sprint per updates by @mslarae13 
thank you

**Comment by ssarrafan** [comment]
Will this issue be completed this sprint? @marySalvi @mslarae13

**Comment by marySalvi** [comment]
> Will this issue be completed this sprint? @marySalvi @mslarae13

Yes, it should be

**Comment by mslarae13** [comment]
Decision today at infrastructure sync: will not merge until after berkeley-schema is in production, so after oct 15. There will be merge conflicts

**Comment by ssarrafan** [comment]
@marySalvi @mslarae13 so can this be considered done (for DOE report purposes) but moved to the next sprint for production deployment?

**Comment by marySalvi** [comment]
I think this can be considered done but should not be merged until after Oct 15th

**Comment by mslarae13** [comment]
Ready to merge?

**Comment by mslarae13** [comment]
@marySalvi  @pkalita-lbl 
Any updates here? I believe the PR noted that if this is merged it'll break the app.

**Comment by pkalita-lbl** [comment]
No no no, I _would like_ this to be merged into `main` sooner than later so that I can complete some app updates.

**Comment by marySalvi** [comment]
> No no no, I _would like_ this to be merged into `main` sooner than later so that I can complete some app updates.
I have rebased my runtime and created the PR below.
https://github.com/microbiomedata/nmdc-runtime/pull/741

I'll work on rebasing my PR on `nmdc-server` now. Once both are ready we should be able to merge.

@pkalita-lbl for the `runtime` PR I adjusted the tests and everything is passing. I would feel more comfortable if I saw the finished products in the DB but I didn't see any test entries in the DB. Am I right in thinking they get deleted in cleanup?

**Comment by mslarae13** [comment]
Blocked. Coordinating changes in run-time. Major change in the way sample data is stored. Run time translates submission data into mongo. Mary has started working on this.

**Comment by mslarae13** [comment]
@marySalvi status on this?

**Comment by mslarae13** [comment]
@marySalvi is addressing a bug in runtime.
Correct me if that's wrong

**Comment by ssarrafan** [comment]
@marySalvi @mslarae13 will this be in the release next week?

**Comment by marySalvi** [comment]
Yes, it should be

**Comment by mslarae13** [comment]
As long as https://github.com/microbiomedata/issues/issues/968 gets completed.

**Comment by mslarae13** [comment]
Looks good!

@pkalita-lbl did you make an issue to make sure sample names were unique across sample types?

**Comment by pkalita-lbl** [comment]
> did you make an issue to make sure sample names were unique across sample types?

I have not, no
