### ISSUE TITLE
BUG: If funding source or contributors has been started and left empty, there's not indication for invalid

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-server#1369]
When someone doesn't provide required information, you get red

![Screenshot 2024-08-27 at 11 52 40 AM](https://github.com/user-attachments/assets/0260ad25-0ff1-4418-9781-bfb838946f13)

Can we make funding source & collaborators do that if someone has added but not completed?
![Uploading Screenshot 2024-08-27 at 11.53.10 AM.png…]()

So it's obvious why the "GO TO NEXT STEP" button isn't available

**Comment by ssarrafan** [comment]
Duplicate of #1370 
Closing this one
Thanks @pkalita-lbl
