### ISSUE TITLE
`berkeley` faceted search missing in berkeley data portal

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#1373]
See 
https://data-berkeley.microbiomedata.org/

![20240829 berkeley faceted search](https://github.com/user-attachments/assets/ea907e64-1aba-4431-8b49-e1b1e948f67a)

**Comment by naglepuff** [comment]
I noticed an error in the logs for the `portal-backend`. It looks like the postgres is out of date, maybe due to a stale ingest. I kicked off an ingest to hopefully get more up-to-date data. I'll update this issue when that job is completed.

**Comment by naglepuff** [comment]
Looks like the faceted search sidebar is back in data-berkeley

**Comment by aclum** [comment]
confirmed fixed.
