### ISSUE TITLE
Create mockups for metadata suggestion UI in submission portal

### ISSUE THREAD

**Issue by pkalita-lbl** [microbiomedata/nmdc-server#1381]
Part of Milestone 3.3 (https://github.com/microbiomedata/issues/issues/473)

This task is to sketch out the UI aspects of metadata suggestion/enrichment functionality, including:

* What new UI elements need to be added and what existing elements need to be rearranged
* How a user interacts with the new elements to review, approve, or reject suggestions

This task is complete when mockups have been approved by the submission portal product owner and other stakeholders.

**Comment by ssarrafan** [comment]
@pkalita-lbl @mslarae13 assuming mockups haven't been approved yet so I'll move this to the next sprint?

**Comment by pkalita-lbl** [comment]
Current status:

* Created mockups [here](https://docs.google.com/presentation/d/1mBTB76Z0UV6KfpzRm7lEK3SrXx81mUgKpTuMH5QX9Zk/edit#slide=id.p)
* I reviewed with Montana and she generally agreed with the direciton
* I shared the mockups with the Kitware team. Faiza indicated she had some more ideas, but I haven't heard any follow-up on that yet.

**Comment by ssarrafan** [comment]
@pkalita-lbl can this be closed since Mike approved?

**Comment by pkalita-lbl** [comment]
I'm kind of still waiting on @mslarae13 to review the alternative mockups that Faiza provided. Sorry, a lot of the discussion has been happening on Slack and not in this issue.

**Comment by mslarae13** [comment]
SORRY! Doing it now

**Comment by mslarae13** [comment]
I left some minimal comments and opinions. I just need the row vs column thing explained and otherwise I think it's good. 
@pkalita-lbl did you have any preference for option 1 or 2?

**Comment by pkalita-lbl** [comment]
> I just need the row vs column thing explained and otherwise I think it's good.

There might be a few different "things."

The mockup shows buttons for rejecting or accepting all suggestions. Faiza referred to these in a comment as "bulk operations" and then went on to speculate about adding additional controls for row-wise bulk operations (i.e. accept all the suggestions for, say, row 2 or row 3). I think your comment was that it might make more sense to have column-wise bulk operations (i.e. accept all the suggestions for the elevation column). I think I agree that column-wise might be more useful. But I'd also point out that neither of those are actually reflected in the current mockups. Do you think either a row-wise or column-wise accept/reject is important for a first pass? If so, let's work out those details now. Otherwise, let's keep in our pocket for later.

The mockups also show the individual suggestions grouped by row. I think this was just for visual organization (i.e. here are all of the suggested changes for this one sample). That made sense to me. Were you suggesting that they should be visually grouped by column instead (i.e. here are all the suggested changes to the elevations)?

> did you have any preference for option 1 or 2?

I'm somewhat ambivalent, and I was hoping you'd have a strong preference 😁 The way I see it is:

* Option 1 pros:
  * Fewer changes for users to adjust to
  * Fewer changes to implement
* Option 2 pros:
  * Maybe more holistic improvements in organization for that page

**Comment by ssarrafan** [comment]
Patrick is out till next week so I'll move this to the next sprint for him to update.

**Comment by pkalita-lbl** [comment]
Planning on setting up a meeting with Montana and Faiza next week to finalize plans. Until then, moving to next sprint.

**Comment by pkalita-lbl** [comment]
Met with Faiza and Montana this week. We reviewed the [Figma mockups](https://www.figma.com/design/WznbKUaE9h4v4EOYhKdgHZ/Suggester-Feature-for-submission-portal) that Faiza made and decided to move forward with the one labeled "Second Option". 

This task is now complete. Closing.
