### ISSUE TITLE
Remove BRITE terms from KEGG search

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#1385]
There are issues with parsing the json files which lead to at least one BRITE term being part of the KEGG term search without returning expected results. 
`01000 Enzymes [BR:ko01000] ` is a BRITE term which is not currently supported. There will be a separate ticket to expand support to BRITE. 
 
This term is showing up as a term value without a text value because of how the json is being parsed.  We need to determine if any other terms fall into this category and figure out the best way to exclude it. Options would be to exclude 'terms' that start with a digit instead of a letter or by excluding 'terms' that match to [BR:*].

See original ticket from @cmungall  https://github.com/microbiomedata/nmdc-server/issues/1043

**Comment by ssarrafan** [comment]
@naglepuff mentioned this at infra sync meeting yesterday
moving to next sprint
FYI @aclum

**Comment by ssarrafan** [comment]
@naglepuff what's the status of this issue?  Can it be completed this sprint?  
@aclum

**Comment by aclum** [comment]
I dont see a linked PR so moving to the next sprint.

**Comment by ssarrafan** [comment]
There is a linked PR and hopefully @marySalvi can review this by tomorrow? 
FYI @aclum

**Comment by ssarrafan** [comment]
Moving to next sprint for review

**Comment by aclum** [comment]
@naglepuff is this ready to merge in? Mary has approved the linked PR.

**Comment by naglepuff** [comment]
Yes, I must have missed that. I had to make a small change so once tests finish that will be merged in.
