### ISSUE TITLE
Data Portal - backend support GO faceted search via mappings - KEGG

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#1389]
Search for a GO term in the data portal should use a mapping file to check mapping files since the GO terms aren't stored directly in the data files.

The KEGG -> GO mapping file is https://www.genome.jp/kegg-bin/show?file=ko2go.xl

The code should be able to handle multiple mapping files, there is a related Pfam ticket. #1388 

cc @sierra-moxon

**Comment by ssarrafan** [comment]
@naglepuff @aclum what's the status of this?  I'm going to remove from sprint and add the backlog label. Let me know if you plan to work on it.

**Comment by aclum** [comment]
I scheduled this for sprint 50 since @naglepuff already has 3 tickets this sprint and we have the retreat. This is part of the collection of tickets we'd like done this quarter in support of the milestone to improvement functional annotation search vi GO annotations(2.12.2)

**Comment by aclum** [comment]
This is related to milestone 2.12.2 which is due this quarter (end of Dec), targeting this for the December 16 production release.

**Comment by ssarrafan** [comment]
Appears to be active. Moving to next sprint.
