### ISSUE TITLE
Docs: Replace ORCID Redirect URI list with link to `infra-admin` repo (consolidated list)

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-server#1393]
#### Task

Replace the partial list of ORCID Redirect URIs in [development.md](https://github.com/microbiomedata/nmdc-server/blob/c035f5ff76be051116b1aac596598d4e4f51bdb6/docs/development.md#production-redirect-uris), with a link to [this full list](https://github.com/microbiomedata/infra-admin/blob/main/orcid/README.md#current-redirect-uris) that is in the `infra-admin` repository.

**Comment by ssarrafan** [comment]
@eecavanna who should this be assigned to?

**Comment by eecavanna** [comment]
I'll take it.
