### ISSUE TITLE
`berkeley`: Replace `/api/omics_processing` endpoints with `/api/data_generation`

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#1394]
OmicsProcessing was replaced with DataGeneration in berkeley

replace endpoints in the omics processing grouping https://data-berkeley.microbiomedata.org/api/docs#/omics_processing endpoints with data_generation

cc @shreddd

**Comment by mslarae13** [comment]
@pkalita-lbl & @eecavanna to check / confirm that these end points won't affect submission portal or field notes app

**Comment by pkalita-lbl** [comment]
Correct. As far as I can tell there is no usage of any of the various endpoints under `/api/omics_processing` in either the submission portal or field notes app.

**Comment by aclum** [comment]
@naglepuff do you expect to have this done this sprint?

**Comment by aclum** [comment]
This has a linked PR but no review yet, moving to in review for next sprint.

**Comment by aclum** [comment]
@naglepuff  can this be closed? the linked PR is merged.

**Comment by naglepuff** [comment]
Closing. Confirmed in dev that this is fixed
