### ISSUE TITLE
`berkeley` protocol information not showing up correctly on study pages

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#1406]
Protocol information was remodeled on study, [relevant_protocols](https://microbiomedata.github.io/nmdc-schema/relevant_protocols/) is [protocol_link](https://microbiomedata.github.io/berkeley-schema-fy24/protocol_link/) in berkeley. 
EMP500 (nmdc:sty-11-547rwq94) is an example study where protocol_link is populated in mongo but is not currently being shown in the berkeley data portal env.

**Comment by ssarrafan** [comment]
@aclum are you expecting this to be done this sprint?  issue was created just 2 days ago so I am assuming next sprint?

**Comment by naglepuff** [comment]
@ssarrafan I don't know why github didn't link this up with the PR, but #1407 contains a fix. If it can get reviewed (I've assigned @marySalvi) by EOD it should make it into the berkeley environment

**Comment by ssarrafan** [comment]
> @ssarrafan I don't know why github didn't link this up with the PR, but #1407 contains a fix. If it can get reviewed (I've assigned @marySalvi) by EOD it should make it into the berkeley environment

Ok I'll move to the next sprint for @marySalvi to review.

**Comment by aclum** [comment]
Same here, linked PR is merged so I think this can be closed. @naglepuff

**Comment by aclum** [comment]
Confirmed fixed in dev.
