### ISSUE TITLE
Remove downtime banner from Data and Submission Portals

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-server#1424]
Remove this banner.

![Image](https://github.com/user-attachments/assets/f1598ea4-8233-4b12-9b7c-8d6c911e6a6d)

I will do this now.

**Comment by ssarrafan** [comment]
Hmm I thought @shreddd brought this down yesterday but it looks like it's still up. 
@eecavanna are you planning to do this today or next week?

**Comment by eecavanna** [comment]
I'm still planning to do it today.  He did bring down the banners on the Runtime and the Status website.

**Comment by eecavanna** [comment]
This is done. I was deployed to production today via a hotfix (`Release 2024.10.1`).

**Comment by eecavanna** [comment]
Re-opening because, while it's been deployed to production already, the code isn't in `main` yet.

**Comment by eecavanna** [comment]
Oops. This is redundant with what @naglepuff implemented in https://github.com/microbiomedata/nmdc-server/pull/1421. I prefer his implementation, since it also consolidates multiple occurrences of "the same" boolean value into one "shared" occurrence.
