### ISSUE TITLE
Update ingest of `functional_annotation_agg` for compatibility with new slot

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#1431]
Katherine has some PRs which change slot names on functional_annotation_agg https://github.com/microbiomedata/nmdc-schema/pull/2203.

This ticket is for the updates needed to nmdc_server

cc @kheal 

Please confirm this can be done by Nov 11.

**Comment by aclum** [comment]
@naglepuff  assigning to you since you've handled the other changes to the functional annotation aggregation work.

**Comment by kheal** [comment]
We have not yet translated the MetaP results into the functional_annotation_agg collection (dependent on a 1 more schema change + aggregation change).  However, we have a PR open to change the structure of the functional_annotation_agg records (switched a field name) for the Sequencing results, so I think we do still need a change in the server ingest to accomodate for that.

**Comment by aclum** [comment]
thanks for the clarification, i've updated the title and description.

**Comment by kheal** [comment]
The schema dependencies have been merged in for this.  Note that this collection `functional_annotation_agg` still only contains MetaT and MetaG data (not yet MetaP, which are still housed in the `metap_gene_function_aggregation`).

**Comment by aclum** [comment]
This was merged into dev yesterday and @naglepuff did an ingest. Everything is working as expected.
