### ISSUE TITLE
metabolomics data is not showing up in data portal dev

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#1449]
There should be 34 metabolomics analysis records but there are none in data portal dev. I checked the dataset API dev and it does know about the workflow data objects (ie Request URL
https://data-dev.microbiomedata.org/api/data_object/nmdc%3Adobj-13-f4rjgf19)
<img width="1346" alt="Screenshot 2024-11-14 at 3 05 07 PM" src="https://github.com/user-attachments/assets/1d19f08f-beb1-42bc-b19d-6d73172ea324">

This is what prod looks like.
<img width="1414" alt="Screenshot 2024-11-14 at 3 14 34 PM" src="https://github.com/user-attachments/assets/d886bfd1-aa0c-43d7-aa43-d4b14f5a2f7a">

cc @kheal

**Comment by eecavanna** [comment]
The screenshots @aclum posted above were taken at a time when the Data Portal code had been updated to use version 11.1.0 of the schema, but the corresponding ingest was still taking place. Now that the ingest is finished (it finished about 30 minutes ago), I still see the symptom she initially reported.

In short, these "Metabolomics" chips are grayed out in the development Data Portal (this does not match her expectations):

![image](https://github.com/user-attachments/assets/5de16d28-7da3-46b3-824f-d0e6aed945ac)

Whereas they are not grayed out on the production Data Portal (this _does_ match her expectations):

![image](https://github.com/user-attachments/assets/4af82842-9399-4b8d-a9cd-ffdbfccee867)

**Comment by naglepuff** [comment]
There are several errors in the ingest logs for the most recent dev ingest that hint at the issue:
```
INFO  [nmdc_server.ingest.all] Loading metabolomics analysis...
ERROR [nmdc_server.ingest.pipeline] Error parsing pipeline nmdc:wfmb-13-1v78b457.1
Traceback (most recent call last):
  File "/app/nmdc_server/ingest/pipeline.py", line 260, in load
    pipeline = load_object(db, obj, **kwargs)
  File "/app/nmdc_server/ingest/pipeline.py", line 186, in loader
    pipeline_dict = schema(**obj)
  File "/usr/local/lib/python3.9/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for MetabolomicsAnalysisBase
has_calibration
```

Looks like that slot was moved in [nmdc-schema#2235](https://github.com/microbiomedata/nmdc-schema/pull/2235)

We currently have that as a non-nullable column in postgres

**Comment by naglepuff** [comment]
@aclum please confirm this is fixed on dev and can be removed from the list of blockers for the next release

![image](https://github.com/user-attachments/assets/b458d671-faea-4d66-aa6f-29583f542109)

**Comment by aclum** [comment]
Confirmed fixed on dev & I will update the Nov release ticket.
