### ISSUE TITLE
data portal prod - COG & CL terms showing up in KEGG search

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#1452]
Not sure this is worth fixing b/c this is not happening on dev and we are close to a production update but COG terms as well as pfam clans (CL) terms are showing up in the KEGG search but not returning any results (dev returns 167 results when searching the COG faceted search with CL0585  vs 0 in prod with a search for CL0585 with the KEGG faceted search).  Also this term's link out redirects to an empty page.

nmdc-server version: v1.0.1
![Screenshot 2024-11-14 at 5 01 48 PM](https://github.com/user-attachments/assets/56a0ff6b-a100-42a1-86c1-1bd1697d497e)

**Comment by naglepuff** [comment]
This is fixed by #1436
