### ISSUE TITLE
Data portal - UI updates for GO functional search

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#1462]
This should be implemented in a similar fashion to https://github.com/microbiomedata/nmdc-server/issues/1338

Depends on 
 - [x] #1389 
 - [x] #1388 

Expansion prefix http://purl.obolibrary.org/obo/GO_

General documentation link:
https://geneontology.org/docs/ontology-documentation/

cc @sierra-moxon 

This is a target for the Dec 16, 2024 release. It is part of [milestone 2.12.2](https://github.com/microbiomedata/issues/issues/518) which is due in Q1 FY25 (end of Dec) 

This ticket completes the cluster of related tickets to expand functional annotation search.

**Comment by aclum** [comment]
@naglepuff is this done? i can see this in the UI but it doesn't appear to be filtering any samples. cc @sierra-moxon

**Comment by naglepuff** [comment]
![image](https://github.com/user-attachments/assets/f9768325-e1e3-47fc-a9ea-00ec0c53013b)
This search filters samples. What value are you searching with and what are you expecting to see? Maybe there are some missing mappings.

**Comment by aclum** [comment]
I used https://data-dev.microbiomedata.org/?q=ChQIABAAGAgiDCJHTzowMDAwMDA2Ig as a filter and returned all samples which does not make sense b/c not all samples have the types of data generation that would have functional annotation results.
![Screenshot 2024-12-10 at 1 34 55 PM](https://github.com/user-attachments/assets/c11af31b-91ef-4066-9b56-0aa47d87936b)

**Comment by aclum** [comment]
I did confirm that a search for GO:0004930 is working, it filters down to 217...based on that I suspect a bug when there is no mapping

**Comment by naglepuff** [comment]
Weirdly, when I click the link you provided, this is what I see:
![image](https://github.com/user-attachments/assets/3adce1b9-7cf5-4201-acf6-509e7592b991)

Are you able to consistently get into the buggy state where all samples are returned?

Do you have an expected count/expected biosample ID for your search?

**Comment by aclum** [comment]
Yes, Im able to consistently get into the buggy state where all samples returned. 
To reproduce:
go to https://data-dev.microbiomedata.org/
click on GO for facted search
select 'GO:0000005: high-affinity zinc transmembrane transporter activity' from the drop down list to apply it as a filter

**Comment by naglepuff** [comment]
Hmm, ok. I will take some time today to try and reproduce locally and work on a fix. I have a hunch as to what's going on. (Your comment about not all terms having mappings is a good clue)

**Comment by aclum** [comment]
Confirmed fixed.
