### ISSUE TITLE
Data portal- support lipidome results

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#1464]
We expect to add lipidome records along with workflow results. We need lipodome added in the following:
- [x] bar chart
- [x] facted omics type search
- [x] upset plot
- [x] tick boxes below samples
- [ ] be able to download workflow results 

@kheal added test data to mongo dev in https://github.com/microbiomedata/issues/issues/944

cc @shreddd @ssarrafan 

Needs prioritization, we expect to have lipidome results in mongo in December and would like to highlight this in the annual report which needs to be finalized mid-January 2024.

**Comment by aclum** [comment]
Effectively will undo [this](https://github.com/microbiomedata/nmdc-metadata/issues/312) old request.

**Comment by naglepuff** [comment]
@kheal @aclum I'm looking at the example data in dev and I don't see any biosample with ID `nmdc:bsm-11-0n5nks24`, which is listed as the input for both of the test `data_generation` documents. Should this biosample exist in dev?

**Comment by kheal** [comment]
@naglepuff - sorry about that, not sure where I pulled that biosample ID from!  Would it help to submit a changesheet for the two data generation records so they point to an exisiting biosample id?  Or I can resubmit to dev with better IDs when dev mongo is overwritten during the release cycle (in the next couple days), which would be better for you?

**Comment by naglepuff** [comment]
@kheal If the changesheet wouldn't be too much of an issue, that would be great. 

Alternatively, if the records can just point to any arbitrary biosample, I can actually just make that change myself (I typically use a local mongo database for my development environment), and you can resubmit after the overwrite for testing in dev.

**Comment by kheal** [comment]
@naglepuff  - I've put in a changesheet.  See below for new biosample ids matched with their data generation records.  The biosamples are just arbitrary ones that exist.

`id	action	attribute	value

nmdc:dgms-11-7eknfj92	update	has_input	nmdc:bsm-11-002vgm56
nmdc:dgms-11-7pd1ce60	update	has_input	nmdc:bsm-11-002vgm56`
