### ISSUE TITLE
Source MetaProteomics functional results from `functional_annotation_agg` collection for ingest and Data Portal

### ISSUE THREAD

**Issue by kheal** [microbiomedata/nmdc-server#1468]
After restructuring of the `functional_annotation_agg` collection in Mongo we will be and adding MetaProteomics functional results to this collection (dependent on https://github.com/microbiomedata/nmdc-aggregator/pull/27).  We will then need to restructure/check how the MetaP functional annotations are accessed during ingest to postgres and ultimately on the Data Portal.  

We intend to remove all records from the `metap_gene_function_aggregation` collection in Mongo - instead all functional annotations for Metaproteomics will be found in the `functional_annotation_agg` collection.

For testing - in dev mongo, the `functional_annotation_agg` collection  now contains records for a MetaProteomics analysis.  You can find them by searching dev mongo's `functional_annotation_agg` collection  for the `was_generated_by` field's value "nmdc:wfmp-11-x0zhd078.1".

cc @aclum

**Comment by aclum** [comment]
@naglepuff  we'd like this as part of the December release.

**Comment by eecavanna** [comment]
Hi @kheal, I have a question regarding this statement:

> We intend to remove all records from the `metap_gene_function_aggregation` collection in Mongo - instead all functional annotations for Metaproteomics will be found in the `functional_annotation_agg` collection.

I talked with @aclum during today's release planning meeting and she elaborated on this ticket. One question I have is: what do you expect to happen to the data that's currently in the `metap_gene_function_aggregation` collection. For example, will there be a **Mongo migrator** that moves it to the `functional_annotation_agg` collection? Or will we ignore it (maybe delete it later) and allow the **aggregator** to re-generate that data "in the right place" (i.e. in the `functional_annotation_agg` collection)? I think the latter will be simpler for me, as the migration framework has not been used with non-schema-described collections before (I'm under the impression the `metap_gene_function_aggregation` is not described by the schema).

**Comment by kheal** [comment]
@eecavanna. Your second suggestion is currently our plan. No migration, just let the aggregator populate. Once we know the aggregator is working properly with the data portal, delete the ‘metap_gene_function_aggregation‘ collection entirely.

**Comment by naglepuff** [comment]
Looks like I had some sort of misunderstanding regarding the change last month in the `functional_annotation_agg` collection and stopped pulling from the `metap_gene_function_aggregation` collection. So the functionality requested by this issue is already done and live in production. My bad.

Since this means the November release of `nmdc-server` is bugged, I can issue a hotfix that undoes the change from this commit:
[`9aa5e09` (#1433)](https://github.com/microbiomedata/nmdc-server/pull/1433/commits/9aa5e09a9ddd4adde6bfa6d65887bea41390e6e5). This hotfix would NOT be merged into `main`` due to the removal of `metap_gene_function_aggregation` for the December release. 

@aclum I think the hotfix route here is low risk. Would you like me to implement it?

**Comment by aclum** [comment]
yes please

**Comment by kheal** [comment]
@naglepuff  - you'll need to fix more than just that commit for a hotfix. From that same PR the `was_generated_by` change is not applicable to the `metap_gene_function_aggregation` collection for the November release (but will be for the December release).

![Screenshot 2024-12-04 at 10 27 56 AM](https://github.com/user-attachments/assets/e761acb1-5f27-4972-8188-89c2a71d0c8c)

**Comment by naglepuff** [comment]
You're right, here's the full changelog for the hotfix: https://github.com/microbiomedata/nmdc-server/compare/v1.1.0...v1.1.1

**Comment by kheal** [comment]
@naglepuff  - This is now in production, correct?  If so, please close this ticket.

**Comment by naglepuff** [comment]
There's currently a bug, so I don't want to close this issue until #1499 is merged (the change in that PR will also be released as a hotfix)

That being said, neither dev nor prod use the `metap_gene_function_aggregation` collection in mongo. That can be deleted.

**Comment by aclum** [comment]
confirmed fixed with this release. verified by https://data.microbiomedata.org/?q=Ch8IABAAGAUiFyJLRUdHLk9SVEhPTE9HWTpLMDIxMTEi 
expected number of proteomics records based on mongo: 26
observed: 26
