### ISSUE TITLE
populating envo_ancestor

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-server#156]
`populate_envo` builds the initial edge list, and restricts to is_a - I recommend also including part_of (BFO:000050)

Also I may be misreading but it looks like `populate_envo_ancestor` uses recursion without memoization which may be inefficient... this is the code we use for relation-aware ontology graph traversal: https://github.com/biolink/ontobio/blob/54a7fe404bf396dacd8f8913e61da3966c8612fc/ontobio/ontol.py#L460-L491

**Comment by subdavis** [comment]
done in #471 and followups.
