### ISSUE TITLE
Date Histogram Options are bad

### ISSUE THREAD

**Issue by subdavis** [microbiomedata/nmdc-server#172]
* GCharts doesn't have a good date histogram.
* I tried to use https://github.com/oguzhaninan/vue-histogram-slider, but it's horribly buggy.  I managed to get it to render, but all the interactions are perilous.

![Screenshot from 2020-09-23 16-14-59](https://user-images.githubusercontent.com/4214172/94064629-f6d1ab80-fdb7-11ea-9b02-7d6fe6b07161.png)

Click-and-drag to zoom was added in a recent version, but it doesn't work.  I honestly think it needs to be on a logarithmic scale to even be usable.

Might have to actually create one of these from scratch using d3, which I'm confident I could do, but I don't know if it's the best use of my time.

Going to leave the date histogram alone for now.

**Comment by jeffbaumes** [comment]
Thanks for trying to find something else. At this point I agree we probably want to do something custom D3.
