### ISSUE TITLE
Check whether there is a valid GOLD link on omics processing

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#188]
http://lb.nmdc-dev.development.svc.spin.nersc.org/type/project/result?c%5B0%5D%5Bfield%5D=id&c%5B0%5D%5Bop%5D=%3D%3D&c%5B0%5D%5Bvalue%5D=emsl%3A499400&c%5B0%5D%5Btable%5D=project 

Click on “Open in GOLD”. There is a null value error.

Perhaps gray out the link, or fix the value if it should be available.

**Comment by subdavis** [comment]
this was fixed.
