### ISSUE TITLE
Discussion of Hierarchical Search

### ISSUE THREAD

**Issue by subdavis** [microbiomedata/nmdc-server#190]
I sat down to draft an API, and I couldn't shake the feeling that a bit more clarity was needed.

-----------

After giving this some more thought, I really can't get my head around the idea of combining Studies, Samples, and Omics Types into a single search interface.  You end up needing tabs because there are too many concepts on the page at once.

* I do not understand if this combined view is going to replace the existing "I am looking for..." pages.
* I've noticed that there are omics types not associated with any sample, and I don't understand how that's possible. [Here's an example](http://lb.nmdc-dev.development.svc.spin.nersc.org/type/project/search?c%5B0%5D%5Bfield%5D=omics_type&c%5B0%5D%5Bop%5D=%3D%3D&c%5B0%5D%5Bvalue%5D=Organic%20Matter%20Characterization&c%5B0%5D%5Btable%5D=project&c%5B1%5D%5Btable%5D=study&c%5B1%5D%5Bfield%5D=id&c%5B1%5D%5Bop%5D=%3D%3D&c%5B1%5D%5Bvalue%5D=gold%3AGs0112340).  Neither OMC or Proteomics for that study have any samples.  Is this an inconsistency?

> is it possible to enable toggle between sample and study level here

^ this is a comment from miro. I believe that no matter how we end up doing this, the author of the comment is right: you have to differentiate between study, sample, and omics processing type as your first-order search result.

# The fundamental problem

The problem we're trying to solve is not that different types of results appear on different tabs/pages, but that sometimes you want to filter one type of entity by another type of filter, and having to go from A to B, add a filter, then back to A to see results is too much of a burden.

For example, 

* filter studies by KO term (not really sure what entity KO term belongs to)
* filter study by omics type (show me studies with any amount of Proteomics)
* Filter samples by PI Name

In other words...

* I think NMDC understands that, if they want to see studies (with some aggregations and vis) they go to the study page.
* I think they are (rightfully) confused that, to see studies with Metabolomics processing on environmental samples, they have to visit 2 other pages and add filters first, then return to the study page.

# Possible incremental solution

As we discussed earlier this week, I would actually be fine with doing this work in "new" routes.  I'd like to have a simpler API, and the query string parameters could use simplifying. My goal here is to have a better idea of where this is going before I back myself into a corner.

**To start with,** we need to show all facets from Studies, Omics Types, and Samples on each page.  Probably if you're on Studies, the study facets are at the top.  

## Study search updates

I think this is what the NMDC crew expected us to show up with. We were hand-waving at the "search by KO, filter by study" part that comes before sample search results are visible, but this was an important part of the query process to show.

A couple notes;

* Flip the order of the aggregations and the search results.  Aggregations go on top.
* I stupidly only drew 1 row for study search results.  That's a list.
* Clicking on "40 samples" would take you to the sample page filtered by that study.
* Clicking on "38 MegaG" would take you to the sample page filtered by that study AND only including samples with MetaG.

![IMG_0332](https://user-images.githubusercontent.com/4214172/104493287-d619a580-55a2-11eb-964b-57ad2f2d92c6.jpg)

Another version I hacked together.  Pretend it has a "samples" button for each study, and that it has KO search.

![Another](https://user-images.githubusercontent.com/4214172/104503446-1717b700-55af-11eb-899a-a705c9ede5f9.png)

This is an incremental change.  After this is done, we can have a discussion about whether or not it is **actually necessary** to embed a list of samples in a drop-down under studies, or if that suggestion came about because of the misunderstandings about filtering above. 

## Sample search updates

Will look exactly like it already does in figma.  Maybe they `group_by study_name` for sort order, maybe we add dividers between groups, but otherwise, it's a paginated list of ~~studies~~ samples.

**Comment by jbeezley** [comment]
IMO, this is key:

> I think they don't understand that, to see studies with Metabolomics processing on environmental samples, they have to visit 2 other pages and add filters first, then return to the study page.

More generally, the search result type is mixed in with filtering condition UI.  We should find a way to make one part of the UI deciding what you are looking for, and another part providing the filtering conditions.  This will actually match better the way the backend is structured anyway.  There are tables that contain filterable conditions that can't be the target of a search directly.  The ENVO terms are an example of this, but this is hidden from the UI by associating the ENVO terms with the sample table.  I think something similar will be happening with the KO term table and processing tables for the next round of data.

**Comment by jbeezley** [comment]
One more thing, your drawing makes the search interface more explicit and less general.  E.g. we need to add UI code if a new attribute is added rather than just having it show up in the results. This is probably the direction we want to go anyway as we are finding that most of the attributes don't have any particular usefulness in search.

**Comment by kfagnan** [comment]
Thanks, Brandon. It will be useful to talk through this at tomorrow's
meeting.

I agree that some of the understanding of the navigation and filters was
getting confused, however, I want to make the point prior to tomorrow's
meeting that the team is adding a lot of missing metadata right now that
will be available next week.

1) Each data object will have a sample associated with it (there will be no
proteomics or org matter with no samples). This was missing from the EMSL
data previously because they just gave us what they had before the last GSP
meeting.
2) The concept of splitting search and filtering makes a lot of sense to me
- especially as the search gets more complex. The filtering/refinement
doesn't make sense until the user has provided some general idea of what
they're interested in - I think this was a source of confusion in the
discussion last week.
3) filter studies by KO term (not really sure what entity KO term belongs
to) - the KO terms are features of data objects that can be generated by
any omics process - it's something that links different studies, but you
can only find it once you've done all the processing and annotated the
content of the data. KO terms are something that makes the ACTG or spectra
more biologically meaningful. Like you've mentioned before, this is similar
to the navigation starting point of "I'm interested in a specific study,
environment, omics type, or KO term (functional annotation, more
generally)"... I'm just not sure that's what everyone else has in mind.

**Comment by subdavis** [comment]
I didn't' realize there were comments on figma when I wrote this.  There are a lot of [modes of communication](https://xkcd.com/1254/)

I'll respond here because many of these are direct action items.

> It is not intuitive that these are samples.  There needs to be added level of organization at the study level to improve nav.

I took that sketch from miro and let it guide my proposal above.  

> Some indication that these are samples not studies

Noted.  We can either put a table header "# samples found" at the top, or even rename the "environments" page to be "samples" maybe?

> Can the colors be replicated in the sankey from the bar and map (terrestrial, aquatic)

I'm not sure if we can do this. The trouble is that Terrestrial and aquatic both have "environmental" as a parent, so what color should that be?  Also, all unclassified buckets at each level flow together, so they could have parents and children from different groups.  

> Individual data object file name doesn't matter, just show extension.

Sure.   Will there never be multiple files with the same extension?  

> Sankey is busy and will become worse as more data is loaded.

We sort of already ran into that when we tried to break out "Unclassified" into unique groups.  If this gets out of hand, we can discuss replacing it with a more succinct graph.

> KO in one omics type but not the other

Graying the others out seems like the right choice.

> Frames around vis elements

Sure.

>

**Comment by kfagnan** [comment]
On Thu, Jan 14, 2021 at 06:01 Brandon Davis <notifications@github.com>
wrote:

> I didn't' realize there were comments on figma when I wrote this. There
> are a lot of modes of communication <https://xkcd.com/1254/>
>
yes, were attempting to consolidate to slack, GitHub, and occasional
emails... not sure how that will succeed. Figma comments seemed to be the
easiest way to let the whole team provide feedback on the design.

Thanks for responding here, I’ll pull this up in the Aim 3 discussion today.

**Comment by subdavis** [comment]
Here's a more explicit version:

Now, the filters are fixed.  You can filter whatever you want by any facet.

The results tabs have moved to the top (pretend all the chips are there, or maybe we leave the other 4 pages like they were, IDK how that fits into this).

So your filtering is now totally independent of your search results.

![Anotherone](https://user-images.githubusercontent.com/4214172/104629648-c1ebac00-5667-11eb-9759-be0b3cebed91.png)

Is this what you were thinking too, or am I lost?

**Comment by dwinston** [comment]
@subdavis I love this. Filtering and Selection/Projection (what is retrieved and how it is displayed) are separated.

**Comment by dwinston** [comment]
I wonder if this can be adjusted to accommodate consistent display of tabular results, but dynamic display of graphical filter affordances like the existing map/timeline graphical filters, but particular to a selected perspective (study, omics type, envionment, or function). Here's a quick sketch:

![image](https://user-images.githubusercontent.com/1497854/104766581-d350b900-5738-11eb-8a26-9b79c226f576.png)

**Comment by subdavis** [comment]
@dwinston this makes a lot of sense to me as long as there exists a consistent way to display results.  Which of the figma mockup result lists would you choose for the consistent results box?

**Comment by kfagnan** [comment]
I think it was agreed in the meeting that the sample result list would be
used with the study filter. I'll call it option B since that's what Faiza
showed second.

**Comment by jeffbaumes** [comment]
Agreed @kfagnan. We want to begin implementation of Faiza's interactive prototype, except that instead of filter buttons per sample there is a study list above the sample list whose main feature is to show the name, PI, and a "filter by this study" button which will add that study's ID to the active search, which will in turn subset the samples shown.

Also, we do not need to show the link to GOLD or the GOLD ID in the result list.

**Comment by subdavis** [comment]
* Study-on-top (Option A) https://www.figma.com/file/PMh2xvausdMup3AQtL1mhj/Search-by-KO-Terms-UI?node-id=209%3A10
* Sample (option B) https://www.figma.com/file/PMh2xvausdMup3AQtL1mhj/Search-by-KO-Terms-UI?node-id=178%3A0

As Jeff points out, I believe the sample table will look like option B, and there will be another table or list for filtering studies.  Are we planning to do a mockup of that?

**Comment by jeffbaumes** [comment]
My thinking is to go right to implementation of the study selection at this point and iterate afterward. A poor man's design (just a screenshot from the study result page):

![image](https://user-images.githubusercontent.com/81305/104773785-9807b780-5743-11eb-8a24-f204c211649b.png)

To the right on each study could be a button: [(filter icon) FILTER BY THIS STUDY].

**Comment by jeffbaumes** [comment]
> > To the right on each study could be a button: [(filter icon) FILTER BY THIS STUDY].
> 
> Functionally speaking, they're check boxes not radio buttons, right? Each button toggles independently.

Simplest in my mind is a button that literally adds the study ID to the global search, thus when clicked the other studies go away. If a particular study ID is already in the global search, the button could read [CLEAR STUDY FILTER] which would as it suggests remove the study filter and all studies with results would appear again. There are many ways to allow this toggling, this is just one I could see implementing that isn't too convoluted.

> What parts of the new design are we starting with? Here's my understanding:
> 
> * [ ]  new function search page with 3 facets (KO, COG, PFAM)

Just 1 facet (KO) is needed for now.

> * [ ]  study toggle list above sample list
> * [ ]  sample list (in accordance with figma option 2)

Yes to these two. The sample list will incorporate drilling into omics types and files, so there's a lot rolled into that one.

> Later, we will discuss...
> 
> * [ ]  new tabbed graphical filtering section
> * [ ]  redo sidebar to have all search criteria static, possibly with some clever sorting based on graphics tab (NMDC is currently going to think more about this)
> * [ ]  abandon sidebar nagivation altogether, so that there's only 1 static sidebar and 1 static results list with tabs for graphics (a la Donny's diagram)

Right, you can move forward without dealing with these yet.

**Comment by kfagnan** [comment]
Agree with Jeff's assessment (FWIW).

**Comment by jeffbaumes** [comment]
Faiza did a bit more work on what the study list could look like that is better than my rough idea, this should hopefully link to the specific mockup (Functions Screen iteration 3): https://www.figma.com/file/PMh2xvausdMup3AQtL1mhj/Search-by-KO-Terms-UI?node-id=248%3A18

**Comment by kfagnan** [comment]
Thanks, Jeff and Faiza - this is a great iteration.

I got feedback from the team at today's implementation lead meeting.

There is consensus on checkboxes + "filter by these/this studies/study".

There is also consensus on the need for a the aggregated omics information
under studies. The ask if if you can take the tiles from the home page -
#studies, #metagenomes, #metaproteomes, etc and carry that through to each
landing page.

Some users will want to know if there are proteomics data sets available
for a given KO search term and we want this summary stats information to be
prominent.
