### ISSUE TITLE
Results summary of samples x studies x omic types

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/nmdc-server#192]
One thing that users have asked for and we still haven't quite provided is a way to summarize the relationships between samples and omic types (the homepage stats are great but do not provide insight into how all of the data are related). I mocked up an [upset plot](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4720993/) as I find that this representation is much cleaner than my janky idea of a venn diagram. I imagine this being part of the results summary page, and would change when filters are applied (maybe even allow for clickable filtering, similar to the barplots - although not necessary). 

![image](https://user-images.githubusercontent.com/7374085/105111835-9eb16a00-5a76-11eb-9bde-b0b6bfa1d40d.png)
_MG, MT, MP, MB = metagenomics, metatranscriptomics, metaproteomics, metabolomics_

This could potentially provide the higher level summary of samples and studies (that we talked about before I think) that would complement the text based list of samples well.

Would this be difficult to implement?

**Comment by kfagnan** [comment]
@subdavis @jeffbaumes @dehays @jbeezley check out this new summary view that Pajau has put together. Would it be possible to have a summary plot like this?

**Comment by jeffbaumes** [comment]
I like this idea and have worked with Upset plots in the past. Let's get the general summary info in there (@kfagnan mentioned this in the hierarchy issue #190) and then see if we can further break things down with a visualization like this.

**Comment by kfagnan** [comment]
Thanks for naming the plots. Agreed on the general aggregation summary info
and then moving in this direction.

**Comment by jeffbaumes** [comment]
See #199 for a start of an implementation with example data.

**Comment by jeffbaumes** [comment]
This is realized as a live visualization that changes with the data, but does not currently update with the current query which I believe was @pvangay's intended behavior. Keeping this open in case we want to move to a view that updates with the query. @jbeezley is this a tough one or is it feasible?

**Comment by jbeezley** [comment]
I would guess a day or two of work from my end.

**Comment by subdavis** [comment]
done in #227
