### ISSUE TITLE
Enable file download from UI

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#220]

**Comment by subdavis** [comment]
done in #226 

Note that we don't seem to have data download urls right now, so they 404.

**Comment by jbeezley** [comment]
Download urls are derived from the [data object id]( https://data.microbiomedata.org/docs#/data_object/download_data_object_api_data_object__data_object_id__download_get).  That endpoint should redirect.  If it 404's then it means a url was not given during the ingest.

**Comment by jbeezley** [comment]
Nevermind, I see from the deployed site, you are getting the correct url.  I know some of the objects did have urls, but it seems many don't.
