### ISSUE TITLE
Study landing page seems broken, always shows Stegen

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#224]
Seems to be hitting a "Principal Investigator not found" error, e.g. on this page

https://data.microbiomedata.org/type/study/result?c%5B0%5D%5Bfield%5D=id&c%5B0%5D%5Bop%5D=%3D%3D&c%5B0%5D%5Bvalue%5D=gold%3AGs0114663&c%5B0%5D%5Btable%5D=study

**Comment by jbeezley** [comment]
I suspect this is due to the cached study result page.  When a new ingest happens the principal_investigator_id will change.  We can set a static id by providing it as a keyword argument [here](https://github.com/microbiomedata/nmdc-server/blob/master/nmdc_server/ingest/study.py#L31).

**Comment by jeffbaumes** [comment]
@jbeezley ok to close?

**Comment by jbeezley** [comment]
Fixed by #277
