### ISSUE TITLE
Display raw input files

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#230]
For many of the omics_processing objects, there should be a raw file that is not listed as part of a workflow execution. We should have the API return these data objects in a dummy "Raw data" workflow execution.

**Comment by jeffbaumes** [comment]
Assigning @subdavis to add the client side support for this now that server-side is there. I originally thought to have the client see this as a workflow step from the server API (requiring no client change) but I like explicitly having it as the output of the project.

@subdavis please add this to the client as a data object row with the workflow step "Raw data".

**Comment by subdavis** [comment]
I lost track of this task.   Should this be another button next to `Metagenome` and others?   Or should the same file just appear under every tab in the table?

**Comment by jeffbaumes** [comment]
There should be no extra buttons for raw data, just an extra row or rows in the data object table. From #248, every project should have an output which is the raw data object(s). This should appear as a row in the table with workflow name as "Raw".

Each project (omics-processing) should have I think one raw data object, but you will need to take into account that there may be multiple raw files for the metabolomics under a sample, since there are multiple metabolomics projects (omics-processings) for a sample, each with it's own raw data.
