### ISSUE TITLE
There should be five metagenomics workflow activities and some files are missing

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#247]
There should be a Reads workflow activity (and one other), and some files like "structural annotation GFF" seem to be missing. Does the server API or client somehow cut off these files? Are they being ingested properly from mongo?

**Comment by jbeezley** [comment]
There are definitely more than 10 files being returned by the biosample search endpoint.  I think the client is limiting them somewhere.

**Comment by subdavis** [comment]
Fixed in #249
