### ISSUE TITLE
Make placeholder for download button to keep table row height consistent

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#252]
Pages of data objects end up being different sizes because of this, making the pagination buttons shift a bit so you need to move your mouse each time. Not high priority, but a bit annoying.

**Comment by jeffbaumes** [comment]
Moving the pagination to the top would also help with it not popping up high on the last un-full page, is that an easy fix? I still think consistent row height is good to have for aesthetics regardless.

**Comment by jeffbaumes** [comment]
@subdavis is this still an issue or is this resolved?

**Comment by subdavis** [comment]
There aren't missing downloads anymore, but I didn't fix it yet.

**Comment by jeffbaumes** [comment]
Since this is moot with no missing downloads, and I also realized rows can resize for other reasons (e.g. text overflow in a cell), I'll go ahead and close this one.
