### ISSUE TITLE
Modify subsurface entry

### ISSUE THREAD

**Issue by kfagnan** [microbiomedata/nmdc-server#262]
![image (1)](https://user-images.githubusercontent.com/1504015/107834953-b4037680-6d4c-11eb-984a-276cb99ba21f.png)

Feedback:
Subsurface depth - needs units, and to be specific - subsurface to what? soil, sediment, Mars?

This is another where I'm not sure if this can/should be addressed here or in another part of the system. @cmungall @wdduncan @dehays

**Comment by cmungall** [comment]
Can I see the underlying json?

I don't see subsurface in the schema but depth and all like fields take a complex QuantityValue as range, which has a slot for units

https://microbiomedata.github.io/nmdc-metadata/depth/

**Comment by subdavis** [comment]
Closing as a metadata issue, feel free to reopen if I've closed by mistake
