### ISSUE TITLE
Should we keep the histograms on the analysis pages

### ISSUE THREAD

**Issue by kfagnan** [microbiomedata/nmdc-server#265]
![image (1)](https://user-images.githubusercontent.com/1504015/107835292-d053e300-6d4d-11eb-89c5-e4e28dfc2990.png)

Feedback: What is the meaning of these plots?  Data available from NMDC metaG assemblies?  Usually users would not care about it. They want to know for specific studies, what the data distribution may look like.

I think we may need a session with the pipelines/workflows group to decide which elements of the "omics types" search should be maintained.

**Comment by subdavis** [comment]
This page is gone, so I'll close this for now.
