### ISSUE TITLE
Change display names associated with metagenome assemblies

### ISSUE THREAD

**Issue by kfagnan** [microbiomedata/nmdc-server#266]
![image (1)](https://user-images.githubusercontent.com/1504015/107835341-114bf780-6d4e-11eb-89a5-3171315118c8.png)

Feedback:
Not sure about the value of listing a collection fo assemblies with encrypted ID numbers.

Possibly linked to the tooltip issue - https://github.com/microbiomedata/nmdc-metadata/issues/262

**Comment by subdavis** [comment]
This page is gone, I'll close this for now.
