### ISSUE TITLE
Create descriptive labels for sections on the data portal

### ISSUE THREAD

**Issue by kfagnan** [microbiomedata/nmdc-server#267]
![image (1)](https://user-images.githubusercontent.com/1504015/107835836-b7e4c800-6d4f-11eb-8a0f-5159f03a5de2.png)

Feedback: Need more descriptive labels for the user. For example, "Git url" is actually the workflow used, including the version number. "Data Objects" is the term we used internally for communication. For end users, they will look for common words like "workflow results."

**Comment by aclum** [comment]
Closing as wont' fix. This view isn't avaliable anymore.
