### ISSUE TITLE
Change text for organic matter characterization

### ISSUE THREAD

**Issue by kfagnan** [microbiomedata/nmdc-server#269]
I think there have been a few requests around this, tagging @corilo since I think he's the subject matter expert on how we should refer to this data.

![image (1)](https://user-images.githubusercontent.com/1504015/107835966-3f323b80-6d50-11eb-8b90-6054c2fc2d7d.png)

Feedback:
Can we just use "organic matter" instead of with the word "characterization" in the label? We can still show the long name as a tool-tip.

**Comment by corilo** [comment]
I  would keep it as natural organic matter,  which is the correct term for this type of analysis

**Comment by subdavis** [comment]
Missed a spot
