### ISSUE TITLE
Clarify meaning of map objects

### ISSUE THREAD

**Issue by kfagnan** [microbiomedata/nmdc-server#272]
![image (1)](https://user-images.githubusercontent.com/1504015/107836318-92f15480-6d51-11eb-9d6c-4136f41d79ec.png)

Feedback:
Can this be fill in with something more useful? is 48 the number of samples? maybe remove "color"?
Can there be a ? or help icon on the map to let people that they're able to click the points? or explaining that points correlate to sample size? what does the green color even mean?

**Comment by subdavis** [comment]
this is the old map
