### ISSUE TITLE
accommodate "KO:" prefix for KO term search

### ISSUE THREAD

**Issue by dwinston** [microbiomedata/nmdc-server#285]
For example, if I search for `KO:K19055`, I get 0 results (and I see a 500 error in the browser console), whereas if I put in `K19055`, I get 70 results. Given the formatting of Sam Purvine's spreadsheet of example KO terms (see aim3_integration slack channel) that include the `KO:` prefixes, I imagine many users may copy-paste prefixed KO terms into the search and assume there are no results, when in fact an un-prefixed has matches.

@subdavis what do you think?

**Comment by subdavis** [comment]
Sure, this should be pretty easy to do.
