### ISSUE TITLE
Inconsistent ordering of omic buttons under each sample

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/nmdc-server#302]
Is there any order to how the omic buttons under each sample name are displayed? They look inconsistent across samples.
![image](https://user-images.githubusercontent.com/7374085/108422679-b7cf4700-71eb-11eb-81ca-49d5af687e61.png)

**Comment by subdavis** [comment]
It's the order that they come back from the API in, which probably involves where they were found in the original tables.

I'll sort them alphabetically just to keep consistent.

**Comment by pvangay** [comment]
I'd recommend sorting them metaG, metaT, metaP, metaB, then NOM -- for consistency.
