### ISSUE TITLE
Wrighton missing info for one DOI citation

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#312]
I don't recall this being missing before we started caching DOIs. We should remove or correct that citation.

![image](https://user-images.githubusercontent.com/81305/108717141-ed757800-74ea-11eb-822b-211e70a66c31.png)

**Comment by subdavis** [comment]
This is missing in the API response. The key is there, but the value is an empty object.

![Screenshot from 2021-02-22 08-53-46](https://user-images.githubusercontent.com/4214172/108717635-80aead80-74eb-11eb-9f86-ca72342877f6.png)

**Comment by jbeezley** [comment]
The doi site sometimes sends back an error response.  This happened during the ingest.  I updated it manually.
