### ISSUE TITLE
Numbers in upset plot overlap

### ISSUE THREAD

**Issue by Lebedeva-Sonya** [microbiomedata/nmdc-server#321]
<img width="599" alt="Screen Shot 2021-02-28 at 9 26 08 AM" src="https://user-images.githubusercontent.com/77990692/109427694-6885d500-79a8-11eb-8f2d-83a5352d7097.png">

The numbers in the “samples” column are partially covered up. (please ignore the arrow)

**Comment by subdavis** [comment]
resolved by removing study column
