### ISSUE TITLE
EnvO filters do not reflect values from all biosamples

### ISSUE THREAD

**Issue by dehays** [microbiomedata/nmdc-server#322]
For the biome, feature and material search filters in the EnvO search section - the only filter values presented are from the Stegen study biosample MIxS/EnvO triad.  Values from Brodie and Wrighton biosamples are not displayed as filter options.

I checked a couple biosample JSON documents in ETL output and then in the Mongo instance (ex. Wrighton biosample gold:Gb0119260, Brodie biosample gold:Gb0191644) and see that the each have the expected EnvO values included.

Any chance the query to populate the available filter values is being restricted to study Gs0114663 (Stegen)?

**Comment by jbeezley** [comment]
The ENVO id's are formatted as `ENVO_00000446` rather than `ENVO:00000446` for these biosamples.  I'll implement a fix in my ingest.

**Comment by dehays** [comment]
@jbeezley Thanks Jon - I'll address the issue of inconsistent EnvO reference raw values in the provided biosample metadata.
