### ISSUE TITLE
Provide mechanism for providing units to the client

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#338]
Ultimately just involves communication between client and server on the portal, but may need a bit of discussion with @cmungall as to how data with units should be stored/presented vs. normalized for query.

**Comment by jeffbaumes** [comment]
A new version of MIxS will have a separate units which will make this simpler.

**Comment by jeffbaumes** [comment]
For this sprint we will take care of this on the portal for the one field where it is a concern (sample depth).

**Comment by ssarrafan** [comment]
Based on the meeting today I'll move this to "in progress".  If you'd like help setting up a meeting with @wdduncan and @cmungall to discuss how data with unites should be handled let me know.

**Comment by cmungall** [comment]
It's not clear this is actually the case...

**Comment by jeffbaumes** [comment]
> A new version of MIxS will have a separate units which will make this simpler

I'll defer to @dehays here, he had mentioned it in a meeting so I made a note but I actually have no direct knowledge on this.

**Comment by dehays** [comment]
@cmungall I'd mentioned this knowing Ramona W had said units would be specified in v6 - but I have attended enough of MIxS meetings to take a 'wait and see what happens' perspective.  MIxS v6 is also reportedly going to make a beta appearance next month - we'll see what happens.  The value now  of knowing that the intent is to specify units in some future MIxS is simply that dealing with units may someday get easier.

Do you have any thoughts on dealing with current situation where units are specified in the raw values ?  Normalize where?
