### ISSUE TITLE
Had to rename organic_matter_characterization in API to "Organic Matter" in the UI.

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#340]
I'll leave this on the pilot repo since it involves changing DB schema/API, but @cmungall since we've adopted this shorter name should it be reflected in the upstream schema for clarity?

**Comment by jeffbaumes** [comment]
@jbeezley it seems we can handle one level of this in the pilot itself so I've assigned to you.

**Comment by jeffbaumes** [comment]
@emileyfadrosh do we want to use Organic Matter consistently in the UI? We have one place (upset plot) right now where we use NOM, should that change to OM?

**Comment by emileyfadrosh** [comment]
@corilo Yuri, please advise.

**Comment by ssarrafan** [comment]
Based on meeting today I'm moving this to "in progress"

**Comment by corilo** [comment]
@jeffbaumes  if you have to use an acronym, I would use NOM (natural organic matter), which is the high level, general term that encapsulates, dissolved organic matter, soil organic matter, etc.  I would not use "organic matter" or OM.

**Comment by ssarrafan** [comment]
@jeffbaumes is this one that can be closed or should I move it to June?

**Comment by ssarrafan** [comment]
I'm moving this to the June sprint.  @jbeezley please let me know if this is something that should be assigned to someone else.

**Comment by ssarrafan** [comment]
I believe this is done. Closing and removing Backlog.
