### ISSUE TITLE
Incorporate UX design feedback

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#341]
This is feedback shared by @pvangay from the UX review.

**Comment by faiza-a** [comment]
@jeffbaumes @subdavis @pvangay 
I have added improvement suggestions based on feedback from 'Mockup Report SGCI-NMDC Usability Consulting.pdf'.
Here is the [Figma link](https://www.figma.com/file/h3v0xOrdZSYWSCRZhxQcXw/Improvements-based-on-'Mockup-Report-SGCI-NMDC-Usability-Consulting.pdf'?node-id=0%3A1).
I have added descriptions on the mockups. Let me know if there are any questions.

**Comment by jeffbaumes** [comment]
I'm experimenting with keeping conversation on GitHub issues, hopefully the right people are notified.

Thanks @faiza-a. Some of these small tweaks are obvious improvements and we can go ahead and do them, but a few of the ideas require approval, such as:

* Should we make the major change of moving the search criteria from the sidebar to above the search results? My recommendation is no, at least at this time. It would require a lot of UX rework.
* Should the whole sample area be clickable to go to the details page?
* What version of the details chevron button should we use?

I suggest people (@pvangay @kfagnan @emileyfadrosh) go to Figma and comment there or on this issue with your thoughts. If you have trouble accessing try logging in, and if you still have trouble contact Faiza and she can get you access.

**Comment by pvangay** [comment]
Thanks for starting the discussion all.

- agree with not moving the search criteria. helpful to keep in mind though.

- Not sure i follow - which one is this?
> Should the whole sample area be clickable to go to the details page? 
- chevron button: i prefer the shaded box (3rd one), followed by the shaded circle

**Comment by kfagnan** [comment]
I don't think we should move the search criteria.

I'm also not sure what is meant by the whole sample area being clickable...
you mean the names of the files, samples, etc?

I also prefer the shaded box for the chevron button.

Thanks!
