### ISSUE TITLE
Requirements for data landing pages

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#342]
This issue is to track requirements for data landing pages.  Please link to any related documentation, mock-ups, or diagrams developed.  This sprint will not be focused on making these changes but just on the requirements.

**Comment by ssarrafan** [comment]
@elishawc let me know if this should be assigned to a different person or a different sprint in the future.

**Comment by elishawc** [comment]
@ssarrafan - what sprint was this for? April (not in current project list)? May?

**Comment by ssarrafan** [comment]
@elishawc I did add this to the April sprint earlier this week but if it should be moved out to May sprint let me know.

**Comment by elishawc** [comment]
Met w/ Wiley to do demo of portal and discuss options for collaboration moving forward. Next steps for us: 
1. survey other publishers to see if they are interested in a joint publisher info session. if yes, schedule
2. inform Wiley when we are ready for more UX feedback

On their end, they will start reviewing journals and editors that are relevant to the community/data types the NMDC serves and creating us a contact list for iterative design of data landing pages.

**Comment by elishawc** [comment]
Met with Wrighton lab to discuss landing pages - notes here: https://docs.google.com/document/d/10VM3DNrPO2mUVW-81zi2eSBzbkW1lMKLDvpYitvDKBw/edit

**Comment by elishawc** [comment]
Good discussion with James (FICUS PI), PLOS editor re: landing pages. Next are Eoin/Ulas (FICUS) and Joanne (TrIP), and to schedule joint publisher call.

**Comment by elishawc** [comment]
Met with Joanne (TrIP) today. One more call w/ Eoin tomorrrow, then will summarize the discussion. 
Also, likely will be meeting with publishers 1 June to get their feedback. 

Then this can probably be closed, and a new issue that consolidates that input and moves it into design with Kitware can start in June sprint (FYI @ssarrafan)

**Comment by elishawc** [comment]
@subdavis - is there a specific point that should be discussed atm?

**Comment by elishawc** [comment]
@ssarrafan - this can likely be closed, and a new issue around design for study page 2.0 with kitware for June sprint

**Comment by ssarrafan** [comment]
Closing this issue per @elishawc and created a new issue for June at https://github.com/microbiomedata/nmdc-server/issues/394.  New issue is assigned to @faiza-a
