### ISSUE TITLE
Portal Help - data products

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#356]
The term "data objects" is not clear until clicking on it and seeing the file extensions. Listing multiple fastq files add confusion (especially to those not familiar with JGI processing procedures which generates 2 fastq files). Researchers want to know how these data objects were generated.

Priority - medium
Urgency - low

**Comment by jeffbaumes** [comment]
We have included all the file descriptions available at this point. This would require information from data product generators to provide more descriptions through the schema.
