### ISSUE TITLE
Portal Search - environments

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#360]
Current search is not intuitive for researchers who don't work with samples collected from environments. More effort is needed to make this term more inclusive (include those who work in host-associated samples, lab samples, etc.).

Priority - medium
Urgency - medium

**Comment by jeffbaumes** [comment]
This sounds like a schema and data curation task first, and we can add this to the portal afterward.

**Comment by ssarrafan** [comment]
Not actionable at this time per @pvangay. Closing issue.
