### ISSUE TITLE
Portal Search - smart text search

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#364]
autocomplete, autosuggest, or enable search results with partial matches. this is helpful so that exact matches aren't necessary. Search space should include the accompanying descriptions/help text, aliases, etc.

Priority - Low
Urgency - Low

**Comment by kfagnan** [comment]
This seems to be a large scope, but I'll leave it to you all to come up with the appropriate label @subdavis @jbeezley
