### ISSUE TITLE
Portal Search - Taxonomy

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#365]
Search by taxonomy (all levels)
Also have separate taxonomy search for bins compared to annotated genes/contigs (EF)

Priority - High
Urgency - Low

**Comment by jbeezley** [comment]
We will need additional information to complete this.  In particular, which fields in the provided data does this relate to and how do they match with the search term?  Is all of the necessary data currently provided by the workflows?

**Comment by ssarrafan** [comment]
@pvangay and @emileyfadrosh if this issue can be worked on in terms of requirements and specification for this sprint let me know. Otherwise it's been removed from the May sprint.

**Comment by ssarrafan** [comment]
@emileyfadrosh suggested holding off on this till September 2021. I've added the backlog label and removed from the sprint.

**Comment by ssarrafan** [comment]
Assigned to @emileyfadrosh to work on requirements.

**Comment by ssarrafan** [comment]
Moving this to "backlog" per the NMDC sync meeting today. FYI @emileyfadrosh

**Comment by emileyfadrosh** [comment]
Closing this as we will revisit for FY24.
