### ISSUE TITLE
Portal  Visualization - map zooming and legend

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#366]
Allow zooming in and out of map to visualize samples. Whether it's manual or automatic. This is helpful when there are a lot of samples that were collected in close proximity to each other.
Related to https://github.com/microbiomedata/nmdc-metadata/issues/327

The map needs a clear legend. Researchers expect to be able to interact with the map. While most people liked the map, others did not find it useful because geographic location does not matter for their work.

Priority - High
Urgency - High (legend)

**Comment by jbeezley** [comment]
This seems largely client-side only, but there may be an additional need on the API to provided geospatial lookups/binning.

**Comment by kfagnan** [comment]
@subdavis any sense for the level of effort on this, do you need things from the team for this issue to make sense?

**Comment by ssarrafan** [comment]
Per @jbeezley Brandon doesn't have bandwidth to finish this for May sprint. I'm moving this to the June sprint. @pvangay @emileyfadrosh I assume this is still high priority and to be scheduled for June.

**Comment by pvangay** [comment]
yes, that makes sense. thank you!

**Comment by subdavis** [comment]
It's the end of the sprint and I haven't been able to finalize this.  I would like to get it done before the portal promotion that was delayed to next week, but technically it will be in the next sprint.  I'm hoping to have this done by the end of this week.

**Comment by ssarrafan** [comment]
> @ssarrafan It's the end of the sprint and I haven't been able to finalize this. I would like to get it done before the portal promotion that was delayed to next week, but technically it will be in the next sprint. I'm hoping to have this done by the end of this week.

Thanks for the update @subdavis. I will move it to July.

**Comment by subdavis** [comment]
This is in progress.  Need to get clustering working, I'm just running into [apparently known] [issues with icons](https://vue2-leaflet.netlify.app/quickstart/#marker-icons-are-missing).

I expect this to be completed and deployed tomorrow.

![Capture](https://user-images.githubusercontent.com/4214172/124671860-1ee05600-de84-11eb-957c-167a7f0f4392.PNG)
