### ISSUE TITLE
Portal Visualization - sample dashboard

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#368]
Ability to select multiple samples with various data types and interactively display aggregated information (eg, QC stats, high-level taxonomy or function) through a set of user-select dashboards or other visuals. Example: DNAnexus Apollo

This will likely take a considerable time to develop, but we should begin scoping aspects of how this would work. Input from key stakeholder groups will be important. 

Priority - High
Urgency - Medium

**Comment by jeffbaumes** [comment]
This is almost certainly extra large, but needs more discussion.

**Comment by mslarae13** [comment]
This issue was started _I think_ BEFORE we had the JGI and EMSL tabs in the submission portal UI.

I expect that work was the extra large part. The request here now is make the "templates" multi select.
Then, when the "samples" page is rendered, it provides the DH interface for all checked sample types.

This also requires an update to the postgres -> mongo ingest code.

@pkalita-lbl thoughts?
@naglepuff

**Comment by ssarrafan** [comment]
@mslarae13 I brought up this issue today at the infra sync meeting and there was a lot of confusion about the original scope/idea.  I think it may be better to just close this old issue and open a new one with what's needed but I will start a Slack discussion on this next week when you're back.  
FYI @jeffbaumes @naglepuff

**Comment by mslarae13** [comment]
Mis-read issue and misunderstood the assignment here.
Incorrectly linked to Milestone, will remove & make a new issue

**Comment by ssarrafan** [comment]
@mslarae13 can this one be closed?

**Comment by mslarae13** [comment]
IDK, it's not submission portal like I thought. I misread it.
@aclum thoughts? I think this is data protal

**Comment by aclum** [comment]
I think so too, however the related milestone has been canceled in favor of focusing on notebooks and visualizations would be a focus for the renewal so I will remove the priority label and backlog this.

**Comment by ssarrafan** [comment]
This issue is from 2021 and not slated to be done in 2025. Will revisit and create a new issue after renewal. @aclum
