### ISSUE TITLE
Portal  Homepage orientation

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#372]
Need better orientation: links to NMDC website/github/where to send help desk items/social media feeds/newsletters/funding statement & acknowledgement

Priority - High
Urgency - High

**Comment by kfagnan** [comment]
Would like to understand this a bit better. I don't think it's a huge amount of work... but needs a strategy

**Comment by aclum** [comment]
@emileyfadrosh did this get covered by other work in the last 2.5 years or this is still needed?

**Comment by aclum** [comment]
No comments since January..closing.
