### ISSUE TITLE
Portal Search - filter by data product or file type

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#373]
Allow filtering of search results by file type. For example, download only KO files from their specific search results.

Will need to determine if annotation JSON enables retrieval of relevant files instead of just a presence/absence in a sample. From Emiley: Ability to access relevant data results and/or files based on search criteria across multiple samples/projects. Example: retrieve KO files based on function search across omic types, not just the list of samples that contained that function term

Priority - High
Urgency - Medium

**Comment by jbeezley** [comment]
I don't think we have the information in the data_object's yet.  The best we could at the moment is to parse the description field or the file extension.

Once we have the data necessary to do the search, the server side components for this:
- [ ] Add "data product" or "file type" as a query-able field (however it is provided in the data)
- [ ] Expose `POST /data_object/search` for searching files directly

The server-side work on this is a probably `Small`.  The UI and client modifications may be more complicated.

**Comment by aclum** [comment]
@jeffbaumes  I'm closing this b/c you can filter by workflow execution activity or by file type. cc @ssarrafan
