### ISSUE TITLE
Make number of search results more noticeable

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/nmdc-server#391]
I'd like to propose moving the number of sample results returned closer to the sample list (maybe at the top of the list?), and/or highlighting it so that it stands out more. I actually thought this wasn't implemented yet because I never noticed it by the filters. I think naturally our eyes gravitate toward the sample list after applying a search. We sat down with Eoin's group today to review his dataset and he was asking for this information as well - and it wasn't obvious to the 5 of us on the call (who are already very familiar with the NMDC portal). I can get more user feedback about this if needed @kfagnan

**Comment by subdavis** [comment]
> I'd like to propose moving the number of sample results returned closer to the sample list (maybe at the top of the list?)

* Make it bigger and closer to the sample list.
* Also maybe change "results" to biosamples, but not yet.
