### ISSUE TITLE
Problems downloading some Brodie NOM data files

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/nmdc-server#392]
Entering this issue for @mslarae13 as well as Eoin, who have both reported having problems downloading files (I haven't been able to replicate it myself)

When trying to download certain NOM files, Montana received this error:
![Screen Shot 2021-05-26 at 6 49 27 PM](https://user-images.githubusercontent.com/7374085/119865964-1e41c080-bed1-11eb-8557-c08dcb8d64a6.png)

She was logged in with her ORCID. And it doesn't seem to be for all NOM files - just some. Will let her chime in if she's able to narrow down which files caused the problems... but thought I'd at least log this here in case the team is able to do some checks.

**Comment by jbeezley** [comment]
That appears to be an issue with the DNS configuration of nmdcdemo.emsl.pnnl.gov.  From what I can tell, it seems to be fixed now, so maybe it was a temporary issue.  If it is just some files, they might have been deleted from that server.

In any case, the portal just redirects to the url provided in the metadata.  I haven't seen any issues logged by sentry in our redirection service.

**Comment by pvangay** [comment]
btw @mslarae13 noted that this happened when she was on the VPN... is that expected?

**Comment by mslarae13** [comment]
After conversation with @corilo , yes that was expected. but it's fixed! So I'm going to close this issue as it's been solved
