### ISSUE TITLE
Accept <return> keypress to submit KO term for search

### ISSUE THREAD

**Issue by dwinston** [microbiomedata/nmdc-server#399]
![image](https://user-images.githubusercontent.com/1497854/120558931-2f596880-c3ce-11eb-8cb8-76525d35e77f.png)

It took me a bit to figure out that I *had* to click the plus (+) button to submit a search for a KO term. I would like to be able to paste in a KO term ID and press `<return>`/`<enter>` to submit the search.

**Comment by subdavis** [comment]
closed in #450
