### ISSUE TITLE
x axis labels in upset plot

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/nmdc-server#400]
can the omic types be reordered MG, MT, MP, MB, NOM? so it'll be more consistent with how other things are ordered.

also, i really like that there are tooltips to explain the acronyms but they're not obvious at first. could we replace the x-axis labels with icons derived from a [figure](https://drive.google.com/file/d/1w9P7I26lsp1EKr2m3RplvtLz4epU9h6D/view?usp=sharing) that our creative services dept put together?

**Comment by subdavis** [comment]
Add a legend to the bottom explaining the abreviations.  Hold off on images for now.
