### ISSUE TITLE
Make buttons on study landing page clickable

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/nmdc-server#408]
Sorry if this was captured elsewhere, I can't find it.

Users tend to think these gray buttons are clickable. Whether they take the user back to the search page with the study and omic type selected, or something else, it would be great if these were interactive.
![image](https://user-images.githubusercontent.com/7374085/122610237-24404280-d034-11eb-834a-1349a5b12684.png)

**Comment by subdavis** [comment]
closed in #452
