### ISSUE TITLE
Collection date should be available on the sidebar

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#410]
Collection date is filter-able via the chart but it does not appear in the sidebar. I believe this was an oversight and should be added.

**Comment by ssarrafan** [comment]
Should I add this issue for the July sprint or is this one for the backlog?  @jeffbaumes @subdavis @pvangay @emileyfadrosh

**Comment by subdavis** [comment]
I think I can just do it.   Please add it to the sprint.
