### ISSUE TITLE
Move docker image to microbiomedata org.

### ISSUE THREAD

**Issue by subdavis** [microbiomedata/nmdc-server#442]
In order to get the docker images for the portal out of Kitware's exclusive control and into a place where NMDC can own them, we'd like to move these images to github container registry in the microbiomedata github organization.

I will need to work with an administrator of the microbiomedata github org to get this set up correctly.  In particular, my github account, subdavis  will need permissions to create packages.

This is a chicken-and-egg problem, because you can't change permissions on packages until they exist, and I don't have permissions to create packages, so the solution may involve making me a temporary organization owner so I can push initializations, add myself as the admin for the new packages, and then make me a normal member again.

Github Container Registry is new and relatively immature, but I think it's a better solution than creating a new organization in DockerHub that someone has to be responsible for.

https://github.com/organizations/microbiomedata/settings/packages is a good place to start

**Comment by dwinston** [comment]
Alternative registries:
- Docker Hub - NMDC has an active DockerHub organization - <https://hub.docker.com/u/microbiomedata>. @scanon @hubin-keio is this a paid account such that e.g. @subdavis can be added to push?
- NERSC runs a Registry using the Harbor software for the Spin platform, where data.microbiomedata.org is hosted - <https://registry.nersc.gov>. Could seek access to that registry via kitware-held nersc account(s).

**Comment by subdavis** [comment]
https://hub.docker.com/u/microbiomedata seems ideal to me, my user account is https://hub.docker.com/u/subdavis

If I can't get my user account added, I could also make do with a push access token.
