### ISSUE TITLE
Add new workflow execution mode for transcriptomics to pilot database

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#447]
From Jon Beezley:

It's not too hard to add, but I don't really have time to do it, so I'm putting this together to summarize the places where you need to make changes to add it in.  There are many workflow types that all behave the same, so it is fairly mechanical to do.

I *think* this sums up the changes that are necessary:

- [x] Add new models following the example at:
https://github.com/microbiomedata/nmdc-server/blob/master/nmdc_server/models.py#L499-L513

- [x] also note where the types should be added following:
https://github.com/microbiomedata/nmdc-server/blob/master/nmdc_server/models.py#L617-L643

- [x] Generate a migration following:
https://github.com/microbiomedata/nmdc-server#generating-new-migrations

- [x] Add a schema for the model and add it to the OmicsTypes union:
https://github.com/microbiomedata/nmdc-server/blob/master/nmdc_server/schemas.py#L445-L446
https://github.com/microbiomedata/nmdc-server/blob/master/nmdc_server/schemas.py#L544

- [x] Follow the examples of the other workflow executions in table.py
https://github.com/microbiomedata/nmdc-server/blob/master/nmdc_server/table.py

- [x] Add a query schema class:
https://github.com/microbiomedata/nmdc-server/blob/master/nmdc_server/query.py#L645-L648
https://github.com/microbiomedata/nmdc-server/blob/master/nmdc_server/query.py#L808-L817

- [x] You can add it to the database summary as well, but I don't think this information is actually used:
https://github.com/microbiomedata/nmdc-server/blob/master/nmdc_server/crud.py#L43
https://github.com/microbiomedata/nmdc-server/blob/master/nmdc_server/aggregations.py#L110-L121

- [x] Generate ingestion from the mongo table metatranscriptome_activity_set.  There are no custom properties, so it should be exactly like the other simple workflow types:
https://github.com/microbiomedata/nmdc-server/blob/master/nmdc_server/ingest/pipeline.py#L134-L136
https://github.com/microbiomedata/nmdc-server/blob/master/nmdc_server/ingest/all.py#L103-L110

**Comment by ssarrafan** [comment]
@zachmullen we had our mid-sprint review today so I'm checking in with folks who have issues for this sprint to see if you need help with anything, are blocked by anything or have any concerns about completing your issue by the end of July.  Let me know if there are any concerns.

**Comment by zachmullen** [comment]
Hi @ssarrafan , thanks for checking in. I am not blocked on anything at this point.

**Comment by subdavis** [comment]
New workflow visible in portal

![Screenshot from 2021-07-26 16-19-59](https://user-images.githubusercontent.com/4214172/127053696-85792cca-153a-4162-aa31-dd965b6d0e63.png)
