### ISSUE TITLE
Sample metadata issues from Chris

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/nmdc-server#448]
Consolidated issues that haven't already been captured elsewhere from @cmungall's [document](https://docs.google.com/document/d/1IA5MfLbIdI9TzukcC6beocnuh_ovEdmY521KXaGk_7g/edit#) here:

- [x] Allow for alternative ways to search for KEGG terms (e.g. by function name instead of KO term)
- [ ] Make sure that units are explicit in the data object (i.e. Depth search is in cm, but this field is stored in meters so the search doesn't work correctly). This may be related to the [depth range issue](https://github.com/microbiomedata/nmdc-metadata/issues/355).
- [ ] Every CURIE should be hyperlinked: IGSN, GOLD, ENVO. See https://microbiomedata.github.io/nmdc-schema/identifiers.html. When displaying a CURIE, always retrieval minimal metadata to display. MUST have a label field, this should be shown. SHOULD have a description field, this may be shown as a tooltip
- [ ] Provide tooltips for every field using the description field from schema
- [ ] Indicate when a term is from MIxS
- [ ] All quantitative values should show units, this is stored in the JSON as both the verbatim value (e.g. 0.15m) and as a normalized tuple (value=0.15, unit=m)
- [ ] Individual sample page - consider adding: omics processing metadata and sample prep metadata, elevation, environmental package

### Nice to have:
- [ ] GOLD - if sublevels are non-discriminatory then auto-expand; e.g. if I am looking already at fracking samples, then I have to click 5 times to see
- [ ] Consider showing some key metadata terms (EnvO) with each sample (in the sample results list)
- [x] Allow search results to be bookmarkable 
- [x] Improve UI of individual Sample Page - too much white space on the right. consider map.

**Comment by ssarrafan** [comment]
I assigned this to @cmungall and @pvangay to make sure we can clarify what we need Kitware to do before we assign it to them.  @dehays can these be discussed at the metadata meeting next week?

**Comment by ssarrafan** [comment]
This is on the agenda for the metadata meeting on Dec 1st so I'm moving this to the December sprint. @dehays @pvangay

**Comment by ssarrafan** [comment]
@pvangay and @cmungall would you like me to keep this issue open still?  I've created GH issues for Brandon from the list but let me know if this issue should still remain open until everything is done.

**Comment by pvangay** [comment]
i think it's already captured elsewhere, makes sense to close.

**Comment by ssarrafan** [comment]
Closing this issue since the details and tasks are captured in other GH issues.

**Comment by aclum** [comment]
@ljohnson09 previous user research from Chris on the data portal

**Comment by aclum** [comment]
Note a lot of these tickets are not actually complete, but rather that we eventually ended up with duplicate tickets and so some of the older tickets got closed out but are still not resolved.
