### ISSUE TITLE
Changes for Monday 7.12.21

### ISSUE THREAD

**Issue by subdavis** [microbiomedata/nmdc-server#450]
- [x] Left search bar, KO terms, clarify that its limited to samples that have queried KO terms (see row 6 of the testing spreadsheet)
- [x] Left search overall, please remove the following from the list [1]
- [x] Left search overall, please rename “geo loc name” to “geographical location name”
- [x] Left search, latitude, sometimes the boxes around the numbers turns red, determined that it’s a bug on the call and can be fixed. (lower priority)
- [x] Bioscales study page, manually fix the dataset citation area and remove the publications sections, see screenshot below [2]
- [x] Remove multiomics from study page
- [x] #399
- [x] #408
- [ ] #410
- [x] Reorder the left search bar as follows (top to bottom). [3]
- [x] Replace citation [4]

# Remove facets [1]

Habitat
NCBI taxonomy name
Sample collection site
Community
Location

# Bioscales study page [2]

![BioscalesPage](https://user-images.githubusercontent.com/4214172/125080426-c8953200-e092-11eb-88ec-4fe53953a6cd.png)

# Reorder [3]

Study
PI Name

Sample
Depth
Latitude
Longitude
Geographical Location Name

GOLD Ecosystems
GOLD Classification

EnvO
Environmental Biome
Environmental Feature
Environmental Material

Omics Processing
Omics Type
Instrument Name
Processing Institution

Function
KO term

## Citation [4]

```
Doktycz, M. (2020) BioScales - Defining plant gene function and its connection to ecosystem nitrogen and carbon cycling [Data set]. DOE Joint Genome Institute. https://doi.org/10.46936/10.25585/60000017
```

**Comment by ssarrafan** [comment]
Added this to the project board so everyone can see all the work being done.  Thank you!
