### ISSUE TITLE
Ability to enable or disable data at the study level

### ISSUE THREAD

**Issue by subdavis** [microbiomedata/nmdc-server#451]
We could add an "enabled" column at the study level and make sure to adjust all the queries.

This is a great example of something that would be significantly easier to accomplish in ElasticSearch.

**Comment by aclum** [comment]
@ssarrafan  @jeffbaumes  anyone have more info about what this request was about? Only showing results if we had workflow results?

**Comment by aclum** [comment]
Closing, unclear what the original request was.
