### ISSUE TITLE
Fix front page counts

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#47]
Fill in all missing statistics on main page.

**Comment by subdavis** [comment]
See https://github.com/microbiomedata/nmdc-server/pull/41 -- this is how it currently looks.

**Comment by jeffbaumes** [comment]
Excellent, missed that one. Do we have file size on data objects? If so, can we bring back the total size for the "Data" metric?

**Comment by subdavis** [comment]
done properly in #65
