### ISSUE TITLE
Dev migrations are failing

### ISSUE THREAD

**Issue by subdavis** [microbiomedata/nmdc-server#472]
```
Checking for script in /app/prestart.sh
Running script /app/prestart.sh
   user
----------
 postgres
(1 row)
Creating and migrating database
ERROR:  database "nmdc_a" already exists
ERROR:  database "nmdc_b" already exists
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade cab1403436ff -> 28f470a18472, empty message
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DuplicateTable: relation "uq_envo_ancestor_id" already exists
```

Caused by #471 

https://github.com/microbiomedata/nmdc-server/blob/7575a03ca1a5d229b306303264991d7ba500a51e/nmdc_server/migrations/versions/28f470a18472_envo_tree.py#L29

conflicts with earlier migration

https://github.com/microbiomedata/nmdc-server/blob/main/nmdc_server/migrations/versions/cab1403436ff_metatranscriptome.py#L83

Copy/paste?

**Comment by zachmullen** [comment]
Hm, I didn't edit that file manually or anything, but I must have gotten my local database in a weird state when I made the migration.

On other projects, we have a "check-migrations" step that runs during CI to make sure no migration steps were forgotten or invalid. If it's easy to add something like that with alembic, we should do that.
