### ISSUE TITLE
View bulk download file count by type without logging in

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#506]
Instead of completely closing off the bulk download UI when not logged in, let the user see the file types, counts, and size, but disable download. The new UI might look something like this:

![image](https://user-images.githubusercontent.com/81305/132863131-0f520f04-f6ce-449d-b1ca-520ce2a8c1c3.png)

**Comment by subdavis** [comment]
I can do this.

It may be worth considering that a user might be frustrated if they don't notice the grayed out download button and spend a lot of time curating a bulk download and then have to start over.  This is similar to the issue where someone sets up a search and then realizes they have to log in, but it delays that realization.

We could potentially look back into passing the active query as state through the oauth flow, such as by using https://github.com/msgpack/msgpack-javascript or base64 encoded json.

That would bring back copy/pasteable links to query terms.

**Comment by jeffbaumes** [comment]
Ah, I wasn't thinking about the fact that query state and bulk download state reset on login. Yeah I think we'd need to have persistent state of those things through login or this would be super frustrating. Could we get that working as well this month or is that too much to take on? Query reset (e.g. when visiting the main NMDC and coming back) was a separate stated frustration from the user interviews so it has multiple benefits.

**Comment by subdavis** [comment]
I'm interested in the state persistence problem, so i'll look into that since we're blocked on some other issues right now.
