### ISSUE TITLE
Back button should step through prior filter changes

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#515]
Would there be a downside to pushing the URL to browser history on filter change? This would allow the back button to undo changes to the filter.

**Comment by subdavis** [comment]
I chose `router.replace()` because `push()` seemed to flood the history a bit, but we should check with the NMDC team about this because that was just my personal preference.

**Comment by jeffbaumes** [comment]
It caused unexpected behavior when I logged in, changed the filters, then pressed back. It gave an error since the browser was trying to go back through the Orcid login redirects (which should be expected to fail). My expectation was to go back to those prior URLs when pressing back. But maybe others will see it differently. If the URL changes frequently with map or timeline interaction, for example, it would be tedious to press back through dozens of minor filter changes.

**Comment by aclum** [comment]
@jeffbaumes  is this still an issue?
