### ISSUE TITLE
October Release Testing Feedback

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#537]
This issue is to document and track testing feedback and fixes in one place

**Comment by ssarrafan** [comment]
Testing feedback from today is noted in the[ testing worksheet ](https://docs.google.com/spreadsheets/d/1wb7eXqDTSOv4KaPy_uGjU0UBqURKBsL-1QlN3dhSxsA/edit#gid=0)and there is a [Google doc](https://docs.google.com/document/d/1GjX9Drj_A-myyIRPKtAPvLz30LoKaAMNELWPk2hg-oM/edit) with screenshots and other details. 


- [ ] Two Gold IDs for all samples in Brodie study (already reported on Slack)
- [ ] Spruce data isn’t sub-setting properly, see row 6 of testing spreadsheet and page 1 of Google doc for screenshot
- [ ] Faceted search is not working the subsetting is not working for the Spruce data (PI name Schadt)
- [ ] Funding sources, needs to be a whole block of text, not a single line, see page 2 of Google doc for screenshot
- [ ] Can you please add a PI image on the study page for the new Spruce study. Photo on page 3 of Google doc. 
- [ ] Link to user guide at the top of the site as discussed

**Comment by ssarrafan** [comment]
> Thanks, @ssarrafan, I'm working on these issues now, except for two:
> 
> > Two Gold IDs for all samples in Brodie study (already reported on Slack)
> 
> This is a metadata problem, so I think it needs to be corrected in Mongo. Is that right?
> 
> > Can you please add a PI image on the study page for the new Spruce study. Photo on page 3 of Google doc.
> 
> Profile image is part of the NMDC schema: `PersonValue.profile_image_url` -- our server doesn't host images. This image will need to be added to the `principal_investigator` object of the study.

@dwinston or @dehays can one of you please add Dr. Schadt's photo from the third page of this [Google doc](https://docs.google.com/document/d/1GjX9Drj_A-myyIRPKtAPvLz30LoKaAMNELWPk2hg-oM/edit) to NERSC or wherever the PI images need to live?

**Comment by subdavis** [comment]
Thank you for the detailed report. I can reproduce this now.

```
2021/10/13 01:28:59 [error] 11#11: *113 upstream prematurely closed connection while reading upstream, client: 128.55.212.127, server: localhost, request: "GET /data/1781_100351/qa/1781_100351.filtered.fastq.gz HTTP/1.1", upstream: "http://10.42.8.144:8080/1781_100351/qa/1781_100351.filtered.fastq.gz", host: "data.microbiomedata.org", referrer: "https://data.dev.microbiomedata.org/"
```

From the data container, I see a 206 return code.

```
128.55.206.110 - - [13/Oct/2021:01:30:58 +0000] "GET /1781_100351/qa/1781_100351.filtered.fastq.gz HTTP/1.0" 206 871207475 "https://data.microbiomedata.org/?q=ChQIABACGAIiDCJNZXRhZ2Vub21lIg==" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.58 Safari/537.36" "216.63.191.253"
```

I can see that each request failes (for me) after exactly 1 GB has been downloaded.  If the download is resumed, it runs until exactly 2GB is downloaded.  

I suspect a proxy configuration issue, I'm going to recruit some help from another member of the team tomorrow.

**Comment by ssarrafan** [comment]
Closing this as October release is in prod now
