### ISSUE TITLE
Undo portal-side data manipulation

### ISSUE THREAD

**Issue by subdavis** [microbiomedata/nmdc-server#540]
- [ ] Renaming of `nmdc:MetagenomeAssemblyAnnotation` and `nmdc:ReadBasedAnalysisActivity` to handle inconsistent types.
- [ ] Disabling of data objects missing `file_type` and `file_description`.  Data objects without `data_object_type` will not appear in the portal.
- [ ] Disabling of Lipidomics data.
- [ ] Disabling of `gold:*` ids found in `alternate_identifiers` field.
- [ ] Hack to replace "Metagenome" workflow name for Metabolomics workflows
- [ ] Undo ingest-time combining of alternate identifires, GOLD_biosample_identifier, INSDC_biosample_identifiers

**Comment by aclum** [comment]
Closing as not needed given not activity in 3 years.
