### ISSUE TITLE
Hyperlink every CURIE

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#553]
Every CURIE should be hyperlinked: IGSN, GOLD, ENVO. See https://microbiomedata.github.io/nmdc-schema/identifiers.html. When displaying a CURIE, always retrieval minimal metadata to display. MUST have a label field, this should be shown. SHOULD have a description field, this may be shown as a tooltip

Related to #448

**Comment by ssarrafan** [comment]
@turbomam @mslarae13 I'm closing this old issue assigned to Brandon.  If we still need to work on CURIE hyperlinks let me know.

**Comment by mslarae13** [comment]
seems related to / replicating https://github.com/microbiomedata/nmdc-runtime/issues/307 
So probably good to close. Problem is, we have some IDs that aren't real curies, so they'll never resolve.

**Comment by aclum** [comment]
This would still be good to have, related to https://github.com/microbiomedata/nmdc-server/issues/1024. nmdc-server code should be able to use prefixes defined in the schema to determine which curies are resolvable and which aren't.

**Comment by ssarrafan** [comment]
I'm closing this issue. Hasn't been touched in almost a year.  Issue #1024 is already on the data portal board.
