### ISSUE TITLE
Use schema description field for tooltips

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#554]
Provide tooltips for every field using the description field from the schema

Related to #448

**Comment by ssarrafan** [comment]
Brandon, please add T-Shirt size and any questions. Team is trying to get an idea of the time/effort to do this.

**Comment by subdavis** [comment]
I believe this is duplicate of #505

![Screenshot from 2021-12-06 13-09-21](https://user-images.githubusercontent.com/4214172/144899048-60a757a9-7dc7-483e-929e-a1991521b52f.png)

This schema description is in the popup menu because it would be too large for a tooltip.

Can this be closed?

**Comment by ssarrafan** [comment]
Double checked with Pajau and closing this one since it's a duplicate.
