### ISSUE TITLE
Indicate MIxS terms

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#555]
Indicate when a term is from MIxS

Related to #448

**Comment by ssarrafan** [comment]
Brandon, please add T-Shirt size and any questions. Team is trying to get an idea of the time/effort to do this.

**Comment by subdavis** [comment]
Please provide information/documentation about how to know if a term comes from MIxS.  Is this consumable from code, or will we need to maintain own mappings?  Where should we be looking for this info?

Thanks.

**Comment by pvangay** [comment]
@ssarrafan this should be reassigned to Mark M. and Bill. Mark is currently working with Montana to identify sources of each term (where they came from) for display on the metadata submission interface. Once that information is available, hopefully Bill can include that information in the schema so that Brandon can also display it via the portal.

**Comment by ssarrafan** [comment]
@pvangay ok I've assigned this to Bill and Mark.  Is the expectation that this will be done this month or can I move this to the January sprint?

**Comment by pvangay** [comment]
good question for @turbomam

**Comment by subdavis** [comment]
I'm already consuming `nmdc-schema` repo as a git submodule, so any JSON file that exists in that repo is something I can grab and use.   Other kinds of data (xml, yaml) would probably also be OK, but JSON is preferable.

**Comment by ssarrafan** [comment]
@wdduncan can this issue be closed?

**Comment by wdduncan** [comment]
@ssarrafan I do not know. What do you think @subdavis ?

**Comment by turbomam** [comment]
Sorry, I'm late to the game.

Where should it be indicated that a term comes from MIxS?

If a term is to be used in the NMDC DataHarmonizer, it will be marked with a `disposition` of `borrowed` or `use as-is` on the [mixs_packages_x_slots tab of Soil-NMDC-Template_Compiled](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit?pli=1#gid=877213473)

**Comment by subdavis** [comment]
* if possible, it would be great to have a json version of https://github.com/microbiomedata/nmdc-schema/blob/main/src/schema/mixs.yaml in the schema.  A util function is only useful if the resulting json will be checked in.  If a util is added that I need to run myself, it would be easier for me to convert the file myself.
* I'm not totally clear on how this should look in the data portal. Where should this be indicated in the portal?

Should be a small amount of effort.   Also, I won't be able to directly map `lat_lon` to `latitude` and `longitude` so we should talk about what sort of interventions are needed for edge cases like that.

**Comment by ssarrafan** [comment]
Based on the recent comments I will move this one to February.  @turbomam and @wdduncan let me know if it should be in the backlog or assigned to someone else.

**Comment by mslarae13** [comment]
I am really late to this game! But saw the message in slack & checked this out.
Is this for the data harmonizer or read the docs / schema definitions?

**Comment by wdduncan** [comment]
See work discussed in this ticket https://github.com/microbiomedata/nmdc-schema/issues/252

**Comment by ssarrafan** [comment]
@wdduncan and @turbomam can we close this issue?  Seems like work is being tracked under the nmdc-schema#252?

**Comment by ssarrafan** [comment]
Removed @wdduncan per his note.

HI Set. Here is an update:
https://github.com/microbiomedata/nmdc-schema/issues/134
This is an ongoing issue that will need to be passed on to Mark or Sujay (not sure which).
https://github.com/microbiomedata/nmdc-runtime/issues/89
I updated the comment on this. I should be able to get the change sheet edit done before I leave.
https://github.com/microbiomedata/nmdc-schema/issues/195
I am working with Sujay on this. I should be able to close before the week’s end.
https://github.com/microbiomedata/nmdc-runtime/issues/46
This is an ongoing issue that will need to be passed on to Mark or Sujay (not sure which).
https://github.com/microbiomedata/nmdc-server/issues/555
This is a lot of conversation in this thread. But, it looks like Mark has taken this one over.

**Comment by turbomam** [comment]
But the `from_schema` may change after further imports/merges.

Yes, switch to `source`

**Comment by turbomam** [comment]
Solution in https://github.com/microbiomedata/nmdc-schema/pull/292

closing this issue in anticipation of a merge in May 2022
