### ISSUE TITLE
Show units for all quantitative values

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#556]
All quantitative values should show units, this is stored in the JSON as both the verbatim value (e.g. 0.15m) and as a normalized tuple (value=0.15, unit=m)

Related to #448

**Comment by ssarrafan** [comment]
Brandon, please add T-Shirt size and any questions. Team is trying to get an idea of the time/effort to do this.

**Comment by subdavis** [comment]
Similar to #552, where should metadata about what fields are in what units be stored? 

Can depth have values represented in different units?  Can one sample be 15 CM and another sample be 15M?

**Comment by ssarrafan** [comment]
@cmungall @wdduncan @dehays can anyone respond to Brandon's question about where to store the information for units?

**Comment by ssarrafan** [comment]
@mslarae13 who is working on this?  It's not currently assigned to anyone

**Comment by ssarrafan** [comment]
It looks like this is the backlog so I'll remove from the sprint. @mslarae13 if you plan to work on it next sprint let me know.

**Comment by mslarae13** [comment]
Relates to https://github.com/microbiomedata/sample-annotator/issues/111

That issue is identifying which slots are assumed units vs not...

This issue then captures how to share those units on the dataportal

**Comment by pkalita-lbl** [comment]
> how does the string or float in the submission schema go into the data portal? How do we get the units?

This is something that should be sorted out as part of https://github.com/microbiomedata/issues/issues/236

**Comment by mslarae13** [comment]
closing in favor of https://github.com/microbiomedata/issues/issues/236 & https://github.com/microbiomedata/nmdc-schema/issues/1257
