### ISSUE TITLE
Additions to individual sample page

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#557]
Individual sample page - consider adding: omics processing metadata and sample prep metadata, elevation, environmental package

Related to #448

**Comment by subdavis** [comment]
What kind of data is this and where is it documented?

* Elevation would be easy to add.  
* Environmental Package seems like finite terms, so also doable.

I can't find information on the other two.  I'm sure it's doable, but IDK how hard it is to get out of mongo or store.

**Comment by ssarrafan** [comment]
@wdduncan and @dehays can you answer Brandon's question above please?

**Comment by dehays** [comment]
It is unclear what Brandon is being asked to display and where he would obtain some of this information.

Displaying omics_processing information:  there is little metadata on omics_processing.  When the the sequencing project or MS run occurred, which instrument was used and which facility performed the instrument process.  There could be multiple omics processing per sample (same biosample used for metaP, metaB, metaG, metaT, etc.)

Sample prep - this is not currently included anywhere in the biosample schema so I think it is premature to ask Brandon to display it as he has not source for this information.

**Comment by ssarrafan** [comment]
Old issue, closing. 
Backlog cleanup 12-2023
