### ISSUE TITLE
Auto expand non-discriminatory sub levels 

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#558]
GOLD - if sublevels are non-discriminatory then auto-expand; e.g. if I am looking already at fracking samples, then I have to click 5 times to see

Related to #448

**Comment by ssarrafan** [comment]
Brandon, please add T-Shirt size and any questions. Team is trying to get an idea of the time/effort to do this.

**Comment by subdavis** [comment]
Sorry, I don't fully understand what's being asked here.    Could you provide a screenshot of the view where this change is pertinent?

I'm going to guess that this relates to the screenshot below?

![Screenshot from 2021-12-06 13-17-06](https://user-images.githubusercontent.com/4214172/144900127-6a3542c4-fe3e-4ea4-933e-56539019ae06.png)

"Plants" and "Roots" are "non-discriminatory" and so should be auto-expanded, is that right?

I know for a fact that this widget as-packaged cannot do this, so we'd need to fork it (which I'm already planning to do eventually). 

Probably somewhere in the neighborhood of 4 hours of work.

**Comment by cmungall** [comment]
you understand correctly @subdavis - an in fact in this case you can also lump in host-associated

I am not sure if the functionality belongs in the widget or in a pre-processing step. Possibly the widget if facets can be dynamically combined

**Comment by ssarrafan** [comment]
@subdavis do you need more information on this issue?

**Comment by subdavis** [comment]
Nope, this is clear now, thank you.

**Comment by ssarrafan** [comment]
Now that GSP is over is this a priority for March? @cmungall @subdavis @turbomam

**Comment by subdavis** [comment]
This was done a while ago.
