### ISSUE TITLE
Add ingest logic to handle transition to all data_objects with file type values in data_object_type

### ISSUE THREAD

**Issue by dehays** [microbiomedata/nmdc-server#560]
Current situation is that data_object JSON was provided WITHOUT data_object_type.  This attribute is needed for the portal download function.

Donny updated the existing data_object documents by applying a series of regex patterns on the URL attribute and setting a value for the data_object_type.  However, the value he set is not a value from the enum defined in the schema ( [schema/nmdc.yamnl#L446](https://github.com/microbiomedata/nmdc-schema/blob/main/src/schema/nmdc.yaml#L446) but an ID to documents within another collection in Mongo called: file_type_enum

The ingest script is aware of this and data_object.load is called with a list of objects derived from the file_type_enum Mongo collection.  That list is then used in data_object.load to set the file_type and file_type_description by referencing by the ID found in the data_object_type attribute. ( [nmdc_server/ingest/data_object.py#L35](https://github.com/microbiomedata/nmdc-server/blob/6b651ebc6599469f21dfc63eb67084761549d81c/nmdc_server/ingest/data_object.py#L35)

Situation we are moving to:  metadata providers (analysis workflows) provide data_object that includes data_object_type with the range specified by the NMDC schema.

Ingest would have have the value for file_type directly from the data_object_type (No creating a map from the file_type_enum Mongo collection and referencing it by an ID.). However, ingest would still need to create a map based on the schema file_type_enum to get the file_type_description for each data_object_type.

@subdavis I was originally thinking of adding logic to ingest (within data_object.load) to differentiate between an actual file type string value of data_object_type and one of those IDs of documents in Mongo's file_type_enum collection.  But I think the better path would be to change ingest to expect the file type string to be there in the data_object_type attribute and create a map from the file_type_enum in the schema in order to get the description values.  I'll add another GH issue to fix the data_objects that are in Mongo to replace the ID value with the actual file type string values.  That means the ingest script does need changing, but the change is to the behavior we ultimately want without additional logic to deal with inconsistent data_object JSON.

**Comment by dehays** [comment]
[#](https://github.com/microbiomedata/nmdc-runtime/issues/76)

**Comment by dehays** [comment]
Note that making this change will cause ingest of data_objects to be blocked by microbiomedata/nmdc-runtime#76

**Comment by wdduncan** [comment]
@subdavis FYI the last release of `nmdc-schema` on pypi includes a utility for fetching the file type enums. The command line util is `nmdc-data`:
```
nmdc-data -h              
Usage: nmdc-data [OPTIONS]

Options:
  -f, --fetch TEXT  Fetches the specified data file from the nmdc-schema library.
                    Only one argument is permitted.
                    
                    fetch arguments:
                    yaml            returns the nmdc.yaml file as a string
                    jsonschema      returns the NMDC jsonschema as json
                    dict            returns the NMDC jsonschema as a dict
                    schemadef       returns the LinkML SchemaDefintion created from the nmdc.yaml file
                    filetypeenums   returns informaton about the NMDC file type enums as json
                    goldsssom       returns the gold-to-mixs.sssom.tsv file contents

  -h, --help        Show this message and exit.
```
`nmdc-data -f filetypeenums` will return a json for the file type enums. E.g.:
```
{
    "name": "Pfam Annotation GFF",
    "description": "GFF3 format file with Pfam",
    "file_name_pattern": "[GOLD-AP]_pfam.gff"
  }
```

**Comment by subdavis** [comment]
Thanks Will.  That's unfortunately not a great API for me because I'm coming from python.

Instead, I'm going to pip install nmdc-schema and then get the enum dict as `nmdc.FileTypeEnum.__dict__` which will prevent me from having to go through subprocess.

If this CLI is just for me, feel free to drop support for it.

**Comment by wdduncan** [comment]
@subdavis you can access the file type enums programmatically like this:
```
from nmdc_schema.nmdc_data import get_nmdc_file_type_enums
```
This returns list of dicts with information about each NMDC file enums.
Each dict in the list has the key/values:
```
    {
        name: the name of the enum
        description: the description of the enum
        file_name_pattern: the pattern for the file type or None if not present
    }
```
Or you can return the json by calling:
```
from nmdc_schema.nmdc_data import get_nmdc_file_type_enums_json
```

**Comment by ssarrafan** [comment]
@subdavis are you still blocked on this?

**Comment by dehays** [comment]
@ssarrafan @subdavis  From today's conversation, I'd imagine Brandon could make the change but I'd suggest it not be merged until Shane and Bill have made updates to data object json (when there will be something that works with the updated Postgres ingest script).
