### ISSUE TITLE
Study page updates

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#563]
GH issue for adding changes wanted on the study pages.  

12/6/21: Would like the link to ESS-DIVE to be more prominent (logo?). Would like to have a mock-up to share with the ESS-DIVE team on January 24th.

**Comment by ssarrafan** [comment]
@faiza-a wondering if you have any questions about this issue?

**Comment by faiza-a** [comment]
@ssarrafan Could you please point me to the logo we are referring here. and what was the ask. i need to refresh my memory on this.

**Comment by ssarrafan** [comment]
> @ssarrafan Could you please point me to the logo we are referring here. and what was the ask. i need to refresh my memory on this.

Hi @faiza-a,
The logo is the one at the top of this site https://ess-dive.lbl.gov 
But I think we need some information from @emileyfadrosh on where she wants the logo. 
The meeting on Jan 24th was canceled so we have till mid-February.  Let's discuss with @emileyfadrosh when she's back next week.

**Comment by ssarrafan** [comment]
Moving to March. Let @faiza-a know via Slack that there are updates on the issue and to reach out if she needs more information.

**Comment by faiza-a** [comment]
Sorry for late response. i was on vacation.
Here are a few variation for placing logo. Let me know if any of these works. or if there are any other suggestions i can quickly create those.
_______
![option1](https://user-images.githubusercontent.com/61198087/156822931-07cbd652-db5b-49cf-aaae-80ebcef050d8.png)
_______
![option2](https://user-images.githubusercontent.com/61198087/156822937-aac05c72-db5f-41be-8347-6d08c563ce6d.png)
_______
![option3](https://user-images.githubusercontent.com/61198087/156822942-575f0394-0d30-47d7-aa9c-87a90a98a020.png)
_______
![option4](https://user-images.githubusercontent.com/61198087/156822943-a0e8151c-1e1f-4646-a5b2-2503fa0d490e.png)
_______
![option5](https://user-images.githubusercontent.com/61198087/156822947-fb6a4289-9bcb-4624-8294-359b3a0c2f7b.png)
_______
![option6](https://user-images.githubusercontent.com/61198087/156825032-de13e9cd-e8f6-4e47-a437-b26189212b51.png)
_______
![option7](https://user-images.githubusercontent.com/61198087/156825941-51d15602-3ca5-42a6-8acc-3fa55f3f6c73.png)
_______
Can also show ESS dive link upon hover over logo.

<img width="679" alt="Screen Shot 2022-03-04 at 2 12 31 PM" src="https://user-images.githubusercontent.com/61198087/156827055-e6ae6363-83b4-4d41-b56b-5c8dfd7046e0.png">

**Comment by pvangay** [comment]
Thanks @faiza-a. I like the last option the best - it's cleanest.

**Comment by jeffbaumes** [comment]
One other thought is to replace the link icon with the ESS DIVE icon (no words like the last example) which would keep everything else in line. @faiza-a can you show us how that would look?

**Comment by faiza-a** [comment]
@jeffbaumes 
<img width="618" alt="Screen Shot 2022-03-04 at 2 32 11 PM" src="https://user-images.githubusercontent.com/61198087/156829733-ed39150f-c5fb-4f26-a87e-84acc545a9c8.png">

**Comment by ssarrafan** [comment]
@pvangay and @emileyfadrosh can you confirm which design you prefer for @faiza-a?

**Comment by pvangay** [comment]
I think that last image looks great!

**Comment by emileyfadrosh** [comment]
I prefer the latest version with the logo as the link, and without the link icon. We had a discussion at the infrastructure sync yesterday about doing the same for other resources we link out too. It would be great to follow the same for GOLD, IMG, and NCBI. Attached are the links: 

GOLD: 
![image](https://user-images.githubusercontent.com/76500011/157977428-77b72f27-2ac9-464d-a1f4-7371012798ce.png)
IMG: 
![image](https://user-images.githubusercontent.com/76500011/157977552-8814662f-c848-43ff-8cdc-c42c4264c205.png)
NCBI:
![image](https://user-images.githubusercontent.com/76500011/157977650-af2f5cca-bf4c-457e-8e76-466b45b8d23d.png)

@pvangay is this OK?

**Comment by ssarrafan** [comment]
@faiza-a thanks for putting all the options together.  If it's ok I will re-assign this to @subdavis for implementation.

**Comment by ssarrafan** [comment]
@emileyfadrosh do you want to get feedback from the ESS DIVE team?  Or can we have @subdavis move forward with implementation of this?

**Comment by kfagnan** [comment]
This looks good and I think we should move forward with implementation.

**Comment by faiza-a** [comment]
Based on our meeting discussion
![with gold](https://user-images.githubusercontent.com/61198087/162289230-a1956bf5-dc19-4743-91dd-7c0b5882393e.png)

**Comment by ssarrafan** [comment]
> Based on our meeting discussion
> ![with gold](https://user-images.githubusercontent.com/61198087/162289230-a1956bf5-dc19-4743-91dd-7c0b5882393e.png)

This looks great @faiza-a.  Approved by the team at the infrastructure meeting today.  @subdavis this is ready for implementation.  Thank you

**Comment by subdavis** [comment]
Done, see https://data.dev.microbiomedata.org/details/study/gold:Gs0135149
