### ISSUE TITLE
client display of analysis files groups some files under incorrect analyses 

### ISSUE THREAD

**Issue by dehays** [microbiomedata/nmdc-server#570]
Shane noticed this and we investigated the following example (though it occurs in other places).

PMI SFA study gold:Gs0103573

For sample:  gold:Gb0115854

MAGs Analysis:

```
"has_input": ["nmdc:9a020e7ccd23f7a7e3df25dde65db69a", "nmdc:95604e1f98e2ac8aed6f799d150e2dd2", "nmdc:e0772b4db5f67ac1e4f810cc70919399"],
    "too_short_contig_num": 5862623,
    "part_of": ["nmdc:mga0rh71"],
    "binned_contig_num": 45095,
    "git_url": "https://github.com/microbiomedata/mg_annotation/releases/tag/0.1",
    "has_output": ["nmdc:589ce9d7a9fa089a9a87312086c3fe75", "nmdc:b81a9e557695141bae1024476147fb3e"],
    "was_informed_by": "gold:Gp0116336",
    "input_contig_num": 6443641,
    "id": "nmdc:8ad8c1621a57b0812a47395374cd84d7",
    "execution_resource": "NERSC-Cori",
    "name": "MAGs Analysis Activity for nmdc:mga0rh71",
```

Two outputs:

1)     nmdc:589ce9d7a9fa089a9a87312086c3fe75 - bin check
2).    nmdc:b81a9e557695141bae1024476147fb3e - bin.zip

But UI also displays a GOTTCHA2 Krona HTML file and a CENTRIFUGE read classification file - both of these should be outputs of the Read Based Analysis (which should have 9 output files but the UI only displays 5.)

```
"part_of": ["nmdc:mga0rh71"],
    "git_url": "https://github.com/microbiomedata/mg_annotation/releases/tag/0.1",
    "has_output": ["nmdc:02e6caad2d38e74efd774a46eab1a986", 
"nmdc:dc89ed4f6fe9cc33904739081a306cf5", 
"nmdc:529733e07713e2ee912302645ce8ac92",
 "nmdc:62f981ba321b25754cb7cbe004fe5282", 
"nmdc:8b4a9bfe8b7f72893718d3d1b0587b93", 
"nmdc:604af56e6bb222896d472bea841d23a8", 
"nmdc:339e38b819db9b35b54b3f1f92552da8", 
"nmdc:d77b5da6cf0e4a0779bc6dd209639cb8", 
"nmdc:2e50dcb1bef5a33524f2222f7c641e3e"],
    "was_informed_by": "gold:Gp0116336",
    "id": "nmdc:8ad8c1621a57b0812a47395374cd84d7",
    "execution_resource": "NERSC-Cori",
    "name": "ReadBased Analysis Activity for nmdc:mga0rh71",
    "started_at_time": "2021-09-06T23:06:13+00:00",
    "type": "nmdc:ReadBasedAnalysisActivity"
```

Read Based Analysis in UI is missing the two that are listed under MAGs analysis and then an additional two for which the data objects are missing both type and data_object_type.  The latter should be addressed in metadata by correcting the data object json docs.

I understand why the files with data objects with missing keys (type and data_object_type) are missing.  I do not understand how the other two are being grouped under MAGs analysis rather than Read-based analysis.

Big clue might be - this behavior changes with the selection of # rows to display.  The above (2 read-based files under MAGs analysis) happens when 5 display rows selected.  But choose to display ALL rows and all of the files for Read-based show up under MAGs and the Read-based analysis group heading is not displayed at all.

**Comment by subdavis** [comment]
Thanks for the detailed bug report, I'll take a look.

**Comment by dehays** [comment]
Looks good - thanks
