### ISSUE TITLE
Change DOI registry target

### ISSUE THREAD

**Issue by subdavis** [microbiomedata/nmdc-server#577]
Switch to `url = f"https://bioregistry.io/doi:{doi}"`

**Comment by subdavis** [comment]
No dice.  These are redirects, not a cache.  Here's what's happening.

```
Starting new HTTPS connection (1): bioregistry.io:443
https://bioregistry.io:443 "GET /doi:10.25585/1488096 HTTP/1.1" 302 270
Starting new HTTPS connection (1): doi.org:443
https://doi.org:443 "GET /10.25585/1488096 HTTP/1.1" 302 175
Starting new HTTPS connection (1): data.crosscite.org:443
```

`Bioregistry.io -> doi.org -> data.crosscite.org`

Because data.crosscite.org is "under heavy load" and not answering requests, I don't see another way to get this information.  We'll have to either find a true mirror of the DOI REST API from datacite (which I don't think exists) or wait for things to resolve on that service.

**Comment by dehays** [comment]
OK - yuck.  That just adds another redirect.
