### ISSUE TITLE
Investigate auto renewal options for NMDC certs for prod and dev

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#585]
Scheduled for March or later. Just adding to backlog for now.

Links to consider:

https://forums.rancher.com/t/ssl-certificate-renewal/18261

https://letsencrypt.org/getting-started/

**Comment by ssarrafan** [comment]
> I'm not sure if this is possible with Rancher, or if it is possible, that Kitware has the necessary access to do it. I have a hunch the NERSC rancher maintainers would need to change something. We will likely need to open a support ticket to figure out if it's possible.
> I think we can do some research and open a ticket as a first step. Let's keep it.

Thanks @subdavis.  Let me know if I can help with this.

**Comment by ssarrafan** [comment]
@subdavis do you have any updates on this issue?  I am trying to close out the sprint on time since I'll be off next week.  Thanks for your help.

**Comment by subdavis** [comment]
No update on this one, I haven't investigated yet.

**Comment by ssarrafan** [comment]
No problem. I will move this out of the sprint and add the backlog label.

**Comment by ssarrafan** [comment]
@shreddd this wasn't the highest priority but wanted to run it by you in case it's easy to do from your end

**Comment by shreddd** [comment]
We may not need auto-renewal anymore if we use cloudflare. Cloudflare (I think automatically manages the certs for you).

**Comment by ssarrafan** [comment]
@shreddd @eecavanna I'm going to close this issue

backlog cleanup 12-2023
