### ISSUE TITLE
Biosample counts mismatches on barchart vs. upset plot vs. download

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/nmdc-server#589]
- NOM counts are 996 on the barchart vs. 102 on the upset plot --> i think this is to be expected because there isn't a 1:1 relationship between biosample and NOM data product but I wanted to double check
- Metagenome counts on barchart vs. upset plot off by 1
- Total num biosamples are different on upset plot (623) vs. bulk download (654)

**Comment by dehays** [comment]
654 is the number of biosample docs in NMDC Mongo.  I think upset plot displayed sample count is off but will need to investigate to understand why.

**Comment by jeffbaumes** [comment]
> NOM counts are 996 on the barchart vs. 102 on the upset plot --> i think this is to be expected because there isn't a 1:1 relationship between biosample and NOM data product but I wanted to double check

Yes I believe this is the case.

> Metagenome counts on barchart vs. upset plot off by 1

Looks like there is a metagenome not associated with a biosample in one of the studies. When I download the QC stats files for the "Deep subsurface shale" project, I get this, so Gp0119870 seems to be the culprit:

![image](https://user-images.githubusercontent.com/81305/151387829-87d57e3b-d23a-4af6-89ed-a28ff3ea8132.png)

This might also explain the total biosamples off by one.

@dehays can you ensure that Gp0119870 is associated with a sample in mongo?

**Comment by dehays** [comment]
microbiomedata/nmdc-metadata#435

**Comment by dehays** [comment]
Thought I'd removed the moose rumen sequencing project - but if this off-by-one is still the case,  @dwinston or @mslarae13 could use the delete API endpoint to remove the omics_processing with ID gold:Gp0119870

**Comment by mslarae13** [comment]
@ssarrafan This should be an easy fix. Can you bring this into August sprint?

**Comment by ssarrafan** [comment]
@mslarae13 was this easy fix done?  can we close this?

**Comment by mslarae13** [comment]
We never got to discuss it. Hoping there's time at the next metadata meeting.

**Comment by mslarae13** [comment]
- [ ] Get sample IDs to remove for Sujay
- [ ] Then Sujay will remove the sample

**Comment by ssarrafan** [comment]
Moving all outstanding issues to backlog to focus team on squad work. @mslarae13 let me know if you plan to work on this this month.

**Comment by mslarae13** [comment]
23 data sets... 24 samples?
This seems like the opposite of  .. 
> > Metagenome counts on barchart vs. upset plot off by 1
> 
> Looks like there is a metagenome not associated with a biosample in one of the studies. When I download the QC stats files for the "Deep subsurface shale" project, I get this, so Gp0119870 seems to be the culprit:
> 
> ![image](https://user-images.githubusercontent.com/81305/151387829-87d57e3b-d23a-4af6-89ed-a28ff3ea8132.png)
> 
> This might also explain the total biosamples off by one.
> 
> @dehays can you ensure that Gp0119870 is associated with a sample in mongo?

![Screen Shot 2022-09-28 at 10 39 58 AM](https://user-images.githubusercontent.com/44581429/192851887-0cbbed2b-c439-4030-a17b-ddfefeda5130.png)

**Comment by sujaypatil96** [comment]
I just used the NMDC runtime API endpoint: https://api.dev.microbiomedata.org/docs#/queries/run_query_queries_run_post to query the `omics_processing_set` slot to look for gold:Gp0119870, but I couldn't find it in there?

So I ran:
```
{
  "find": "omics_processing_set",
  "filter": {"id": "gold:Gp0119870"}
}
```
and it returned nothing, meaning there isn't such a record on `omics_processing_set`.

I also retrieved all the Gp's on `omics_processing_set` and looked through all of the returned records, and still couldn't find gold:Gp0119870.

**Comment by dehays** [comment]
@mslarae13 I'm not sure if you meant to tag me in your comment (maybe you meant Donny).

But I do not believe you want Gp0119870  ( https://gold.jgi.doe.gov/project?id=Gp0119870 ).  Per my comment from January - this is the moose rumen sequencing project.  Initially the biosample had been removed but the sequencing project remained. From Sujay's query 40 minutes ago - it appears the sequencing project is no longer in Mongo either - which is what you want.

**Comment by jeffbaumes** [comment]
@dwinston removed the related biosample gold:Gb0150262 from mongo just now. Up until now just the metaG processing objects had been removed but the biosample had remained. This still needs to be ingested into the portal database.

**Comment by ssarrafan** [comment]
I think this means an ingest to production, correct @jeffbaumes? I think that's Matt or Mike. I don't know if an ingest will be done with the schema update.

**Comment by jeffbaumes** [comment]
It is not gone yet on dev or production, but @naglepuff can report here when that sample removal gets to each stage. Dev should be coming soon.

**Comment by naglepuff** [comment]
The sample is no longer in dev.

**Comment by ssarrafan** [comment]
Closing this issue. @aclum is this related to other issues you have open?  
Backlog cleanup 12-2023

**Comment by aclum** [comment]
There are still data object records for this project in mongo, it will be cleaned up as part of the re-iding squad which is addressing referential integrity issues so I will add this to that project board.

**Comment by aclum** [comment]
{'description':{$regex:'Gp0119870'}}

**Comment by aclum** [comment]
same story with workflow execution activites
{'was_informed_by':{$regex:'Gp0119870'}} returns a record on mags_activity_set

**Comment by aclum** [comment]
Data for Gp0119870 was removed from mags_activity_set and data_object_set during re-iding.
