### ISSUE TITLE
Add "fit to screen" button to map

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/nmdc-server#604]
(logging this here so I don't forget about it)

when zoomed into a set of samples, depending on the granularity, the user sometimes has to click 5-7 times to be able to zoom back out to see the full map again (cumbersome when exploring using the map). would be helpful to have a button that brings the user back to the full map view, similar to a "fit to screen" button.

**Comment by subdavis** [comment]
Let's start by adding a "Reset" button next to the existing "Search this region" that is only available when there are active query terms present for the map search.

So when there are lat/long conditions in the search filter, show a new "Reset" button that clears the search criteria.  This action will automatically trigger updated search, and automatically reset the zoom to the full map.

![Screenshot 2022-06-23 133025](https://user-images.githubusercontent.com/4214172/175359453-e24c34cc-c468-47c0-a2c4-847c439e2c67.png)

**Comment by aclum** [comment]
Closing for now, workaround is to clear the lat and log faceted search opitons.
