### ISSUE TITLE
Update URL in the Contributor Role description 

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/nmdc-server#616]
URL in the description for "Roles" should be https://info.orcid.org/credit-for-research-contribution instead of https://info.orcid.org/credit-for-research-contribution/&sa=D&source=editors&ust=1644213796018471&usg=AOvVaw0gAzMVLEoWTNkuaN_5O3gR. It currently errors out to a page not found.
![image](https://user-images.githubusercontent.com/7374085/156068301-443f63e2-0274-411f-8c2c-b9035f1c5681.png)

FYI: @dehays

**Comment by subdavis** [comment]
Just FYI, I pulled these descriptions from https://docs.google.com/spreadsheets/d/1T31B5gbRgS6vuK_lIg0ZLpIyafByWhlvE2hfcCy-c4k/edit#gid=0

If descriptions need to change, could they be updated on that sheet so we have a record when they eventually move into a more permanent location?
