### ISSUE TITLE
Fix metaT and metaP annotation search

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#618]
Currently this search returns no matches on metaT in the bar chart:

![image](https://user-images.githubusercontent.com/81305/156656208-73df195b-edb3-4594-a606-caa063a8b978.png)

We need to discover why metaT are not being populated and fix it so that this search returns 33 matches for metaT in the bar chart.

Some thoughts on the problem from @dehays and others:
* There is a single mongo collection storing all annotations which should contain metaT, metaP, metaG annotations. Understand that table and how to distinguish between the annotation types.
* Annotations should link back to omics_processing ids, which should have a definitive type (metaG, metaT, etc.).
* metaT annotations are run separately from metaG, and there should be data parsed and populated in mongo.
* nmdc_server does not seem to have a separate join path/table for metaT. Investigate why that is and how to add it.

**Comment by jeffbaumes** [comment]
@ssarrafan This is the metaP issue we were discussing today.

**Comment by ssarrafan** [comment]
> @ssarrafan This is the metaP issue we were discussing today.

Thanks @jeffbaumes. I've added this to the March sprint.

**Comment by ssarrafan** [comment]
@mcovalt any update on this issue?  Can this be closed?  Does it need to continue to April?

**Comment by jeffbaumes** [comment]
This is being worked on but will not be complete this month so should continue to April.

**Comment by ssarrafan** [comment]
@mcovalt do you have any updates on this issue?  I am trying to close out the sprint on time since I'll be off next week.  Thanks for your help.

**Comment by mcovalt** [comment]
I believe this is blocked while waiting for an upstream fix. Some GFF files need to be parsed and included in the metaT JSON before this ticket can be completed.

**Comment by ssarrafan** [comment]
@scanon @hubin-keio is this something that will be worked on in May or should this be labeled backlog?

**Comment by ssarrafan** [comment]
Removing from the sprint. Adding backlog label.
@dehays @emileyfadrosh
