### ISSUE TITLE
Investigate splitting out the submission portal into its own deployment

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#620]

**Comment by aclum** [comment]
@mslarae13 @jeffbaumes  is this still needed? cc @shreddd

**Comment by mslarae13** [comment]
...What does "into its own deployment" mean?
@jeffbaumes  ?

**Comment by jeffbaumes** [comment]
It means the submission portal deployment would not be tied to the data portal. It would involve totally decoupling the frontend, backend, and database which would be considerable effort. I don't think we've seriously considered this since it was suggested two years ago. I feel it can be closed.
