### ISSUE TITLE
Create a ReadtheDocs for the development and maintenance of the data portal

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#621]
Documentation reframing is part of the April release.  
It can be written in md or rst. It should include information about tools used (and versions), databases included, and how everything is maintained.  
Please contact @kwdavenport  if you or they need more information.

**Comment by ssarrafan** [comment]
Here's a link to the current documentation:
https://nmdc-docs-sphinx.readthedocs.io/en/latest/index.html

**Comment by jeffbaumes** [comment]
Note that the doc page we are looking to fill is here:

https://github.com/yxu-lanl/nmdc-docs/blob/main/docs/guides/data_portal.md

This page should contain architecture details for technical folks, not user-level docs.

**Comment by ssarrafan** [comment]
Per @kwdavenport you should create the readthedocs in the NMDC-Server repo.  
This was discussed at the infrastructure sync meeting today and the goal is to have the documentation done for the April release, by mid-April latest so Karen and team can pull it in and format by April 22nd.

**Comment by subdavis** [comment]
@kwdavenport I've made a first pass at this here: https://github.com/microbiomedata/nmdc-server/blob/main/docs/data_portal.md

Please let me know if that provide what you need and if you'd like more detail on any topics.  Thanks
