### ISSUE TITLE
Document desired API to use DH as a library

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#623]
# DataHarmonizer Library

It would be great to be able to consume DH from the NPM package repository and hook it up to an element in the dom.

## Requirements

* All uses of `window` and global variables should be removed.
* Migrate to ES6 modles for library and template type files, which are natively supported by 92.8% of browsers https://caniuse.com/es6-module.  IMO, this is by far the easiest way to turn this code into a consumable library without introducing complexity from a build system like Webpack or Grunt, which should definitely be avoided if possible.
* The default behavior should _not_ involve any of the toolbar or other UI.  The below code example should just produce an API-interactive HandsOnTable instance.  If needed, the toolbar can be attached to another div in a similar fashion.

## Example Usage

``` typescript
// index.js (consumer code)

import DataHarmonizer from 'data-harmonizer';
import mySchema from './project/path/data.js';
import myExportFormats from './project/path/export.js';

const myDiv = document.getElementById('data-harmonizer-root');
// get the configuration object for handsOnTable
const myHotConfig = DataHarmonizer.getHotConfig(mySchema);
// tamper with hotConfig, for example, to add our own cell editors.
myHotConfig.columns['columnName'].editor = 'someCustomEditor';
// initialize dataHarmonizer at myDiv
const harmonizer = DataHarmonizer.init({
  root: myDiv,
  schema: mySchema,
  exportFormats: myExportFormats,
  hotConfig: myHotConfig,
});
```

``` js
// data.js

// New style: ES module syntax
export default { /** .... */ };

// Old style, change to avoid use of global variables
// var DATA = {}
```

## API Specification

In-exhaustive interface for the harmonizer library.  I've described it with typescript syntax, but I don't expect any of this o be typescript.

``` typescript
interface DataHarmonizerApi {
  hot: HandsOnTable; // direct access to the handsOnTable instance;

  // Run validation and return errors
  validate(): Promise<Record<number, Record<number, string>>>;

  // Select column
  jumpToCol(columnName: string): void;

  // load data from 2d array
  loadData(data: any[][]): Promise<void>;

  // load data from TSV file
  openFile(file: File): Promise<void>;
  
  // switch to a different template
  useTemplate(templateData: Object): void;

  // toggle the visibility of a particular section
  toggleVisibility(sectionName: string | 'all' | 'required' | 'recommended'): void;
}
```

**Comment by subdavis** [comment]
Damion has pointed out that `<script type="module">` cannot be used with `file://` protocol due to CORS.  I thought you could avoid CORS issues with CSP, but I guess you can't.

Modules would be nice, but if we can't use them and have to rely on globals, it doesn't change the general idea behind the desired API.  Instead of `import` you'll just have `window.DataHarmonizer` and `window.DATA` like it is now...

This an issue if you need more than 1 schema loaded at the same time.  There may be a solution where schemas are loaded after DataHarmonizer and can register themselves like this, but I'm not sure what the best idea is.

``` js
// data.js

const data = { /* ... */ };

// Old
var DATA = ...

// New
window.DataHarmonizer.registerSchema('schema-name', data);
```

**Comment by ddooley** [comment]
Yes that looks like a good compromise. To fit existing general purpose functionality I'd keep it that a "var" was declared so that other schemas can be reloaded, ok? And I guess a longer data-harmonizer related name to reduce possible collision. Maybe

var dhSchema = { /* ... */ };

**Comment by ddooley** [comment]
What would you recommend for a file folder structure? As mentioned on slack, At moment I have this on my linkml-datastructure branch.  (Ignore main.js).  There is now a toolbar.js and there can be a toolbar.html to bring that in along with any dialogues.
![image](https://user-images.githubusercontent.com/4000582/160163282-7b4c0b3a-e7a5-4dd8-a12e-48b3c675cac1.png)

**Comment by subdavis** [comment]
I don't think it matters too much.  You'll probably want to figure out what files you intend to publish as a package, separate those into their own directory, and include a `package.json` file.

It looks like that `data-harmonizer` folder already does that, so this looks good to me.

**Comment by subdavis** [comment]
I think this is done.
