### ISSUE TITLE
Submission Portal - Ability to save/load from a previous session using ORCID

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#632]
Users should be able to see and load in-progress and submitted submissions. I believe it makes sense that submitted in-review submissions should not be able to be updated.

**Comment by ssarrafan** [comment]
See states and staging examples drafted by @mslarae13 at https://docs.google.com/document/d/1etdlEgHCkyPCx5LSgf7IJ44tnd3oJ_JttI_C45wQoNg/edit?usp=sharing
