### ISSUE TITLE
Admin interface for viewing submissions

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#633]

**Comment by ssarrafan** [comment]
See states and staging examples drafted by @mslarae13 at https://docs.google.com/document/d/1etdlEgHCkyPCx5LSgf7IJ44tnd3oJ_JttI_C45wQoNg/edit?usp=sharing

**Comment by subdavis** [comment]
The April version of this feature is done.  Administrators can see every submission in the system.    There's more work to be done where we add new review states and begin to integrate with other systems.  I believe this is targeted for June.

**Comment by subdavis** [comment]
Continue work in may.
