### ISSUE TITLE
Sort samples by abundance of KEGG matches

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#635]

**Comment by ssarrafan** [comment]
Removing from the April sprint and milestone.  This issue will require updated requirements and visuals from the NMDC team.  Adding backlog label.  
@pvangay @emileyfadrosh

**Comment by ssarrafan** [comment]
@aclum I'm going to close this one.  It's more than a year old. If sorting still required re-open or open a new issue with more specific requirements.
