### ISSUE TITLE
Typos on the NMDC Data Portal - Project landing pages

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-server#648]
The SPRUCE study landing page has a typo in the study description “Focus Area of ORNL”s Climate” … ORNL”s should be ORNL’s 

Also,  do we have the ability to subscript the 2 in CO2 ?

**Comment by mslarae13** [comment]
Comment from @dwinston  via slack
"
I see that there is (correctly) a single-quote in the nmdc-runtime metadata store (i.e. mongodb): https://api.dev.microbiomedata.org/studies?filter=description.search%3ASPRUCE . I also see that the study name in the metadata store is "Peatland microbial communities from Minnesota, USA, analyzing carbon cycling and trace gas fluxes", whereas the header line on <https://data.microbiomedata.org/details/study/gold:Gs0110138> begins "Fungal, bacterial, and archaeal communities mediating...".
So, it seems that code from the nmdc-server repo ([github.com/microbiomedata/nmdc-server/](http://github.com/microbiomedata/nmdc-server/)) is doing some custom overriding/transformation of values that is incorrect in this case (for the study  description).
To subscript the 2 in CO2, that would be a mater of the nmdc-server repo in how it renders text. It could be revised to detect chemical formulae, or perhaps we could include tagging in the text, e.g. "...<span class='chemical-formula'>CO2</span>..", that the portal renderer could interpret consistently. Either way, the nmdc-server code would need to render it properly.
"

**Comment by subdavis** [comment]
> single quote vs double quote.

Probably a string escaping issue somewhere.  That's probably something I can fix.

> name vs title

The portal uses the `title` field if it's available, which is what @dwinston said I should do in [June 2021](https://nmdc-group.slack.com/archives/C01034ES34G/p1625598985155700).  If the title is wrong, it should probably be corrected in mongo?

From Donny: "5 of the 8 documents in the study_set collection have title fields in addition to name fields. The name field is being displayed for all 8 studies currently. If a study has a title field set, that should be displayed instead of the value of the name field."

> subscript CO2

Can we simply use unicode subscript?  Anything working with strings should support it.  CO₂

**Comment by dwinston** [comment]
> The portal uses the `title` instead of the `name` field if it's available

Ah, right.

**Comment by mslarae13** [comment]
@dwinston & @mcovalt 
Checking in on this. Looks like it was fixed. https://data.microbiomedata.org/details/study/gold:Gs0110138

**Comment by dwinston** [comment]
It was unfixed in the nmdc-runtime store (mongodb). I submitted a changesheet to fix, i.e.

|id|action|attribute|update|
|--|--|--|--|
|gold:Gs0110138|update|description|This study is part of...|

to [/metadata/changesheets:submit](https://api.dev.microbiomedata.org/docs#/metadata/submit_changesheet_metadata_changesheets_submit_post).

Looks like it took: https://api.dev.microbiomedata.org/studies/gold:Gs0110138

Now the nmdc-server team can ingest.

**Comment by pvangay** [comment]
FYI via email from @jeffbaumes, we should hold off on ingests until @mcovalt is back from vacation. Hopefully we'll see the changes after that.

**Comment by ssarrafan** [comment]
> @ssarrafan I'd like to check in on this at the infrastructure sync today (10/20)

Sure I'll add this to the agenda.

**Comment by mslarae13** [comment]
Matt started an ingest. @mcovalt can you let me know when dev is good / you're ready for me to check SPRUCE

**Comment by mcovalt** [comment]
Ingest is still ongoing. I'm debugging why the ingest has still been stalled. I'll update next week on the current status.

**Comment by mslarae13** [comment]
Reassigning to @naglepuff

**Comment by naglepuff** [comment]
This is fixed in dev. https://data.dev.microbiomedata.org/details/study/gold:Gs0110138

**Comment by mslarae13** [comment]
Yup, once it's been updated on prod we can close this issue

**Comment by ssarrafan** [comment]
I'm removing this issue from the sprint since the work is done pending push to prod.

**Comment by aclum** [comment]
We'll check on this once data portal prod is updated. Added this to GSP board and the current sprint.

**Comment by aclum** [comment]
Expect data portal prod ingest to happen tomorrow.

**Comment by aclum** [comment]
Fixed by prod data portal ingest this AM.

**Comment by mslarae13** [comment]
This is still wrong on the DP 
@naglepuff
