### ISSUE TITLE
Ingest EMP500 data to prod for release

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#650]
David and Sujay are working on ingest of the EMP500 data to dev. Once this is ok and passes tests in dev we'll need to get it posted to prod next week, by 4/28.

**Comment by subdavis** [comment]
In progress, I'll close this when it's done.

**Comment by ssarrafan** [comment]
Believe this is done so closing this issue. @subdavis feel free to reopen.
