### ISSUE TITLE
Make new mini issues from #555, "Indicate MIxS terms"

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-server#653]
Slots that are imported from MIxS into the NMDC schema are now tagged with `source` = http://w3id.org/mixs/terms

That's from the `from_schema` annotation that automatically appears when the MIxS terms file is opened with SchemaView. It could change in the future if MIxS changes the filename or the web path. Note that the version of the source schema is not included at this point.

The LinkML YAML file with the `source` = http://w3id.org/mixs/terms annotations has not been merged into the main branch of the NMDC schema yet. It's still in a pull request: https://github.com/microbiomedata/nmdc-schema/pull/292

I'm closing issue #555, "Indicate MIxS terms" because theres code that satisfies this issue in a PR.

However, several related issues were brought up in #555's discussion. I'll make new issues and link them here.

CC @ssarrafan

**Comment by aclum** [comment]
@turbomam I'm closing this since it appears to be a note to create issues from two years ago, please reopen and add information/link issues if this is still an issue.
