### ISSUE TITLE
Support basic "find and replace" feature

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#668]
Search/Replace globally and cell by cell (iterate through and find/replace) would be ideal, advanced feature (nice to have): search/replace within selection.

Also helpful for search/replace of null values. Brandon: may be more complex to implement.

Potential to use google sheets API (to make use of their features)? Brandon to look into this from a technical feasibility? Some drawbacks include requiring google accounts.

**Comment by ssarrafan** [comment]
@mcovalt Today is mid-sprint so I’m checking in to see how you’re doing with your assigned GitHub issues.  Please update this issue and let me know if you’re still actively working on it and it’s on track for finishing by the end of June. If you’re not working on it due to other priorities let me know if you plan to work on it in July or if it should be moved to the backlog for reprioritization.

**Comment by mcovalt** [comment]
@ssarrafan This seems to be on-track for being finished by the end of June. My research has led me to consider using the [Handsontable search plugin](https://handsontable.com/docs/8.1.0/demo-searching.html). If everything goes without a hitch, I might have a rough demo for the meeting today (6/16).

**Comment by ssarrafan** [comment]
@mcovalt can this issue be closed? Or should it continue to July?

**Comment by mcovalt** [comment]
We should continue it to July.

The feature is done, but we've got nowhere to put it on the page. We need to make the sidebar toggle-able first, which is something @faiza-a and I are currently working on.

**Comment by ssarrafan** [comment]
Based on the infrastructure sync meeting yesterday this was still top priority so I will move to the August sprint. @mcovalt @jeffbaumes

**Comment by ssarrafan** [comment]
@jeffbaumes @mcovalt what's the status of this issue?

**Comment by mcovalt** [comment]
This is still in-progress.
