### ISSUE TITLE
Display more navigable errors

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#669]
After move from iframes: brandon will explore this from a UI perspective (display more navigable errors on the DH interface) -- may also include enabling users to download this list of errors too (need to understand need for this more).

**Comment by ssarrafan** [comment]
@jeffbaumes let me know if this one is being worked on in May so I can add it to the sprint board. Thanks for creating all these GH issues.

**Comment by mslarae13** [comment]
Would highlight in demo
