### ISSUE TITLE
GSP feedback: Data Portal: Collection date search facet

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#674]
Users reported it being very tedious to have to click through to get to the appropriate date using the search facet (e.g. a date in 1990 would require clicking the back button far too many times to get to the correct year). Would like to able to type in a date directly.  

User need: Medium
Feasibility: Unknown

**Comment by pvangay** [comment]
This was echoed by ESS attendees as well.

**Comment by pvangay** [comment]
Jeff says will likely go with a stricter format approach YYYY-MM-DD

**Comment by ssarrafan** [comment]
@pvangay @mcovalt any update on this?  I'll move to September but if it's not being actively worked on in the next 2 weeks let me know.

**Comment by pvangay** [comment]
@ssarrafan this has been addressed! i saw it live for the first time in yesterday's workshop - worked beautifully!
