### ISSUE TITLE
GSP Feedback: Data Portal: IMG Link

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#678]
Users had difficulty finding the IMG links near the list of sample names. 

User need:  Low
Next steps: Consider adding IMG, NCBI, GOLD logos near the sample names to link out to instead of the text based links. Work with @faiza-a  to see whether this could be mocked up.

**Comment by pvangay** [comment]
Also reported by ESS attendees.

**Comment by aclum** [comment]
Closing as this has not come up recently and was low priority in previous user research feedback.
