### ISSUE TITLE
GSP Feedback: Submission Portal: Resize Column WidUI

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#684]
Users requested the ability to more easily resize column widths to show values.

User need - unknown
Feasibility - unkown

Users requested being able to resize by hovering over anywhere near the column borders (and not just near the headers), but this would deviate from how other spreadsheet UIs support resizing.

**Comment by pvangay** [comment]
This feature is supported and functions like all spreadsheet UIs.
