### ISSUE TITLE
GSP Feedback: Data Portal: Add a Fit to Screen feature for the map viz

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/nmdc-server#686]
Users reported that after clicking into a set of samples, they often have to click zoom out many times in order to reorient where they are in the map.

User need: Low

Suggestion: Have an option to click "Fit to screen" to zoom back out?
Unclear feasibility.

**Comment by aclum** [comment]
Closing as won't fix, this was low and hasn't come up in the last year.
