### ISSUE TITLE
Add raw field name back to column description

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#719]

**Comment by ssarrafan** [comment]
Let me know if you'd like me to add this to the August project board @jeffbaumes.  I'm removing it from the June milestone.

**Comment by aclum** [comment]
@mslarae13 is this a submission portal issue?

**Comment by mslarae13** [comment]
Ummm IDK? I'm not sure what this is or means?
@jeffbaumes

**Comment by aclum** [comment]
closing as it is unclear what the original request was.
