### ISSUE TITLE
Set and test session cookie attributes

### ISSUE THREAD

**Issue by mcovalt** [microbiomedata/nmdc-server#723]
Currently, after the authorization flow with ORCiD is complete, our backend provides the frontend with a session cookie containing the JWT. This cookie is foundational to the rest of our authorization workflow, so it must be secure.

Ensure the following attributes are set on that session cookie:
- HttpOnly
- SameSite: Strict
- Secure

Provide a test on the backend that proves cookie responses set these attributes.

*Note: the above attributes generally prevent XSS and CSRF on modern web browsers. Older browsers that don't work correctly with the above attributes may still pose risks.*

**Comment by naglepuff** [comment]
See #1257 
We no longer use the session cookie for authentication. Closing this issue
