### ISSUE TITLE
Sample details page fixes

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#740]
- [x] Show geo location (city/state)
- [x] Show human-readable text for ENVO terms
- [ ] Show both depth values (min/max) when present

**Comment by jeffbaumes** [comment]
ENVO and geo location would be great to have in the near term (by July 13)

**Comment by mcovalt** [comment]
Our ingest only accepts depth as a single float right now. The PostgreSQL schema and ingest will need to be updated to include the depth range.

**Comment by ssarrafan** [comment]
@mcovalt @jeffbaumes are you planning to work on this in August?

**Comment by jeffbaumes** [comment]
@ssarrafan Marking this one as closed, and made the new issue #756 to more clearly track the remaining part. We did not yet get indication if this one is high priority for August.
