### ISSUE TITLE
Investigating duplicates identified by the IMG team

### ISSUE THREAD

**Issue by emileyfadrosh** [microbiomedata/nmdc-server#741]
Including two separate cases where duplicates (or triplicates) were identified in the NMDC for metagenomes part of studies: 
Gs0128850
Gs0110138

The metagenomes with duplicates are highlighted in yellow in each of the spreadsheets. @scanon had indicated that there are no duplicates in mongo. Thanks @jeffbaumes @mcovalt for investigating. 

FYI @ssarrafan @turbomam 

[Gs0128850.xlsx](https://github.com/microbiomedata/nmdc-server/files/9067118/Gs0128850.xlsx)
[Gs0110138.xlsx](https://github.com/microbiomedata/nmdc-server/files/9067120/Gs0110138.xlsx)

**Comment by aclum** [comment]
I am unable to reproduce this and annotation and binning will be redone as part of re-iding in May.
