### ISSUE TITLE
Show both depth values (min/max) when present

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#756]
Split out from #740.

**Comment by turbomam** [comment]
We will be migrating away from use of a depth 2 slot, towards a depth slot that has subslots for discrete measurements as well as ranges.

The modeling is complete but changes have not been made to MongoDB yet.

**Comment by jeffbaumes** [comment]
Thanks for that info @turbomam. Can you add a "blocked on <issue link>" comment here if there's an issue for what you just mentioned?

**Comment by mslarae13** [comment]
We should revisit this some time soon
@turbomam 
@jeffbaumes 
@naglepuff 
@pkalita-lbl

**Comment by aclum** [comment]
@jeffbaumes @naglepuff in mongo prod  `biosample_set` `id` `nmdc:bsm-11-2d3eam48` is an example record where a depth range is specified. 

The slot depth has a value of [QuantityValue](https://microbiomedata.github.io/nmdc-schema/QuantityValue/) relevant slots for data portal ingest are  `has_minimum_numeric_value`, `has_maximum_numeric_value`, `has_numeric_value`

 "depth": {
    "has_minimum_numeric_value": 0,
    "has_maximum_numeric_value": 0.1
  }

cc @mslarae13

**Comment by aclum** [comment]
Time permitting adding this ticket to this sprint. NEON will have these min and max values.

**Comment by ssarrafan** [comment]
Per the meeting today Mongo should be updated soon so that this can be resolved. I'm moving this to the next sprint since schema was just released today.  @naglepuff @aclum

**Comment by aclum** [comment]
There is already data in mongo with the values. This issue is to get the range displayed in the data portal

**Comment by ssarrafan** [comment]
This wasn't done so will be addressed after ESA. Adding backlog label. @naglepuff @aclum

**Comment by mslarae13** [comment]
Should / could this be prioritized?
I noticed the NEON samples don't show depth at all.

**Comment by aclum** [comment]
@mslarae13  Right, no depth is shown when depth is a range in mongo. As much as I would like to get this addressed there are bigger issues I'd like addressed like being able to pass a url with a search parameter. https://github.com/microbiomedata/nmdc-server/issues/1034. Leah and I are starting a around of user research now so part of that will be going through outstanding tickets.

**Comment by eecavanna** [comment]
I'm reading up on this issue now.

Here are some references for whoever ends up implementing this:
- Documentation of the `depth` [slot](https://microbiomedata.github.io/nmdc-schema/depth/)
- The slot's usage on the `Biosample` [class](https://microbiomedata.github.io/nmdc-schema/Biosample/#linkml-source) (search the web page for "`slot_uri: MIXS:0000018`", for example):
  > ```yaml
  > depth:
  >     name: depth
  >     annotations:
  >       expected_value:
  >         tag: expected_value
  >         value: measurement value
  >     description: The vertical distance below local surface, e.g. for sediment or soil
  >       samples depth is measured from sediment or soil surface, respectively. Depth
  >       can be reported as an interval for subsurface samples.
  >     title: depth
  >     examples:
  >     - value: 10 meter
  >     from_schema: https://w3id.org/nmdc/nmdc
  >     aliases:
  >     - depth
  >     rank: 1000
  >     is_a: environment field
  >     slot_uri: MIXS:0000018
  >     multivalued: false
  >     alias: depth
  >     owner: Biosample
  >     domain_of:
  >     - Biosample
  >     range: QuantityValue
  > ```
- A mongosh query you can use to find a biosample that has a `depth` property:
  ```js
  db.getCollection("biosample_set").findOne({"depth": {$exists: true}})
  ```
- The `id` (and `_id`) of such a biosample:
  ```js
  {
    "_id" : ObjectId("649b003843aa17f5748437d5"),
    "id" : "gold:Gb0115231",
  ```

**Comment by eecavanna** [comment]
I got an `nmdc-server` development environment set up on my computer, and I got a copy of the production Postgres database loaded into it (from one of the backups). 🙌 

![image](https://github.com/microbiomedata/nmdc-server/assets/134325062/6c55e364-f9cb-40bb-b631-ba5f6d27f8a8)

Tomorrow, I'll work on getting the min/max values to show up (when present).

**Comment by eecavanna** [comment]
I was able to get a range showing. Tomorrow, I'll clean up and the code and run it by someone more familiar with both the Postgres data and Vue.js to see whether there's anything I've overlooked.

<img width="698" alt="image" src="https://github.com/microbiomedata/nmdc-server/assets/134325062/723c3fad-4640-4765-96f5-091e3f11bb0f">

@aclum, is the way the range is shown on the left, what you had in mind?

**Comment by eecavanna** [comment]
I described the format `minimum hyphen maximum space unit` to @aclum **verbally** and she said it sounded good to her, so I'll move forward with that. I'll tag her in the PR I open, and include a screenshot, for her final approval.

In addition, @aclum wants **single values** to be followed by the unit also, when the unit is available (if available, it would be in `annotations.depth.has_unit`). Currently, the unit is not always available, but the team plans to make it required in the future (possibly back-filling missing ones).

**Comment by eecavanna** [comment]
I opened a PR in which I implemented this functionality. Here's a link to the PR:  https://github.com/microbiomedata/nmdc-server/pull/1133

**Comment by naglepuff** [comment]
> I opened a PR in which I implemented this functionality. Here's a link to the PR: #1133

I'll be able to take a look at this PR next week.
