### ISSUE TITLE
Make help text for Submission Portal column headers easier to find

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/nmdc-server#759]
ESS attendees reported still not knowing how to access the help text for each column header (currently requires double clicking but this is not obvious) in the Submission Portal.

@faiza-a previously showed mockups showing the help text display. @jeffbaumes really sorry if there's already an issue for this but I couldn't immediately find it. Please help. I believe the decision was to implement what Faiza mocked up?

**Comment by ssarrafan** [comment]
@jeffbaumes @mcovalt are you actively working on this one?  I'll move to September but let me know if you're not planning to work on this in the next 2 weeks.

**Comment by mcovalt** [comment]
This is still in-progress. It's currently the feature I'm working on now.
