### ISSUE TITLE
Tour of features of the submission portal for new users

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/nmdc-server#760]
**Is your feature request related to a problem? Please describe.**
New users of the Submission Portal often are not aware of the main features. Showing popups/overlays that call out the main features would orient users and allow them to learn the interface more quickly.

**Describe the solution you'd like**
Popups that point to different parts of the spreadsheet interface of the submission portal. For example, this may include popups for: the jump to feature, the help text for each term, the visibility feature, the legend, upload, download, save/submit, validate

**Describe alternatives you've considered**
https://github.com/microbiomedata/nmdc-server/issues/759

**Acceptance Criteria**
Who will use this feature/enhancement? 
New users of the submission portal

When will they use it? 
The first time they create a submission

How will they use it? 
Reaching each popup while exploring the features

How will they test it to make sure it's working? 
They'll need to close out the popup to try the feature and see if the feature functions as the popup describes.

Is the request achievable? During one sprint? 
Unlikely. Needs help from @mslarae13 to create the content first, then @jeffbaumes and team to implement.

What is your definition of done for this request? 
When the popups show up with content that reflects the feature function.

FYI @ssarrafan

**Comment by ssarrafan** [comment]
Based on discussion at Infrastructure sync meeting, adding to the August sprint

Also so excited that you're trying the template for new features 👍

**Comment by pvangay** [comment]
@ssarrafan oh this one wouldn't be worked on for august. sorry if there was confusion.

**Comment by ssarrafan** [comment]
> @ssarrafan oh this one wouldn't be worked on for august. sorry if there was confusion.

No problem. I'll remove from sprint and add the backlog label

**Comment by ssarrafan** [comment]
Closing this.  @mslarae13 is taking care of documentation for submission portal users.
