### ISSUE TITLE
coordinate migration from nmdc-schema v3.2.0 to v6.0.x

### ISSUE THREAD

**Issue by dwinston** [microbiomedata/nmdc-server#767]
nmdc-runtime (and thus JSON validation for metadata ingest) is currently [pinned to v3.2.0](https://github.com/microbiomedata/nmdc-runtime/blob/5dbf733778cc38cfb1878e191d437bb9894486b7/requirements/main.txt#L1182) ([released March 4](https://pypi.org/project/nmdc-schema/#history)).

I don't want to migrate stuff to v6.0.x (current major version as of August 8) until the portal can handle it. Here are relevant diffs of the JSON schema and of the upstream source LinkML YAML, respectively:

[git diff v3.2.0 v6.0.3 -- jsonschema/nmdc.schema.json](https://gist.github.com/dwinston/eae7d7b046b3771742d38489989bceed)

[git diff v3.2.0 v6.0.3 -- src/schema/*](https://gist.github.com/dwinston/bdff2c6a84a87875e906ce111d74264f)

Note: for the mCAFEs study and biosample data intended for portal release ASAP, @turbomam is ensuring they conform to v3.2.0 and will reserve v6.0.x-needed updates for future changesheets.
@
/cc  @shreddd @mcovalt @jeffbaumes

**Comment by jeffbaumes** [comment]
This sounds like a good plan @dwinston thanks.

**Comment by aclum** [comment]
We are on schema 10.* now so closing.
