### ISSUE TITLE
Reset scroll when you visit details page for study/sample

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#771]
To reproduce the behavior
1) click on any nmdc study
2) scroll to the bottom of the study page
3) use the back button on the study page (not browser back)
4) select another study or the same study
5) study page displays with the scroll bar all the way to the bottom.

**Comment by aclum** [comment]
@jeffbaumes  do you have more info or a screen/video of the problem? is this still a problem?

**Comment by naglepuff** [comment]
Still an issue

https://github.com/microbiomedata/nmdc-server/assets/7085625/0da17f7a-6108-430a-a141-a9db5bafb66e

**Comment by aclum** [comment]
@eecavanna do you have time to work on this next sprint?

**Comment by ssarrafan** [comment]
@JamesTessmer is going to take this one. Adding him and putting on the next sprint board.

**Comment by JamesTessmer** [comment]
@eecavanna Thanks for all that work! I think that will be a really good starting point to jump into this.

**Comment by JamesTessmer** [comment]
Here is the [pull request](https://github.com/microbiomedata/nmdc-server/pull/1225) for this issue.
After adding the fix the issue seems to be resolved.
Eric did most of the work finding the code and docs above, there was just a little bit of extra work to be done on where to place that line of code.

**Comment by JamesTessmer** [comment]
@ssarrafan The branch has been merged in, so I think we can mark this as done!
