### ISSUE TITLE
Fix DOI presentation on study page

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#772]
Currently on ingest, the "doi" slot and "publication_dois" slots are [mapped uniformly](https://github.com/microbiomedata/nmdc-server/blob/main/nmdc_server/ingest/study.py#L56-L59) to doi objects, and then the client attempts to [separate them back out](https://github.com/microbiomedata/nmdc-server/blob/main/web/src/views/IndividualResults/StudyPage.vue#L122-L127) by assuming that the dataset DOI (and no others) will have the "dataset" citation type. This causes duplicated and malformed DOI links when that is not the case (see e.g. #606 and the newly created study https://data.microbiomedata.org/details/study/gold:Gs0110119).

We should not be making this assumption, but should instead explicitly keep the provenance of which slot each publication came from and consistently place "doi" slot in the "Dataset Citation" heading and "publication_dois" in "Other Publications" heading.

**Comment by ssarrafan** [comment]
Adding to Sept sprint per @jeffbaumes

**Comment by mcovalt** [comment]
We'll need to move this to the next sprint. I'm currently prioritizing ingest failure (see #648).
