### ISSUE TITLE
env package or entire template name should be displayed in header of submission portal

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-server#780]
Users are currently expected to enter an environmental package value into all rows of their template, even though a global environmental package is captured on a previous screen. The environmental package value must be a constant, and it must agree with the value entered on the previous screen.

It sounds like @mslarae13 needs to see the environmental package when she reviews submissions. 

See also https://github.com/microbiomedata/sheets_and_friends/issues/136

**Comment by mslarae13** [comment]
This is resolved. The tab has the environmental extension.
