### ISSUE TITLE
show but don't require entry of env package

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-server#781]
- [x] #780
- [x] #782

@mslarae13

**Comment by mslarae13** [comment]
Relates to
https://github.com/microbiomedata/nmdc-server/issues/780
https://github.com/microbiomedata/sheets_and_friends/issues/136
https://github.com/microbiomedata/sheets_and_friends/issues/136#issuecomment-1235814783

**Comment by mslarae13** [comment]
@jeffbaumes Do we have a way to export the information a user adds to "Study Information", "Multiomics Data", and "Environmental Package"?
