### ISSUE TITLE
or auto-populate the DH tempalte with the env package value captured on a previous page

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/nmdc-server#782]
Possible alternative to #780 

@pkalita-lbl @mcovalt what do you think of auto-populating some DH columns?

**Comment by mslarae13** [comment]
OBE. We capture the env extension that was selected and have removed that slot from the template

**Comment by turbomam** [comment]
So was this overcome by events, or was there an alternative solution. Maybe I don't understand what overcome by events means.

Bottom line, by the time rows form the Submission Portal become Biosamples in MongoDB, they will have `env_package` values assigned, right?

**Comment by mslarae13** [comment]
Correct. `env_package` in mongo gets populated during ingest by filling in that value with what the user selects in the "Environmental Package" tab of the submission portal.
So OBE, we don't need to autopopulate.. the slot is gone from DH and we populate this information on ingest.

**Comment by turbomam** [comment]
Thanks. From today's NCBI export squad, it looks like we may need to populate the `env_package` **values** attached to Studies or Biosamples with a controlled vocabulary better aligned to either MIxS or NCBI' specifications. But that should probably be another issue

@aclum @sujaypatil96
