### ISSUE TITLE
file sizes shown for downloads are incorrect

### ISSUE THREAD

**Issue by cmungall** [microbiomedata/nmdc-server#784]
Here: https://data.microbiomedata.org/?q=ChgIABAAGAMiECJnb2xkOkdzMDEwMzU3MyI=

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/50745/189001447-3f66698e-95a6-462e-b149-0c1b2a703f70.png">

For RBA it says 3.3KiB for all files but in fact they are up to 1.4gb

**Comment by aclum** [comment]
This should be fixed for reiding. The file sizes between nersc, mongo, and the data portal UI don't match. @naglepuff  can you confirm that nmdc-server code uses the mongo file_size_bytes values for the data portal display?

**Comment by naglepuff** [comment]
The data portal does use `file_size_bytes`. Is this confirmed to still be an issue?

**Comment by aclum** [comment]
Yes, and appears to be an mongo to data portal ingest issue.

https://data.microbiomedata.org/?q=ChgIABAAGAMiECJnb2xkOkdzMDExNDY2MyI=
![Screenshot 2024-04-18 at 11 27 45 AM](https://github.com/microbiomedata/nmdc-server/assets/8196591/3b232dbf-9e89-4ce0-b816-f39607c97241)
The Kraken 2 classification plot is listed as 3.3 KiB. 
This is the corresponding record in mongo prod
  "_id": {
    "$oid": "65baf642583d633accb04636"
  },
  "name": "Gp0127633_Kraken classification TSV report",
  "description": "Kraken classification TSV report for Gp0127633",
  "data_object_type": "Kraken2 Taxonomic Classification",
  "url": "https://data.microbiomedata.org/data/nmdc:mga05zvf81/ReadbasedAnalysis/nmdc_mga05zvf81_kraken2_classification.tsv",
  "md5_checksum": "4825177c6d0a8b67db82e6070cfbc35f",
  "id": "nmdc:4825177c6d0a8b67db82e6070cfbc35f",
  "file_size_bytes": 1310443491
}

The actual file is 1.3 Gb.

 When I take the same identifier and query the data portal API with https://api.microbiomedata.org/api/data_object/nmdc%3A4825177c6d0a8b67db82e6070cfbc35f I get 
{
  "id": "nmdc:4825177c6d0a8b67db82e6070cfbc35f",
  "name": "1781_100335.classification.tsv",
  "description": "Gold:Gp0127633 KRAKEN2 output detail TSV file",
  "file_size_bytes": 3385,
  "md5_checksum": null,
  "url": "/api/data_object/nmdc%3A4825177c6d0a8b67db82e6070cfbc35f/download",
  "downloads": 1,
  "file_type": "Taxonomic Classification",
  "file_type_description": "[Kraken2] output read classification file",
  "selected": null
}
note that name, description and file_size are different between runtime API, backed by mongo and the data portal API, backed by postgres.

**Comment by aclum** [comment]
I believe everything is consistent after re-iding so closing this.
