### ISSUE TITLE
Submission portal- when validation is right there's no confirmation

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-server#787]
This morning I went to check a users submission & pressed the validation button like 6 times, cuz I thought it wasn't working, before I realized that everything was just correct.

Would be helpful to have some kinda of "congrats! Your metadata has been validated" banner or notification that validation was run and complete & it's all good.

What does completion of this ticket look like?
- Upon submitting the complete and validated metadata an pop up appears with next steps
- Upon running validation of metadata on the submission portal, a "complete and correct" notification will pop up.
-- This is lower priority than submitted confirmation
- This feature will be active on production. 

**Deliverable this task is associated with**

_See Deliverables tab here: https://docs.google.com/spreadsheets/d/1z_b6WbuTk4pI0Q-Z-rfCgC-8R3m3F2_JDevYuK8CjYE/edit?usp=sharing_

- 5

**RACI**

_Tag people in their roles_
- Responsible: James
- Accountable: @naglepuff 
- Consulted: Montana
- Informed:

**Describe the the task?**
- [ ] Add a notification that the valid submission is now submitted, pending review & provide next steps
- [ ] Add a notification that validation has run / metadata is complete
- [ ] Add a notification when metadata is submitted

**Criteria for completion**
- Users see a notification when they complete metadata & validate

**Estimate people time**
- ?

**Completion Date (Goal)**
- March 15th (in dev) (TBC)

**Target Sprint Start & End Dates**
- Start: 
- End: 03/15

**Tag Blocker/Contingent upon isues**
- [Tagg issues]

**Comment by mslarae13** [comment]
March 15th is doable. ECR/GSP

**Comment by ssarrafan** [comment]
What's the status of this issue?  It was on the GSP/ECR board.  @JamesTessmer @mslarae13

**Comment by JamesTessmer** [comment]
It should be done @ssarrafan, the PR just needs to be approved and merged (barring some issue that we missed).

**Comment by ssarrafan** [comment]
> It should be done @ssarrafan, the PR just needs to be approved and merged (barring some issue that we missed).

Great. Can you link the PR here?

**Comment by mslarae13** [comment]
in prod!

@JamesTessmer can I make 1 annoying request that I didn't notice. Can we make the grey check box when you submit say "Submitted" instead of done?

![Image](https://github.com/microbiomedata/nmdc-server/assets/44581429/4a3b9125-3a19-4716-aecb-b342aa7ff5c2)

**Comment by JamesTessmer** [comment]
Yup, I can make that change. Should be super quick, I can throw up a PR after the hackathon.

**Comment by mslarae13** [comment]
I think this is done! https://github.com/microbiomedata/nmdc-server/pull/1255
@JamesTessmer please close if so

**Comment by JamesTessmer** [comment]
It is done, closing now.
