### ISSUE TITLE
Migrate data portal to newest version of schema

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#790]

**Comment by ssarrafan** [comment]
@turbomam can you please point @mcovalt to where the latest version. 
Just discussed this with Jeff B. and assigning to the next sprint.

**Comment by jeffbaumes** [comment]
@turbomam can you point us to the data compliant with the latest schema?

**Comment by naglepuff** [comment]
Here is the migration script for 7.0:
https://github.com/microbiomedata/nmdc-schema/blob/issue-486-data-to-7-0/util/migrate_7_0.py

**Comment by turbomam** [comment]
I expect there will be a few more tweaks this week, but I will share a dump minus these two large collections today:

- functional_annotation_set
- genome_feature_set

**Comment by turbomam** [comment]
I did the following **dump & compress** which generated `mongo_for_nmdc_7.tar.gz`. Where should I put it?


## stats for resulting `mongo_for_nmdc_7.tar.gz`

```shell
ls -ltrh mongo_for_nmdc_7.tar.gz 
```

> -rw-r--r--  1 MAM  staff    43M Oct 18 14:49


## dump & compress
```shell
mongodump --port 27777
tar czvf mongo_for_nmdc_7.tar.gz dump
```

> a dump
a dump/nmdc_7_0_0
a dump/admin
a dump/admin/system.version.bson
a dump/admin/system.version.metadata.json
a dump/nmdc_7_0_0/biosample_set.metadata.json
a dump/nmdc_7_0_0/nom_analysis_activity_set.metadata.json
a dump/nmdc_7_0_0/metagenome_assembly_set.metadata.json
a dump/nmdc_7_0_0/metatranscriptome_activity_set.bson
a dump/nmdc_7_0_0/metaproteomics_analysis_activity_set.metadata.json
a dump/nmdc_7_0_0/metatranscriptome_activity_set.metadata.json
a dump/nmdc_7_0_0/mags_activity_set.bson
a dump/nmdc_7_0_0/study_set.bson
a dump/nmdc_7_0_0/metabolomics_analysis_activity_set.bson
a dump/nmdc_7_0_0/biosample_set.bson
a dump/nmdc_7_0_0/metagenome_assembly_set.bson
a dump/nmdc_7_0_0/mags_activity_set.metadata.json
a dump/nmdc_7_0_0/metagenome_annotation_activity_set.bson
a dump/nmdc_7_0_0/nom_analysis_activity_set.bson
a dump/nmdc_7_0_0/metabolomics_analysis_activity_set.metadata.json
a dump/nmdc_7_0_0/omics_processing_set.metadata.json
a dump/nmdc_7_0_0/data_object_set.metadata.json
a dump/nmdc_7_0_0/metagenome_annotation_activity_set.metadata.json
a dump/nmdc_7_0_0/study_set.metadata.json
a dump/nmdc_7_0_0/data_object_set.bson
a dump/nmdc_7_0_0/metaproteomics_analysis_activity_set.bson
a dump/nmdc_7_0_0/omics_processing_set.bson

**Comment by naglepuff** [comment]
Would the DOE - NMDC google drive work?

**Comment by turbomam** [comment]
It looks like @ssarrafan is looking into that. I have not found this shared drive useful since the reorganization.

**Comment by ssarrafan** [comment]
> It looks like @ssarrafan is looking into that. I have not found this shared drive useful since the reorganization.

Mark was able to share the file via Google drive. Thanks Wendi.

**Comment by naglepuff** [comment]
This will have to be moved to the next sprint, as I will not be able to complete by EOD today.

**Comment by ssarrafan** [comment]
@naglepuff any update on this one?  Can it be closed?

**Comment by naglepuff** [comment]
I've made some progress on this one, but it can't be closed yet. Once I am reasonably sure that the ingest script and postgres database are properly adjusted for the new schema, we'll need to decide on a method for testing and verification.

**Comment by ssarrafan** [comment]
@naglepuff are you still working on this issue?

**Comment by naglepuff** [comment]
I've opened PR #797. In order to get this over the finish line that PR needs to be reviewed and merged, and the version 7 compliant data must be loaded into the new dev mongo instance. From there, testing can take place in the dev portal.

**Comment by ssarrafan** [comment]
> I've opened PR #797. In order to get this over the finish line that PR needs to be reviewed and merged, and the version 7 compliant data must be loaded into the new dev mongo instance. From there, testing can take place in the dev portal.

Ok would like me to leave this issue open or can I close it since it's now in the PR track.

**Comment by naglepuff** [comment]
It should probably stay open. Once that PR is merged it should automatically close this issue

**Comment by ssarrafan** [comment]
> It should probably stay open. Once that PR is merged it should automatically close this issue

ok I'll move this over to the next sprint
