### ISSUE TITLE
Investigate data portal DB/API unification

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#796]

**Comment by ssarrafan** [comment]
@jeffbaumes Is there any update on this issue?  Would be great to add any links or other info and close it if you've had time to investigate.

**Comment by jeffbaumes** [comment]
Yes, @mcovalt has done what I believe is the investigation required at this point to have a conversation. We can likely mark this closed after a discussion Thursday, though there will likely be follow up tasks.

**Comment by jeffbaumes** [comment]
@mcovalt can link to his investigation notes.

**Comment by mcovalt** [comment]
You bet, [here they are](https://www.notion.so/Moving-away-from-ingest-ec10b276f48f47a78fcff93daaf6bf21). Note: the sections are collapsed by default in Notion. Toggle the triangles to read more in each section.

**Comment by jeffbaumes** [comment]
I consider this initial investigation closed at this point. It was resolved from this investigation that for performance reasons we cannot build the search API system solely on schema-compliant mongo documents. There will need to be derived data that is denormalized and/or aggregated for performant search. Currently this derived data is in Postgres but this could potentially be migrated to Mongo, ElasticSearch, or even a graph database. Derived data could be computed en masse (as it is today) or performed incrementally for a performance boost if we implement a two-phase commit protocol.

@elais @cmungall @mcovalt @shreddd @dwinston
