### ISSUE TITLE
Add facet groupings to sidebar list

### ISSUE THREAD

**Issue by subdavis** [microbiomedata/nmdc-server#81]
Group the environment levels, maybe the locations, and everything else into 3 ordered groups.
This is only for the environment page, right @jeffbaumes ?

**Comment by jeffbaumes** [comment]
There are the 5 GOLD environment levels, 2 ENVO terms (the "environmental ..." ones), location related ones, then I'd put everything else into an Other. Not sure what you mean by 3 ordered groups.

**Comment by jeffbaumes** [comment]
And yes, I don't know that there are any known good grouping ideas for the other types.

**Comment by subdavis** [comment]
I just meant the groups I had enumerated.  Turns out there are 4 groups (your list) and that order matters (mostly GOLD levels).
