### ISSUE TITLE
Develop sandbox instance of submission portal for workshops.

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#814]
This issue is related to the sandbox needed for workshops. There have been discussions and the decision is to bring up a new instance.  

- [x] #815
- [x] Deploy submission portal sandbox to new instance
- [x] Test new sandbox 

@mslarae13 @shreddd can you please add additional tasks to this issue?

**Comment by mslarae13** [comment]
Matt has been working on this. Still need to complete ORCID sign in and admin privileges.

**Comment by mcovalt** [comment]
ORCiD authentication is complete and users (and their admin privileges) have been copied over from the production deployment into the sandbox.

**Comment by ssarrafan** [comment]
@mslarae13 can you check this and let me know if it's ok to close this one?

**Comment by mslarae13** [comment]
https://data-sandbox.microbiomedata.org/submission/home

**Comment by mcovalt** [comment]
Submissions in the sandbox are deleted at midnight every Sunday. This is accomplished via the [clear-submissions-cron-job](https://rancher2.spin.nersc.gov/p/c-tmq7p:p-bkv45/workload/cronjob:nmdc-sandbox:clear-submissions-cron-job) Workload in Rancher.
