### ISSUE TITLE
Stegen biosample type mis-represented?

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-server#818]
On the NMDC data portal, James Stegen's study "Riverbed sediment microbial communities from the Columbia River, Washington, USA" has all samples that start with GW-RW listed as sediment samples.
https://data.microbiomedata.org/details/sample/gold:Gb0126430
https://data.microbiomedata.org/?q=ChgIABABGAMiECJnb2xkOkdzMDExNDY2MyI=

But, when you follow the Biosample sample identifier, it's a "groundwater metagenone" from a "sand" sample.
img & gold say sediment

Biosample (groundwater metagenome, sand): https://www.ebi.ac.uk/biosamples/samples/SAMN06267115#:~:text=groundwater%20metagenome 

Questions / resolution
1: Do we need to follow up on what is listed in biosample?
2: Is it our responsibility to make sure the external source is right? Do we assume GOLD and NMDC and IMG are right, and biosample is incorrectly represented?
- If we assume we're correct, and we don't bother with updating biosample, this issue can be closed.

@emileyfadrosh , @aclum , @ssarrafan  , FYI.

**Comment by emileyfadrosh** [comment]
I am sending this to Reddy to check with what was submitted to the INSDC. Stay tuned. Thanks!

**Comment by ssarrafan** [comment]
From Reddy:  GOLD will be notifying NCBI about the BioSample updates. JGI/GOLD JIRA ticket number for reference:  https://issues.jgi.doe.gov/browse/GOLD-2032

Closing this issue.
