### ISSUE TITLE
Submission Portal: User edit permissions

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-server#824]
Current Status:
As of 2023-01, every submission on the sample submission portal is limited to being viewed and edited by the individual that started the submission. The individual that started the submission cannot share their submission with others & it is non-collaborative.

Need:
We need the ability to 'add authorized users' to a submission. For example, the PI can add their post-doc to the submission so the post-doc can add metadata to the study the PI has submitted. Additionally, for projects like MONet or NEON, additional metadata can be added post sample receiving and we need to add permissions for people to contribute.

Required for resolution / Criteria for completion:
- Describe / define who can edit a submission. How permissions are give.
- Implement permissions for multiple submitters.

**Deliverable this task is associated with**

_See Deliverables tab here: https://docs.google.com/spreadsheets/d/1z_b6WbuTk4pI0Q-Z-rfCgC-8R3m3F2_JDevYuK8CjYE/edit?usp=sharing_

- 6

**RACI**

_Tag people in their roles_
- Responsible: @naglepuff 
- Accountable: @shreddd 
- Consulted: @pkalita-lbl , @lamccue , @mslarae13 
- Informed:

**Describe the the task?**
- [ ] Incorporate ORCID access for multiple editors for permissions
- [x] Block multiple editors at 1 time / limit submission edits to 1 person
- [ ] ~Add multiple editors framework to schema @brynnz22~
- [x] https://github.com/microbiomedata/nmdc-server/issues/1077
- [x] https://github.com/microbiomedata/nmdc-server/issues/1078

**Criteria for completion**
- Submitters can indicate who should / can edit a submission & provide permission levels
- Permission level will be associated with credit roles
- When a submitter tries to edit a submission that is currently being edited it will be locked / blocked and they'll receive a notification

**Estimate people time**
- 40?

**Completion Date (Goal)**
- 11/3
- Rescheduled for 02/09

**Target Sprint Start & End Dates**
- Start: 9/25
- End: 02/09

**Tag Blocker/Contingent upon issues**
- https://github.com/microbiomedata/issues/issues/416

**Comment by mslarae13** [comment]
This came up again in the metadata meeting on 2023-04-05

GOLD and OSTI have a concept of co-PI... NMDC doesn't have co-PI... we only have PI because we added it outside of the standard CRediT roles we provide.

If we add co-PI as a role, we could use this and other CRediT roles to assign who has permissions to edit a submission or study.

**Comment by mslarae13** [comment]
@naglepuff @marySalvi  @brynnz22 @pkalita-lbl  please use the tasks above to split this issue up into smaller tasks as necessary

**Comment by naglepuff** [comment]
Smaller tasks 

- [ ] #1076 
- [ ] #1077 
- [ ] #1078

**Comment by mslarae13** [comment]
decisions made in : https://github.com/microbiomedata/issues/issues/416

**Comment by ssarrafan** [comment]
Based on discussion at infra sync meeting yesterday I'm moving this to the next sprint.  @naglepuff @mslarae13 FYI

**Comment by ssarrafan** [comment]
Last day of sprint. Removing from sprint. Adding backlog label.

**Comment by mslarae13** [comment]
@naglepuff @pkalita-lbl  will we need a reviewer role to enable people reviewing submissions in the 'new interface' or is that not a 'role'?

**Comment by pkalita-lbl** [comment]
There could be a reviewer role, but it would be a bit different than the other roles (if I'm understanding the point of the reviewer correctly anyway). For roles like Editor, Viewer, Metadata Contributor, the Owner (the person who created the submission) assigns other uses to those roles. But they won't choose their own reviewer will they? That will be automatically determined by... something?

**Comment by mslarae13** [comment]
From Infra sync
- If JGI PMs share their name and email with trusted organizations through ORCID
- Will JGI PMs have ORCIDs? Dana could do a join on contacts table to pull PM ORCID.

The JGI PM associated with the 'pending metadata' status for sequencing project will be joined with the ORCID on contacts table to share ORCID of JGI PM for this project's samples to the NMDC study that is having metadata submitted.

Do need reviewer role. 

Role relation table will match the ORCID as a string. If the PM has signed into the submission portal already, we could use their ORCID as a foreign key (user must already exist in the database).

Submission portal, review is a viewer. But in the "separate page view" (to be created) shows just the information the review needs and allows commenting.

**Comment by mslarae13** [comment]
> But they won't choose their own reviewer will they? That will be automatically determined by... something?

Correct

> would be a bit different than the other roles

On the submission, it's the same as viewer. In this to be created 'review' view they'll be able to comment.

**Comment by bmeluch** [comment]
Tested https://github.com/microbiomedata/nmdc-server/issues/1076 
Submission locking works in dev - Montana was unable to edit a submission when I had it open, and I was unable to edit a submission when she had it open 👍

**Comment by ssarrafan** [comment]
@naglepuff @mslarae13 can this issue be closed?  I'll move to new sprint since it appears to be active.

**Comment by mslarae13** [comment]
Testing Notes
- Editor permissions can't remove their orcid, but they can completely delete themselves. Remove the ability to delete yourself. 
  - With that, why after self deletion can the person with editor permissions still see and edit?
  - When the submitter deletes the editor permission given, the submission does disappear
  - If editor removes themself & submitter goes back into the study page, permissions are empty but they still have edit access. Submitter has to change edit to view to actually remove the permission

- Montana (submitter) started a submission, added some metadata to DH. Made Bea a "Metadata Contributor". She edited the DH sheet, pressed validate, it's invalid. When she goes back to 'Home' her metadata edits disappear.  

- Similar to the previous scenario, we made Bea an "Editor" and her DH edits did not disappear. (DH = Data Harmonizer)

**Comment by mslarae13** [comment]
@naglepuff  See my above comment.

@sujaypatil96 , @jkelliher-github , @pkalita-lbl @aclum , @lamccue , @simroux 

Would appreciate if if you all could poke at it & make sure you see the results. I have 'super user' permission.. I want to be sure people without super user permissions experience the same things!

**Comment by simroux** [comment]
One more note: when playing around with the "adding contributors", I was able to add multiple contributors with the same ORCID, which is probably something we should prevent against / forbid.

**Comment by naglepuff** [comment]
@mslarae13 thank you for bringing these to my attention. Sorry that I did not see this feedback sooner. Seeing as how this is already in production, I have prioritized addressing these concerns. 

See #1159 for the fixes. So far that includes

1. Disabling the "delete contributor" button if the contributor's ORCID matches the currently logged in user
2. Allowing "metadata contributors" to actually save
3. Preventing duplicate ORCID iDs in the contributors list

It sounds like in order to address all the concerns you outlined, I still need a tooltip to explain permission levels. It would be helpful if you knew where exactly that tooltip should go and what it should say. If that part can wait, then I can open up the PR for review (hopefully @marySalvi has some bandwidth for it) and try to get it merged into dev ASAP. 

@pkalita-lbl seeing as there is a known functional issue in production ("metadata contributors" can't save edits to the DH tab), this might be a good candidate for our first non-scheduled patch release.

**Comment by pkalita-lbl** [comment]
Regarding the patch release process, it looks like [some work](https://github.com/microbiomedata/nmdc-server/compare/v0.18.0...main) has gone into dev after the last release. So the options are:

1. If the work already on dev is well-tested and safe to release to prod, use your normal development workflow and we'll make a new tag from `main` when the hotfix is done and tested.
2. If the work already on dev should not be released yet, work off of the last release tag to make a hotfix tag. We'll release that tag and then the changes can be merged back into `main`. Roughly:
```
git checkout v0.18.0
git checkout -b hotfix-issue-NNN
<make changes & commit>
git tag v0.18.1
git push --tags
<make GitHub release based on v0.18.1 tag>
git checkout main
git merge hotfix-issue-NNN
git branch -d hotfix-issue-NNN
```

**Comment by naglepuff** [comment]
I opened #1162 to track the tooltip issue so I can merge the more functional changes.

**Comment by mslarae13** [comment]
Testing Notes
- **FIXED** : Editor permissions can't remove their orcid, but they can completely delete themselves. Remove the ability to delete yourself. 
  - **IRRELEVANT** : With that, why after self deletion can the person with editor permissions still see and edit?
  - **Still works!**: When the submitter deletes the editor permission given, the submission does disappear
  - **IRRELEVANT**: If editor removes themself & submitter goes back into the study page, permissions are empty but they still have edit access. Submitter has to change edit to view to actually remove the permission

- **FIXED** Montana (submitter) started a submission, added some metadata to DH. Made Bea a "Metadata Contributor". She edited the DH sheet, pressed validate, it's invalid. When she goes back to 'Home' her metadata edits disappear.  

- ** FIXED** Similar to the previous scenario, we made Bea an "Editor" and her DH edits did not disappear. (DH = Data Harmonizer)

- **FIXED / IRRELEVANT** Similar to the 2 above, Bea made a study (submitter) and made me a metadata contributor. But my edits did NOT disappear. I suspect it's because I have editor permissions by default.


ADD THESE TO MIKE'S ISSUE: https://github.com/microbiomedata/nmdc-server/issues/1162
- [ ] We should add a tool tip that explains the different permission levels.
- [ ] New bug, make an issue: If someone is a metadata contributor, they can't validate the EMSL shipping to move on. This relates to the EMSL shipping bug here: (ADD LATER)
- [ ] Add a "No shipping information required" check box.
- [ ] Add a banner for "Metadata Contributor" that says "Permission level access does not allow editing of this page. Contact the submission Author to request a change in permission status"

**Comment by mslarae13** [comment]
@naglepuff  All the bugs appear to be fixed! I think we're good to go!!

Note on the duplicate ORCIDs, Bea couldn't move onto the next step because the same orcid was listed twice. I think that's fine.
New error 'orcid must be unique' is good!
But, people can add their own ORCID as the submitter. I think that's ok because the submitter might want to identify their credit roles
Additionally, if I assign someone as PI, AND make them viewer in the Contributors section, contributors supersedes PI. Make this the other way around.
