### ISSUE TITLE
Ensure compliance with ORCID brand guidelines

### ISSUE THREAD

**Issue by naglepuff** [microbiomedata/nmdc-server#826]
[info.orcid.org/brand-guidelines](https://info.orcid.org/brand-guidelines/)

**Comment by naglepuff** [comment]
`nmdc-server` should follow [the minimum requirements for ORCID member integration](https://info.orcid.org/ufaqs/what-are-the-minimum-requirements-for-a-member-integration/).

To summarize:

- [x] Use OAuth to authenticate ORCID iDs
- [x] Include an ORCID branded button to initiate authentication
- [ ] Present auth screen according to [these guidelines](https://info.orcid.org/documentation/integration-guide/user-experience-display-guidelines/#ORCID_OAuth_sign-in_screens)
- [x] Use HTTPS to redirect
- [ ] Accept and store token exchange data with user data
- [x] Use appropriate scopes and request methods (we only use ORCID for authorization)
- [ ] Publicly display authenticated ORCID iDs following the [guidelines](https://info.orcid.org/trademark-and-id-display-guidelines/) (#829)

(From duplicate #830)

**Comment by ssarrafan** [comment]
@naglepuff moving to the next sprint. Let me know if this won't be actively worked on for the next few weeks.

**Comment by ssarrafan** [comment]
What's the status of this @naglepuff @shreddd?

**Comment by ssarrafan** [comment]
Adding Shreyas as an assignee. He needs to review this and follow up with ORCID folks. Moving to next sprint

**Comment by ssarrafan** [comment]
Checked with Shreyas and will move this to the next sprint.  @naglepuff can you please add any updates based on your meeting with the ORCID team?  

This is not highest priority but will keep it on the sprints to get more info documented for now.

**Comment by ssarrafan** [comment]
We just got feedback from Mary on this so I will keep this active and move to the next sprint.  Here's the feedback for reference:

Shreyas,

 

Here is the general feedback and recommendations based on the initial demo.

 

·         Ensure all ORCID brand standards, guidelines are implemented across the interaction - https://info.orcid.org/brand-guidelines/

o   Example: Display Formats

§  Full ORCID iD – orcid logo 16pxhttps://orcid.org/0000-0001-5727-2427

§  Compact ORCID iD – orcid logo 16px 0000-0001-2345-6789

§  Inline ORCID iD – Sarah Pascoe orcid logo 16px

o   When to use the full ORCID iD format

§  The ORCID iD is shown on its own or in a list of links.

§  There is sufficient space to show the full ORCID iD.

·         As a part of the authentication login integration screen, include information as to how/why you will be connecting to ORCID and using their information; essentially, provide an explanation of the integration and how/why you are collecting ORCID iDs.

o   Example:

§  [Organization name] is collecting your ORCID iD so we can [add purpose]. When you click the “Authorize” button, we will ask you to share your iD using an authenticated process: either by [registering for an ORCID iD](https://orcid.org/register) or, if you already have one, to [sign into your ORCID account](https://orcid.org/signin), then granting us permission to get your ORCID iD. We do this to ensure that you are correctly identified and securely connecting your ORCID iD. Learn more about [What’s so special about signing in](https://orcid.org/blog/2017/02/20/whats-so-special-about-signing).

·         If you are writing to records, include an explanation of your integration and the benefits of connecting your information to the researcher’s ORCID record, in particular, the auto-update feature if applicable

o   Example text:

§  By sharing your iD with [ORGANIZATION NAME], and giving us permission to read and update your ORCID record, you enable us to help you keep your record up-to-date with trusted information. Learn more in [Six ways to make your ORCID iD work for you!](https://info.orcid.org/six-ways-to-make-your-orcid-id-work-for-you/)

·         If you use webhooks (the synchronize feature), include an explanation of your integration and the benefits of synchronization.

o   Example:

§  [[ORGANIZATION] is making it possible for you to easily share your research information and keep it up-to-date. With your permission, we will synchronize information between [SYSTEM NAME] and your ORCID record, every XX days/weeks.

·         If you are reading records, include an explanation of your integration and the benefits of collecting information from the researchers record.

o   Example:

§  Filling in the same information about yourself over and over again is frustrating. That’s why we let you choose information from your ORCID record to populate our online forms [MEMBER TO ADD SPECIFIC USE CASE].

·         Specify Scopes used to write on Record: activities/update and/or person/update.

o   https://info.orcid.org/ufaqs/what-is-an-oauth-scope-and-which-scopes-does-orcid-support/

 

Please review and let me know if you have any questions regarding this feedback.


 

Thanks,

 

Mary Beth West

 

Mary Beth West

USDOE/OSTI

**Comment by shreddd** [comment]
I think this can be closed now? We seem to have the go-ahead from OSTI.
