### ISSUE TITLE
Develop interface which enables multiple data harmonizer sheets

### ISSUE THREAD

**Issue by pkalita-lbl** [microbiomedata/nmdc-server#831]
This is a follow up to microbiomedata/issues#30. The task here is to implement the ideas put forth in [the prototype](https://github.com/pkalita-lbl/dh-stepper-example) in the actual submission portal.

**Comment by ssarrafan** [comment]
@pkalita-lbl I added this to the next squad, beginning Monday.  If that's not accurate let me know.  Thanks.

**Comment by ssarrafan** [comment]
Assuming this is still being worked on. Will move to the next sprint. @pkalita-lbl let me if that's wrong.
