### ISSUE TITLE
Member Integration Summary

### ISSUE THREAD

**Issue by naglepuff** [microbiomedata/nmdc-server#832]
## Minimum Requirements ([link](https://info.orcid.org/ufaqs/what-are-the-minimum-requirements-for-a-member-integration/))

- Use OAuth to authenticate ORCID iDs -> We are compliant
- Include an ORCID branded button to initiate authentication -> We are compliant
- Present OAuth screen according to their [guidelines](https://info.orcid.org/documentation/integration-guide/user-experience-display-guidelines/#ORCID_OAuth_sign-in_screens) -> I believe we are compliant, we use the redirect method
- Use HTTPS to redirect -> We are compliant
- Accept and store all data returned in the token exchange with the user's data -> We don't do this
- Use appropriate scopes -> We are compliant
- Publicly display authenticated ORCID iDs -> We don't do this. (#829 includes this change)

## Best Practices ([link](https://info.orcid.org/ufaqs/integration-best-practices/))
- [Customize the user experience](https://info.orcid.org/documentation/integration-guide/customizing-the-sign-in-register-screen/) -> we might be fine here, due to our limited use of ORCID
- Provide a workflow if users deny us permission -> we don't explicitly do this, but the fact that login is required to download files and create submissions ought to cover this; the rest of the system is still usable
- Provide an option for users to remove ORCID iD data -> we don't do this
- Update added items when corrections are needed using the items' unique put code -> Not sure what this means, but I don't think this applies since we don't ever write data to ORCID
- Provide descriptive error messages when integration does not go as expected -> Not sure if we do this, not sure what reasons would prevent login
- Display the ORCID member logo -> I don't believe we have one
- Follow branding guidelines (#829 is attempting to make sure we do this)
- Use access token to check for existing permissions -> we don't do this since we don't store the token in our system. I don't think this is an issue though, since we only fetch data from ORCID once and then we have everything we need. no part of a user workflow will prompt any sort of re-auth

**Comment by shreddd** [comment]
@naglepuff - can we close this?

**Comment by ssarrafan** [comment]
I added this to the auth squad board and closing it.
