### ISSUE TITLE
Create submission context form

### ISSUE THREAD

**Issue by naglepuff** [microbiomedata/nmdc-server#834]
Based on the diagram [here](https://lucid.app/lucidchart/75516c27-0974-4a77-ae92-73234e3f385e/edit?invitationId=inv_8fe7dca1-e52f-431c-9a0e-f1e6dd1e3a72&page=0_0#)
Relevant mockups [here](https://www.figma.com/file/KUtfSqxhYCn334xkoh2CBr/Submission-Portal?node-id=1603%3A51)

**Comment by naglepuff** [comment]
Questions about the address form: @mslarae13

1. Do we want to support international addresses for the shipper information?
2. Do we want to support international addresses for the IRB section?
3. For the "sample" field, what are the valid values? (the example given is "water_extract_soil") Can these come from the schema?
4. Biosafety levels: what are the valid choices here?

**Comment by mslarae13** [comment]
> Questions about the address form: @mslarae13
> 
> 1. Do we want to support international addresses for the shipper information?
Yes
> 2. Do we want to support international addresses for the IRB section?
No, I don't think so. This field is rarely used, and it's only when BSL2 is selected
> 3. For the "sample" field, what are the valid values? (the example given is "water_extract_soil") Can these come from the schema?
Yes-ish... in https://github.com/microbiomedata/nmdc-schema/blob/main/src/schema/portal/emsl.yaml we have "ample_type_enum" but that currently only has the 2 types of soil. The file I shared has MANY more, but not sure they're all relevant for NMDC. We should chat about this.
> 4. Biosafety levels: what are the valid choices here?
BSL1 or BSL2

**Comment by naglepuff** [comment]
@mslarae13 

Thanks for getting back to me about this. Until we get the change to talk more about #3 I'll go ahead and use the two values in the schema.

Additionally, it would  be helpful to know if EMSL is selected and the shipping information form is available, how much of that form (if any) is required? My default mode going forward would be to make all of those fields optional, and make any necessary changes as part of the feedback loop when I get back from being out.

If validation of the shipping form is straightforward there is a chance I can get that in before I go.
