### ISSUE TITLE
Display MASSIVE identifiers on study page

### ISSUE THREAD

**Issue by naglepuff** [microbiomedata/nmdc-server#838]
See https://github.com/microbiomedata/nmdc-schema/pull/668

**Comment by ssarrafan** [comment]
@naglepuff I will add this to the sprint but if you're not currently working on this let me know.

**Comment by naglepuff** [comment]
I'm not currently working on this. This is dependent on the relevant data being added to the mongo and ingested into the postgres data portal database. It will likely follow the migration to version 7.4

**Comment by naglepuff** [comment]
Still no update on this, as it will need to follow the schema migration.

**Comment by ssarrafan** [comment]
> Still no update on this, as it will need to follow the schema migration.

Ok will move to next sprint @naglepuff

**Comment by naglepuff** [comment]
With other links we display on the study page, there is an image of a logo to where we are linking. For example:
![example_link](https://user-images.githubusercontent.com/7085625/224765221-6c96c617-7493-425c-bc00-45f88ed872a1.png)

Is there an image to use for displaying MASSIVE identifiers?

**Comment by aclum** [comment]
@sujaypatil96 is planning on submitting to mongo either today or Tuesday. blocked on https://github.com/microbiomedata/issues/issues/42

**Comment by ssarrafan** [comment]
![Image](https://user-images.githubusercontent.com/79225425/225722412-7f538776-35e3-4485-b290-e728de6d6901.png)

Image for MassIVE emailed to @naglepuff today.  
Attached here.

**Comment by ssarrafan** [comment]
Moving to next sprint.

**Comment by ssarrafan** [comment]
@naglepuff is "in review" the correct status for this?  I don't think you're waiting for anyone to review right?

**Comment by aclum** [comment]
This is not on the study page yet
https://data-dev.microbiomedata.org/details/study/nmdc:sty-11-r2h77870

**Comment by naglepuff** [comment]
#906 will solve this. If the "In Review" status means that the fix is in dev, then that would not be the correct status for this. Once code review is done this will move to dev.
