### ISSUE TITLE
Migrate existing submissions for account for new data model changes

### ISSUE THREAD

**Issue by naglepuff** [microbiomedata/nmdc-server#841]
Submission portal work is currently underway that changes the data structure for submissions. 

@pkalita-lbl I believe you said some of your changes to allow for the multi-tabbed data harmonizer will necessitate an alembic migration. Do you also need to write some conversion code for existing submissions in postgres? Some of my changes break Pydantic model validation, but don't require changes to the DB tables, so I'll need to write some conversion code for that.

I'd prefer to run conversion once, so we can silo off those scripts from the rest of the code base.

**Comment by pkalita-lbl** [comment]
The mutli-tab DH work requires changes to the JSON that's stored in the `metadata_submission` column of the `submission_metadata` table. Those changes are currently in the `issue-831` branch. 

The alembic migration is here: https://github.com/microbiomedata/nmdc-server/blob/issue-831/nmdc_server/migrations/versions/23e0702d2321_multi_tab_metadata_submission_format.py 

And the corresponding change to the Pydantic model: https://github.com/microbiomedata/nmdc-server/compare/main...issue-831#diff-3987ac791d3a4ec70b1b93413ea79e3a4a3e13bdd7611415bc824e13eb8f030e

**Comment by naglepuff** [comment]
Closing this issue. Alembic migrations were used to update the data when containers get redeployed.
