### ISSUE TITLE
Change process to be able to ingest aggregated data

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#845]
change the process on the data portal end to ingest the aggregated data instead of aggregating the data on the data portal
Related to https://github.com/microbiomedata/issues/issues/56

FYI @jeffbaumes

**Comment by scanon** [comment]
@naglepuff @jeffbaumes : I made a comment in https://github.com/microbiomedata/issues/issues/56.

**Comment by ssarrafan** [comment]
Checked with Mike and moving this to the next sprint.

**Comment by naglepuff** [comment]
Still need to do more investigation on the scope of this change.

**Comment by ssarrafan** [comment]
> Still need to do more investigation on the scope of this change.

ok I'll move to the next sprint @naglepuff

**Comment by ssarrafan** [comment]
Mike and Jeff to discuss Wednesday. Will move to new sprint for now.

**Comment by ssarrafan** [comment]
@naglepuff @jeffbaumes assuming this one can be closed, correct?

**Comment by naglepuff** [comment]
Yes, this is done

**Comment by ssarrafan** [comment]
Great. Closing issue. Thanks @naglepuff
