### ISSUE TITLE
Citations not appearing correctly, and title does not appear.

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#85]
When I first navigate to Mary Firestone's study then go to James Stegen's study page, I get this, where the other publications shows one from Firestone and the citation area is empty.

![image](https://user-images.githubusercontent.com/81305/88191041-004c6500-cc09-11ea-8cd0-7404419659ef.png)

The old pilot had a citiation and two other publications:

![image](https://user-images.githubusercontent.com/81305/88191189-28d45f00-cc09-11ea-9790-18867048c95b.png)

Also, the title text is not there, which had been in the "proposal title" field. Is that field not available in the latest JSON?

**Comment by jbeezley** [comment]
The response to that study has three associated dois.  I'm not distinguishing between the main citation and other publications in the database.  It looks like it is always returning the main citation as the first element in the list, but I don't think that is a guarantee.

The title is in the response as `name`.  Should be an easy fix.

@subdavis I can take care of this.

**Comment by jbeezley** [comment]
There is also the issue that the old values will appear briefly while the new values are fetched.  I suspect there is some sort standard way of dealing with this.
