### ISSUE TITLE
Push Dataharmonizer Updates to Prod

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#853]
This issue is to track Patrick's Dataharmonizer updates to be pushed to prod after testing.  
See more at https://github.com/microbiomedata/NMDC_Planning/issues/199

**Comment by ssarrafan** [comment]
@naglepuff I think you mentioned that you merged these updates at the infra sync meeting Thursday so I'll close this issue.
@pkalita-lbl

**Comment by mslarae13** [comment]
@naglepuff  can you let me know when this is in prod? Ping on slack would be appreciated 😅

**Comment by naglepuff** [comment]
The DH update to multi-tab is is prod as of 3/8
