### ISSUE TITLE
Submission Context: EMSL Shipping conditions

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#866]
Shipping conditions in EMSL shipping information should be an enumerated drop down
“Store frozen: transported within a cold chain and stored at -70°C to -80°C upon delivery.”
“Store frozen: transported within a cold chain and stored at -20°C (4°F).”
“Store Refrigerated: at 2°-8°C (36°-46°F): for heat sensitive products that must not be frozen.”
“Room temperature: Store at 15°-25°C (59°-77°F).”
“Other”
- Allows for a text box to be filled out

**Comment by naglepuff** [comment]
@mslarae13 Are these options from the schema?

**Comment by mslarae13** [comment]
None of the EMSL submission stuff is from the schema
