### ISSUE TITLE
Submission Context: EMSL shipping required

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#868]
Shipping information for EMSL should be required not optional.

**Comment by naglepuff** [comment]
@mslarae13 Are there any fields on the shipping form that are NOT required? (I imagine Address Line 2 is optional. Anything else?)

**Comment by mslarae13** [comment]
![Screen Shot 2023-03-02 at 7 13 43 PM](https://user-images.githubusercontent.com/44581429/222622411-df0b6431-3ee0-4136-9a51-99559bbe6580.png)
![Screen Shot 2023-03-02 at 7 14 34 PM](https://user-images.githubusercontent.com/44581429/222622412-a70eb686-a392-429b-94eb-bdd58205140a.png)

**Comment by mslarae13** [comment]
Is it possible to make something required on the prod website, but not on sandbox?
@naglepuff

**Comment by naglepuff** [comment]
I believe that it would be possible, but not necessarily trivial. What's the use case/urgency for this behavior?

**Comment by mslarae13** [comment]
not urget, just annoying when I'm testing.

It took me a minute to realize I couldn't move onto the next step without completing the EMSL shipping.

Can you make the box red so it's obvious it isn't validated?

@naglepuff
