### ISSUE TITLE
Submission Context: EMSL IRB/HIPPA

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#870]
IRP/HIPPA should be IRB/HIPPA Compliance? (this was a typo in the EMSL sheet)
Can remove the IRB form that appears with BSL2.
Just need the check box

![Screen Shot 2023-02-27 at 8 16 26 PM](https://user-images.githubusercontent.com/44581429/221752623-2355bffd-c395-48db-9f8b-9c6f11f8108a.png)

**Comment by naglepuff** [comment]
> Can remove the IRB form that appears with BSL2.

@mslarae13 So this part of the form is not needed at all? Or should it appear only when the checkbox is checked? Just want to make sure.

**Comment by mslarae13** [comment]
It doesn't need to appear at all. EMSL virtually never gets IRB samples so if we ever do we will need to just check in with our rep and that's where they'll get the form.
