### ISSUE TITLE
Multiomics: Update JGI Proposal ID text

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#878]
<img width="1063" alt="Screen Shot 2023-03-02 at 1 46 32 PM" src="https://user-images.githubusercontent.com/79225425/222564913-46673ff6-18da-4573-a03a-0359d801c1db.png">

@mslarae13 please confirm this is correct?

**Comment by mslarae13** [comment]
In both the text on the line & the text in the box

**Comment by ssarrafan** [comment]
tested on data-dev and it's updated based on requirement
<img width="760" alt="Screen Shot 2023-03-14 at 3 48 45 PM" src="https://user-images.githubusercontent.com/79225425/225159255-6aa20656-5437-4fb5-99aa-32b52739bf6f.png">
