### ISSUE TITLE
Make submission portal submissions list sortable

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-server#884]
Can we add (back) the ability to sort submissions

<img width="1228" alt="Screen Shot 2023-03-06 at 8 01 37 PM" src="https://user-images.githubusercontent.com/44581429/223317759-0d90605a-d84f-451c-8248-bf5383fdbd31.png">

**Comment by ssarrafan** [comment]
@mslarae13 assuming this is ok to add to post GSP board?

**Comment by ssarrafan** [comment]
@marySalvi mentioned that she was still working on this and it needed to be reviewed so will add to the new sprint.
