### ISSUE TITLE
1000 soils metadata into Data portal

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/nmdc-server#886]
Ingesting https://data.microbiomedata.org/submission/a2c2b0e9-ea12-4742-a597-59b3dcc1997f/study , "1000-Soils Metadata for GSP" for GSP.

See https://github.com/microbiomedata/issues/issues/120 

Script to convert submission portal records for ingest is being work on. 

Here is the information that will be needed for the study landing page.
Note, some of this information will be pulled from GOLD, as there is a GOLD study and a few of the samples have data & metadata in GOLD, see https://github.com/microbiomedata/issues/issues/85 

This is for updating and adding to the study landing page.
See (InProgress): https://docs.google.com/document/d/110MzrV7-3VyQ-oOK7kx_RHIwmGtQ7Hu41gpMBIflVPM/edit?usp=sharing

For the external data links to see here: 
<img width="728" alt="Screen Shot 2023-03-07 at 10 57 16 AM" src="https://user-images.githubusercontent.com/44581429/223523456-c084ffc2-b69e-408a-a0f8-7285fa657a32.png">

please add https://www.emsl.pnnl.gov/project/60141
with this logo
![EML_Logo-Light](https://user-images.githubusercontent.com/44581429/223523566-f33d9bd6-ec50-4af8-8bf8-7451c727a4da.png)

**Comment by mslarae13** [comment]
Currently blocked. Waiting on information from PM and metadata converstion

**Comment by naglepuff** [comment]
So this new study will have a GOLD ID and an EMSL ID?

Is there a slot in the schema where the EMSL project ID will go?

**Comment by ssarrafan** [comment]
> So this new study will have a GOLD ID and an EMSL ID?
> 
> Is there a slot in the schema where the EMSL project ID will go? _edit: looks like this should come from the `emsl_project_identifier` slot_

@aclum @emileyfadrosh  can you confirm in Montana's absence?

**Comment by aclum** [comment]
Yes, that is correct.

**Comment by ssarrafan** [comment]
@aclum should this issue be moved to the next sprint or to the post-GSP board?

**Comment by aclum** [comment]
I think this is still blocked on metadata conversion, I haven't see a biosample_set json for submission to mongo yet. @mslarae13  to confirm.

**Comment by aclum** [comment]
@mslarae13  @mslarae13 @lamccue 1000 soils study page will be ready to review on the next data portal dev ingest. Biosamples are already on dev data portal. 
https://data-dev.microbiomedata.org/details/study/nmdc:sty-11-28tm5d36
 (it will be entirely blank until the next ingest)

**Comment by aclum** [comment]
dev data portal page looks good so closing this.
