### ISSUE TITLE
Growth facility not validating correctly

### ISSUE THREAD

**Issue by naglepuff** [microbiomedata/nmdc-server#910]
@pkalita-lbl I started seeing an issue last week after #903 was merged. Validation appears to be broken for the `growth_facility` column in the data harmonizer. The following screenshot is from the dev data portal.

![growth_facility_validation](https://user-images.githubusercontent.com/7085625/227973616-420c55dc-04b8-4726-b7c6-fdc31d0f1082.png)

I've tried validating with every enum value.

Setting a breakpoint, after calling `await harmonizerApi.validate()` ([here](https://github.com/microbiomedata/nmdc-server/blob/00f78691039fb071f5507165fced15cfff242d1f/web/src/views/SubmissionPortal/HarmonizerView.vue#L161)) the value of `result` is 
```
{
  0: { 68: "" }
}
```

Thought you might have an idea of what's happening here. If this issue should be moved somewhere, please let me know.

**Comment by pkalita-lbl** [comment]
Thanks I'll take a look
