### ISSUE TITLE
Add pagination to the studies on the data portal

### ISSUE THREAD

**Issue by naglepuff** [microbiomedata/nmdc-server#914]
Currently we display all studies as one long list. Eventually, when the number of studies makes scrolling to the samples cumbersome, we'll want to add pagination.

**Comment by mslarae13** [comment]
+1 for that! Maybe just show 5 to start, and adding a show all button would be good

**Comment by aclum** [comment]
@marySalvi are you picking this ticket up while Mike is out next week or should we remove this issue from the sprint?

**Comment by jeffbaumes** [comment]
This will need to go to the next sprint as @marySalvi is working to complete a few other sprint tasks and @naglepuff is not back until next week.

**Comment by aclum** [comment]
Removing from the sprint in favor of fixing collection date bug  #928

**Comment by ssarrafan** [comment]
Active issue, moving to new sprint.

**Comment by marySalvi** [comment]
Yes! So very close!
