### ISSUE TITLE
class biosample ecosystem slots are required by the data portal but are not by the nmdc schema

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#930]
While ingesting data that did not derive from GOLD we learned that the current data portal ingest requires that the follow slots exist for class Biosample
```
ecosystem
ecosystem_category
ecosystem_type
ecosystem_subtype
specific_ecosystem
```
Based on the [nmdc schema documentation for class Biosample](https://microbiomedata.github.io/nmdc-schema/Biosample/) these are not required. 
The desired behavior is that the GOLD classification filter tree in the data portal displays even if biosamples don't have these slot specified. See related issue https://github.com/microbiomedata/nmdc-server/issues/926

cc @shreddd @turbomam

**Comment by naglepuff** [comment]
@aclum it it functionally the same for a biosample to have "Unclassified" in one of these slots and a biosample to not have the slot populated at all?

In other words, should biosamples without these slots be included in the "Unclassified" counts?

**Comment by aclum** [comment]
It would be a more accurate representation of what is in mongo and the schema to keep these separate. If slots are "Unclassified" there would still be an expectation that there was a slot name and value in a json document.  Because these slots aren't required by the schema that won't be the case.

**Comment by ssarrafan** [comment]
@marySalvi discussed updates on this issue at the infra sync 6/15/23.  Will move to the next sprint for final resolution.

**Comment by ssarrafan** [comment]
@marySalvi can this issue be closed yet?

**Comment by marySalvi** [comment]
I need Mike to do a review before I am comfortable merging my PR. I will ping him Monday morning and ask him to prioritize.
