### ISSUE TITLE
study page link to omics procesing set records does not filter studies correctly

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#933]
From a study page the link to sample count filters correctly but the link to omics processing records doesn't at the study level correctly. Based on how the search is being done the difference is a id [is] $nmdc_study_id vs study id is $nmdc_study_id see attached screenshots. id [is] produces the desired behavior, study id [is] does not produce the desired behavior.
![study id vs id from study page](https://user-images.githubusercontent.com/8196591/230230767-3f2b92b7-427a-4926-b86d-bfcdeeb76139.png)
![id as filter](https://user-images.githubusercontent.com/8196591/230230774-2b969671-76ef-4290-9430-3dddb484e554.png)
![study id as filter](https://user-images.githubusercontent.com/8196591/230230779-93d5519b-e172-44a3-84ab-209b055f24e9.png)

Created a new issue to separate concerns from https://github.com/microbiomedata/issues/issues/168

**Comment by ssarrafan** [comment]
@aclum is this a post-GSP item?

**Comment by aclum** [comment]
@ssarrafan  yes, this is fine to be post-GSP is there is not time to fix this week.

**Comment by naglepuff** [comment]
Note the difference between:
https://github.com/microbiomedata/nmdc-server/blob/4b9399a8a43340ec0af1fd8fb03125021059ba6f/web/src/views/IndividualResults/StudyPage.vue#L128-L135

And 
https://github.com/microbiomedata/nmdc-server/blob/4b9399a8a43340ec0af1fd8fb03125021059ba6f/web/src/views/IndividualResults/StudyPage.vue#L108-L126
