### ISSUE TITLE
Ontology url links in submission portal help menus not working

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#945]
Links in the help menu in the submission portal to  http://purl.obolibrary.org/obo/ are being truncated. An example field is broad-scale environmental context. Any columns that have links to purl.obolibrary.org (ie soil type, broad-scale environmental context, environmental medium)
![sub port help menu issue](https://user-images.githubusercontent.com/8196591/230678778-d06f4b16-3e88-404f-a397-cea634a2467a.png)

@mslarae13 mentioned this may be a regression from the schema sync and the sheets and friends info was lost.

cc @pkalita-lbl 

Using chrome version 112.0.5615.49

**Comment by aclum** [comment]
duplicate of https://github.com/microbiomedata/nmdc-server/issues/820

**Comment by aclum** [comment]
@naglepuff Is it possible to fix the help menu? @pkalita-lbl said this is different that the pop-up box which is controlled by Data Harmonizer which is what Montana reported in https://github.com/microbiomedata/nmdc-server/issues/820

**Comment by pkalita-lbl** [comment]
I'm working on this now.
