### ISSUE TITLE
ess dive identifier links are broken

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#951]
I think the fixes that happened last week impacted the ess-dive idnetifiers. I spot checked and massive looks good so i think the problem is limited to ess-dive identifiers 
the link should be to https://data.ess-dive.lbl.gov/view/doi:10.15485/1603775 instead of https://identifiers.org/https://data.ess-dive.lbl.gov/view/doi:10.15485/1603775

slot
[ess_dive_datasets](https://microbiomedata.github.io/nmdc-schema/ess_dive_datasets/)

**Comment by naglepuff** [comment]
Which study is affected? Is it all of them?

**Comment by aclum** [comment]
<img width="1587" alt="Screenshot 2023-04-12 at 12 12 07 PM" src="https://user-images.githubusercontent.com/8196591/231574180-c2f1de16-630b-482d-9bb4-e551ab6463d7.png">

**Comment by naglepuff** [comment]
https://data-dev.microbiomedata.org/details/study/gold:Gs0135149
ESS-DIVE identifiers looks good here

https://data-dev.microbiomedata.org/details/study/nmdc:sty-11-5tgfr349
ESS-DIVE identifiers don't look good here

Looks like the new study with id `nmdc:sty-11-5tgfr349` has urls starting with `"https//data.ess-dive.lbl.gov/..."`, whereas study `gold:Gs0135149` just has DOIs. From the data portal side, this is fixable if we do some parsing of these strings before displaying them, however it would be nicer if we knew exactly what to expect, and the source (mongo) was consistent. Looks like the schema allows for ANY string here, so the source mongo is currently valid, but I do have reservations about implementing complex logic/pattern matching to change behavior unless strictly necessary.

I'm certainly open to further discussion about this. @aclum

**Comment by aclum** [comment]
Looks like the two studies that have these ids used different formats so we'll need to be consistent. 
This study resolves correctly
https://data.microbiomedata.org/details/study/gold:Gs0135149
This one does not
https://data.microbiomedata.org/details/study/nmdc:sty-11-5tgfr349

**Comment by aclum** [comment]
@naglepuff  let me know if I should fix the data in mongo but then you'd have to do another ingest

**Comment by naglepuff** [comment]
@aclum I think that's the best way to resolve this, so sure. If that's done before 5PM EDT I can have the data ingested into dev for verification of our approach. Then tomorrow if the problem is indeed solved, I'll ingest to prod and we can close this issue or figure out how to prevent this from happening again.

**Comment by aclum** [comment]
Fixed on prod mongo and prod data portal.
