### ISSUE TITLE
data portal ingest code update to support for new nmdc classes

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#966]
This is a placeholder ticket until schema details are sorted out. 

For NEON soil samples we plan to use Class: ProcessedSample for the first time. I believe at a minimum in order for this to work on the data portal side the nmdc-server code would need to be updated to make postgres database joins between biosample_set records, processed_sample_set records,and omics_processing_set records by looking at Classes that inherit from PlannedProcesses (Pooling, Extraction, LibraryConstruction) 

Dependent on [pooling process being supported by nmdc-schema
](https://github.com/microbiomedata/nmdc-schema/issues/886)
Dependent on https://github.com/microbiomedata/nmdc-schema/issues/906
Dependent on https://github.com/microbiomedata/nmdc-schema/issues/908

Example:
`biosample_set` `id` `nmdc:bsm-11-k249h697`, `nmdc:bsm-11-k249h698`, `nmdc:bsm-11-k249h699` go through process X which generates `processed_sample_set` `id` `nmdc:psm-11-j324h942`. Processed sample `nmdc:psm-11-j324h942` is an input to a extraction_set record which generates output `nmdc:psm-11-j324h943`. Processed sample `nmdc:psm-11-j324h943` is the value for has_inputs in a library_preparation_set record, generating nmdc:psm-11-j324h944`. 'nmdc:psm-11-j324h944` is the value of has_outputs in a library_preparation_set. 
`omics_processing_set` `id` `nmdc:omprc-11-68k0tc36`  slot `has_input` has a value of `nmdc:psm-11-j324h944`

**Comment by aclum** [comment]
I've uploaded some test data in mongo dev, the full example record was provided via slack. Starting biosample_set ids are `nmdc:bsm-99-abcdef1`, `nmdc:bsm-99-abcdef2`, [nmdc:bsm-99-abcdef3](url) which ultimately feed into omics_processing_set id `nmdc:omprc-11-s9xj2r24`

**Comment by ssarrafan** [comment]
Moving to next sprint. This is in progress per the infra sync meeting yesterday.

**Comment by ssarrafan** [comment]
@naglepuff @aclum 906 and 908 reference above are closed. Can this issue be resolved and closed by tomorrow?

**Comment by naglepuff** [comment]
Unlikely that it will be resolved by tomorrow, but it shouldn't be too long before this is complete. Early-mid week next week would be reasonable.

**Comment by aclum** [comment]
This work is complete.
