### ISSUE TITLE
ORCID Integration Information

### ISSUE THREAD

**Issue by naglepuff** [microbiomedata/nmdc-server#970]
From ORCID feedback:

> As a part of the authentication login integration screen, include information as to how/why you will be connecting to ORCID and using their information; essentially, provide an explanation of the integration and how/why you are collecting ORCID iDs.

@shreddd  how do you interpret this feedback from the email? It sounds like we need to add an explanation to the oauth login screen, but I'm not sure how to do this. Unless you have a different idea or better understanding of this, I think it would be good to get some clarification from ORCID and maybe some examples of websites that comply with this.

> If you are writing to records, include an explanation of your integration and the benefits of connecting your information to the researcher’s ORCID record, in particular, the auto-update feature if applicable

Currently, we don't write to ORCID records.

>  If you use webhooks (the synchronize feature), include an explanation of your integration and the benefits of synchronization.

We don't use webhooks either.

> If you are reading records, include an explanation of your integration and the benefits of collecting information from the researchers record.

> Specify Scopes used to write on Record: activities/update and/or person/update.

We know why we're collecting information, and we know we want to use the read-limited scope.

From the initial demo meeting with ORCID, I remember discussing adding some kind of FAQ page to the data portal with this information would suffice. I think the next steps would be to get clarification that this is a good approach, and then design and implement something to fill this need, ensuring that it is easily discoverable for users.

**Comment by naglepuff** [comment]
While adding ORCID branding in #829, I came across this bit from the [ORCID branding guidelines page](https://info.orcid.org/brand-guidelines/):

![image](https://github.com/microbiomedata/nmdc-server/assets/7085625/98ac6ff6-7589-4821-87d7-1463325b5cc5)

Particularly of note is the last paragraph. We currently have fields in the submission portal for users to enter ORCID IDs for study contributors. I think we should get more guidance from ORCID folks on this. Since we are using these fields to populate a database, and not as a login form, maybe this use case is an exception. In either case, there is no guidance about how to conform to branding best practices on such a form.

**Comment by jeffbaumes** [comment]
> Particularly of note is the last paragraph. We currently have fields in the submission portal for users to enter ORCID IDs for study contributors. I think we should get more guidance from ORCID folks on this. Since we are using these fields to populate a database, and not as a login form, maybe this use case is an exception. In either case, there is no guidance about how to conform to branding best practices on such a form.

I don't think this should be a blocker. I read this more of not associating an ORCID *login* by entering the ID manually, but with what we're doing I can't see another way to enter role information without specifying ORCIDs manually.

**Comment by ssarrafan** [comment]
> > Particularly of note is the last paragraph. We currently have fields in the submission portal for users to enter ORCID IDs for study contributors. I think we should get more guidance from ORCID folks on this. Since we are using these fields to populate a database, and not as a login form, maybe this use case is an exception. In either case, there is no guidance about how to conform to branding best practices on such a form.
> 
> I don't think this should be a blocker. I read this more of not associating an ORCID _login_ by entering the ID manually, but with what we're doing I can't see another way to enter role information without specifying ORCIDs manually.

I did send an email to our ORCID contact to get clarification on this last week but I haven't heard anything back.  FYI.

**Comment by ssarrafan** [comment]
_Response from ORCID team (also emailed to Mike and Jeff this week):
Hi, Setareh,

 

Apologies on the delayed response, I was out of office a bit this week.

 

It’s ORCID’s recommended best practice to authenticate any ORCID ids that are input into your systems (as opposed to manually typing them in), as that will prevent data integrity issues (e.g., mistypes, misattributions, etc.).

 

To read more about the best practices with ORCID ids – I’d recommend investigating the authentication workflows:

·         https://info.orcid.org/documentation/integration-and-api-faq/

o   There are resources for “How do I collect an authenticated ORCID ID” using OAuth or SSO workflows - https://info.orcid.org/documentation/api-tutorials/api-tutorial-get-and-authenticated-orcid-id/

 

I’m happy to discuss further or answer additional questions regarding authentication practices.

 

Thanks,

 

Mary Beth West

 

Mary Beth West

USDOE/OSTI_

**Comment by ssarrafan** [comment]
@naglepuff any update on this? Asking for the quarterly report.

**Comment by naglepuff** [comment]
@ssarrafan I just merged a PR that updates the data portal to adhere to style guidelines when displaying ORCID IDs, which should be in dev. I haven't addressed other ORCID feedback yet.

**Comment by ssarrafan** [comment]
Moving to next sprint, Mike is out, this is in review.

**Comment by ssarrafan** [comment]
@naglepuff reported updates on this issue. I'lll move to next sprint for completion.  
FYI @shreddd

**Comment by ssarrafan** [comment]
Moving this to next sprint since Mike is out today. Let me know if this should go in the backlog. @naglepuff

**Comment by ssarrafan** [comment]
@naglepuff what's the status of this issue?  Are you still actively working on this?

**Comment by ssarrafan** [comment]
Active per @naglepuff on Slack. Moving to next sprint.
