### ISSUE TITLE
data portal ui updates to support pooled soil samples

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#975]
Base on the infrastructure meeting we had the following ideas about how the data portal UI could support biosamples which are pooled for further processing for ESA
- [ ] on biosample pages show or link to related samples
- [ ] for WorkflowExecutionActivity records show/link to other contributing samples 

Depends on https://github.com/microbiomedata/issues/issues/260

**Comment by mslarae13** [comment]
@aclum are we ready to discuss this at the infrastructure sync? Since the classes are there, can Kitware start sorting this out?

**Comment by aclum** [comment]
@mslarae13  We can discuss but are limited until the schema sync https://github.com/microbiomedata/issues/issues/261 is complete.

**Comment by ssarrafan** [comment]
Mike is out till next week but assuming this is still a priority, adding to Zoe sprint. @naglepuff @aclum

**Comment by ssarrafan** [comment]
new schema version released today, assuming this is still a priority for the next sprint @aclum ?

**Comment by aclum** [comment]
This is still blocked on the data portal ingest code being updated but should be in this sprint as Mike thinks he can have that done early this week.
