### ISSUE TITLE
data portal - show biosample_catagories on biosample landing page 

### ISSUE THREAD

**Issue by aclum** [microbiomedata/nmdc-server#976]
**Deliverable this task is associated with**

_See Deliverables tab here: https://docs.google.com/spreadsheets/d/1jF1RU_TwQlJpqvHnKk-KieE6VlUv0je4eFddK9idPuE/edit?usp=sharing_

- 7

**RACI**

_Tag people in their roles_
- Responsible: @naglepuff 
- Accountable: @jeffbaumes, @mslarae13 
- Consulted: @mslarae13 
- Informed: 

**Describe the the task?**
- [ ] show[ biosample_categories](https://microbiomedata.github.io/nmdc-schema/biosample_categories/) biosample pages 

**Criteria for completion**
- data portal dev for an example biosample shows a biosample with the the values (multivalued) for biosample_catagories. 

**Estimate people time**
- 

**Completion Date (Goal)**
- July 14

**Target Sprint Start & End Dates**
- Start:
- End:

**Tag Blocker/Contingent upon isues**
No nmdc-schema changes required, changesheets could be used on an existing sample to test this.

**Comment by mslarae13** [comment]
contingent upon

- Other NEON biosamples in mongo need identified and tagged. https://github.com/microbiomedata/issues/issues/276

**Comment by aclum** [comment]
@mslarae13 to provide one example record, will use changesheets to update a biosample_set record from the 1000 soils study.

**Comment by ssarrafan** [comment]
@aclum @mslarae13 should this still be assigned to Mike? Still a priority?

**Comment by aclum** [comment]
1000 soils biosamples from NEON sites are now tagged. An example biosample id for @naglepuff is nmdc:bsm-11-bsf8yq62

We would like this for ESA but this has to come after incorporating the new processing classes (https://github.com/microbiomedata/issues/issues/261 and https://github.com/microbiomedata/nmdc-server/issues/975)

**Comment by naglepuff** [comment]
This can be moved in the next spring.

**Comment by naglepuff** [comment]
Closed by #1004
