### ISSUE TITLE
Create annotated study page screenshot which maps page elements to schema slots

### ISSUE THREAD

**Issue by jeffbaumes** [microbiomedata/nmdc-server#978]

**Comment by ssarrafan** [comment]
@jeffbaumes can we consider this issue closed per https://github.com/microbiomedata/nmdc-server/blob/ingest-data-guide/docs/study_page_annotations.md

**Comment by ssarrafan** [comment]
I am moving to the next sprint since Jeff shared this and got some feedback at the infra sync meeting 6/15/23.

**Comment by ssarrafan** [comment]
@jeffbaumes @naglepuff what's the status of this issue?  Can we close this?

**Comment by mslarae13** [comment]
@naglepuff  completed this page: https://github.com/microbiomedata/nmdc-server/blob/ingest-data-guide/docs/study_page_annotations.md

I think he was planning to do a couple more to get the other fields that exist mapped... ones that aren't on this page. Correct @naglepuff ?

**Comment by ssarrafan** [comment]
Since Mike is out till next week I'll move this to the next sprint so he can respond and close out. @naglepuff @mslarae13
