### ISSUE TITLE
Study page update - Design ESA updates of study landing page

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/nmdc-server#989]

**Comment by ssarrafan** [comment]
@mslarae13 is there any update on this issue?  Does Faiza have what she needs to get started on this?

**Comment by mslarae13** [comment]
They met last week but I missed, so not sure! I will cehck in with Lee Ann & team next week

**Comment by faiza-a** [comment]
@ssarrafan @mslarae13  We met Tuesday this week. Lee Ann shared some of her ideas and we decided to brainstorm those and discuss further next week. We also agreed that only a few changes including some textual changes and making multi value from the DOI will be done by this ESA, remaining major changes will be part of after ESA.

**Comment by ssarrafan** [comment]
Thanks @faiza-a 
I'll close this issue
New issue will be opened for after ESA
